import {
  Bell,
  Building2,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Command,
  Factory,
  FileText,
  Gavel,
  LayoutGrid,
  Library,
  Lock,
  LogOut,
  Map,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Radar,
  Search,
  Shield,
  ShieldCheck,
  Sparkles,
  Sun,
  TriangleAlert,
  User,
  UserCog,
  Video,
  Workflow,
  X,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutGrid,
  radar: Radar,
  factory: Factory,
  calendar: CalendarDays,
  visits: ClipboardList,
  inspect: ShieldCheck,
  virtual: Video,
  review: ClipboardCheck,
  admin: Shield,
  library: Library,
  forms: FileText,
  enforcement: Gavel,
  workflow: Workflow,
  risk: TriangleAlert,
  map: Map,
  access: UserCog,
  notify: Bell,
  ai: Sparkles,
  search: Search,
  account: CircleUser,
  identity: User,
  signOut: LogOut,
  organisation: Building2,
  themeLight: Sun,
  themeDark: Moon,
  themeSystem: Monitor,
  openNavigation: Menu,
  dismiss: X,
  disclosure: ChevronDown,
  selected: Check,
  previousPage: ChevronLeft,
  nextPage: ChevronRight,
  collapseRail: ChevronLeft,
  restricted: Lock,
  regionScope: MapPin,
  dateScope: CalendarDays,
  commandPalette: Command,
} as const;

export type IconName = keyof typeof ICONS;
