#!/usr/bin/env python3
"""
Figma coverage against the GOVERNED SCREEN CATALOGUE.

PO decision 2026-07-31: `product-contract/screens/screen_route_catalogue.csv` is the
requirement source for Figma scope. Jira is not reachable from Claude Code in this
project (no Atlassian MCP auth, no CLI, no token), and only `INSP-1` appears anywhere
in the repo — so the catalogue, which is traced to REQUIREMENT_INDEX.csv (2,263 atomic
requirements) under SOURCE_AUTHORITY.yaml, is what we build against.

A screen is in scope for Figma ONLY if it has a row here. No row, no screen — this is
the guard against inventing surfaces.

  python3 docs/design/figma/coverage-matrix.py   ->  docs/design/figma/COVERAGE-MATRIX.md
"""
import csv, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT = ROOT / "docs/design/figma"

cat = list(csv.DictReader(open(ROOT / "product-contract/screens/screen_route_catalogue.csv", encoding="utf-8")))

# What Figma actually holds. The six /admin/* frames render the RBAC refusal state,
# which is faithful to final-cut but is not admin UI.
FIGMA = {
    # web routes built in the original 16-frame matrix
    "/dashboard", "/operations", "/factory-360", "/planning", "/execution", "/reviews",
    "/compliance", "/enforcement-library", "/compliance/approvals", "/analytics",
    "/admin/localization", "/admin/integrations",
    # admin screens built on the ad-* shell against their catalogue contracts
    "/admin", "/admin/regulations", "/admin/regulations/[id]", "/admin/items",
    "/admin/packages", "/admin/packages/[id]/designer", "/admin/violations",
    "/admin/penalties", "/admin/workflows", "/admin/workflows/[id]", "/admin/risk",
    "/admin/gis", "/admin/notifications", "/admin/access",
    # web screens built from their .dc.html sources + catalogue contracts
    "/visits", "/visits/[id]", "/reviews/[id]", "/factories/[id]/360",
    "/planning/bulk", "/planning/single", "/planning/immediate",
    "/planning/bulk/review", "/planning/[id]/review",
    # virtual channel screens built from their catalogue contracts
    "/virtual/appointments/[id]", "/virtual/sessions/[id]/verify", "/virtual/[id]",
}
# only these two still render the RBAC refusal state; the rest were rebuilt on the ad-* shell
REFUSAL = {"/admin/localization", "/admin/integrations"}
# PWA/iPad is out of scope by PO ruling 2026-07-31
OUT_OF_SCOPE_CHANNELS = {"iPad"}

def norm(route):
    return route.replace(":id", "[id]").split("?")[0].rstrip("/") or "/"

rows = []
for r in cat:
    route = norm(r["route"])
    in_figma = route in FIGMA
    real = in_figma and route not in REFUSAL
    rows.append({
        "id": r["screen_id"], "channel": r["channel"], "route": route,
        "screen": r["screen"], "purpose": r["purpose"], "personas": r["personas"],
        "regions": r["mandatory_regions"], "actions": r["primary_actions"],
        "states": r["states"], "permission": r["permission_rule"], "scope": r["scope"],
        "figma": "real UI" if real else ("refusal state only" if in_figma else "MISSING"),
        "in_scope": r["channel"] not in OUT_OF_SCOPE_CHANNELS,
    })

in_scope = [r for r in rows if r["in_scope"]]
have = [r for r in in_scope if r["figma"] == "real UI"]
missing = [r for r in in_scope if r["figma"] != "real UI"]

L = []
L.append("# Figma coverage vs the governed screen catalogue\n")
L.append("Generated by `docs/design/figma/coverage-matrix.py`.\n")
L.append("**Requirement source (PO decision 2026-07-31):** "
         "`product-contract/screens/screen_route_catalogue.csv` — traced to "
         "`REQUIREMENT_INDEX.csv` (2,263 atomic requirements) under `SOURCE_AUTHORITY.yaml`.\n")
L.append("> Jira is **not reachable** from Claude Code in this project — no Atlassian MCP auth, "
         "no CLI, no token; only `INSP-1` appears in the repo. If Jira access is granted, "
         "re-validate this catalogue against it.\n")
L.append("**A screen is in Figma scope only if it has a row here.** No row, no screen.\n")

L.append("## Headline\n")
L.append(f"- Governed screens: **{len(rows)}**")
L.append(f"- Out of scope (iPad channel, PO ruling): **{len(rows)-len(in_scope)}**")
L.append(f"- In scope: **{len(in_scope)}**")
L.append(f"- With real Figma UI: **{len(have)}**")
L.append(f"- **Missing: {len(missing)}**\n")

L.append("## In scope, no Figma UI\n")
L.append("| Screen ID | Channel | Route | Screen | Purpose | Figma |")
L.append("|---|---|---|---|---|---|")
for r in sorted(missing, key=lambda x: x["id"]):
    purpose = r["purpose"].replace("|", "·")[:90]
    L.append(f"| `{r['id']}` | {r['channel']} | `{r['route']}` | {r['screen']} | {purpose} | {r['figma']} |")

L.append("\n## Built and governed\n")
for r in sorted(have, key=lambda x: x["id"]):
    L.append(f"- `{r['id']}` — `{r['route']}` — {r['screen']}")

L.append("\n## Figma frames with NO catalogue row\n")
L.append("These exist in Figma but no governed screen requires them. Either the catalogue is "
         "incomplete or the frame is unjustified — resolve before treating Figma as canonical.\n")
cat_routes = {norm(r["route"]) for r in cat}
for f in sorted(FIGMA - cat_routes):
    L.append(f"- `{f}`")

L.append("\n## Build order for the missing screens\n")
L.append("Each row below carries its own `mandatory_regions`, `primary_actions`, `states` and "
         "`permission_rule` in the catalogue — build to those, not to inference.\n")
for r in sorted(missing, key=lambda x: x["id"]):
    L.append(f"\n### {r['id']} — {r['screen']} (`{r['route']}`)")
    L.append(f"- **Purpose:** {r['purpose']}")
    L.append(f"- **Personas:** {r['personas']}")
    L.append(f"- **Mandatory regions:** {r['regions']}")
    L.append(f"- **Primary actions:** {r['actions']}")
    L.append(f"- **States:** {r['states']}")
    L.append(f"- **Permission:** {r['permission']}")

(OUT / "COVERAGE-MATRIX.md").write_text("\n".join(L) + "\n")
print(f"governed screens : {len(rows)}")
print(f"  out of scope   : {len(rows)-len(in_scope)} (iPad)")
print(f"  in scope       : {len(in_scope)}")
print(f"  real Figma UI  : {len(have)}")
print(f"  MISSING        : {len(missing)}")
print(f"figma frames with no catalogue row: {len(FIGMA - cat_routes)}")
print(f"wrote {OUT/'COVERAGE-MATRIX.md'}")
