// Governed KPI registry — traceable definition for EVERY metric in
// SAQEEL_Dashboard_KPI_Admin_Configuration_Matrix.xlsx and the CODEX 01 spec
// (12 strategic + 9 operational + 7 inspector = 28 metrics).
//
// This registry is the code-side mirror of the seeded rows in
// public.mvp3_kpi_definitions (see migration
// 20260721010000_dashboard_kpi_admin_foundation.sql). The formula text and
// metricId are IMMUTABLE to ordinary admins — only tested code releases change
// them. Admins may only edit approved parameters via the Dashboard
// Configuration engine.
//
// `implementation` records what the shared projection can deliver TODAY against
// the live schema. Where a required source field/table or governance decision
// is missing, the metric is honestly marked and the projection emits an
// unavailable/not_configured/decision_required SharedMetric rather than a
// fabricated value.

import type { MetricCategory, MetricImplementationStatus, MetricUnit } from "./contract";

export type KpiDefinition = {
  metricId: string;
  category: MetricCategory;
  /** Short stable key, mirrors mvp3_kpi_definitions.metric_key. */
  metricKey: string;
  titleEn: string;
  titleAr: string | null;
  unit: MetricUnit;
  formulaVersion: string;
  /** Human-readable governed formula (immutable to admins). */
  formula: string;
  /** Denominator rule, or "n/a" when the metric is a plain count/category. */
  denominatorRule: string;
  /** Default drill route; filters resolved at projection time. */
  drillRoute: string | null;
  /** Owning admin role for policy parameters (roles.role_key). */
  ownerRole: string;
  implementation: MetricImplementationStatus;
  /** Why not fully implemented, or the governance note when implemented. */
  note: string;
  /** Open decision / stop-line id when relevant. */
  decisionRef: string | null;
  /** Matrix requirement id for traceability. */
  matrixRef: string;
};

export const KPI_DEFINITIONS: readonly KpiDefinition[] = [
  // ---------------------------------------------------------------- STRATEGIC
  {
    metricId: "STR-KPI-001",
    category: "strategic",
    metricKey: "compliance_rate_trend",
    titleEn: "Compliance rate trend",
    titleAr: "اتجاه معدل الامتثال",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "compliant eligible answers / (compliant + non_compliant); exclude na, unknown, incomplete",
    denominatorRule: "compliant + non_compliant eligible answers in scope",
    drillRoute: "/analytics/compliance",
    ownerRole: "leadership",
    implementation: "implemented",
    note: "Uses the canonical countChecklistCompliance. Value = Compliant/(C+NC) per the metric title and worked example. Excel formula TEXT ('non-compliant / total') contradicts its own example; recorded as a stop-line decision.",
    decisionRef: "DEC-DASH-001",
    matrixRef: "STR-KPI-001",
  },
  {
    metricId: "STR-KPI-002",
    category: "strategic",
    metricKey: "risk_distribution",
    titleEn: "Risk distribution",
    titleAr: "توزيع المخاطر",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "distinct eligible factories grouped by current governed Health Score band",
    denominatorRule: "all eligible factories with a current governed Health Score band",
    drillRoute: "/analytics/health",
    ownerRole: "leadership",
    implementation: "unavailable",
    note: "dashboard.xlsx explicitly groups this measure by Health Score band. No Health Score snapshot/history source exists; factories.risk_score/risk_band belongs to the separate Risk Engine and is not substituted.",
    decisionRef: "DEC-DASH-002",
    matrixRef: "STR-KPI-002",
  },
  {
    metricId: "STR-KPI-003",
    category: "strategic",
    metricKey: "violation_trend_regulation_severity",
    titleEn: "Violation trend by regulation and severity",
    titleAr: "اتجاه المخالفات حسب اللائحة والخطورة",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count official violations by governed issue date, grouped by period, regulation and severity",
    denominatorRule: "n/a",
    drillRoute: "/analytics/violations",
    ownerRole: "compliance_admin",
    implementation: "decision_required",
    note: "By-regulation grouping is computable, but violations has NO issue-time column. Time-series-by-official-issue-time cannot be produced without silently substituting submission time, which is prohibited. Severity vocab (L1/L2 vs medium) is also unnormalized.",
    decisionRef: "DEC-DASH-003",
    matrixRef: "STR-KPI-003",
  },
  {
    metricId: "STR-KPI-004",
    category: "strategic",
    metricKey: "level2_decision_mix",
    titleEn: "Level-2 Approve / Return / Reject mix",
    titleAr: "مزيج قرارات المستوى الثاني: اعتماد / إعادة / رفض",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "latest decided Level-2 outcome per submitted inspection, grouped Approve/Return/Reject",
    denominatorRule: "all latest decided Level-2 outcomes in scope",
    drillRoute: "/reviews",
    ownerRole: "compliance_admin",
    implementation: "implemented",
    note: "Latest review per inspection only. This is a decision mix and is NOT compliance — kept strictly separate from STR-KPI-001.",
    decisionRef: null,
    matrixRef: "STR-KPI-004",
  },
  {
    metricId: "STR-KPI-005",
    category: "strategic",
    metricKey: "licence_exposure",
    titleEn: "Licence exposure",
    titleAr: "التعرض لانتهاء التراخيص",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "distinct eligible factory licences by expiry state as of reporting date (Asia/Riyadh)",
    denominatorRule: "all eligible active industrial licences",
    drillRoute: "/factories",
    ownerRole: "leadership",
    implementation: "unavailable",
    note: "The live industrial_licenses source is confirmed. The governed expiring-soon lead days remain an unconfigured Admin policy, so expired-only data is not substituted for this combined metric.",
    decisionRef: "DEC-DASH-005",
    matrixRef: "STR-KPI-005",
  },
  {
    metricId: "STR-KPI-006",
    category: "strategic",
    metricKey: "cancellation_rate",
    titleEn: "Cancellation rate",
    titleAr: "معدل الإلغاء",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "cancelled visits / total planned visits whose planning window is in the selected period",
    denominatorRule: "all planned visit records whose planning window is in the selected period",
    drillRoute: "/planning",
    ownerRole: "ops",
    implementation: "implemented",
    note: "Computed from visits.planning_status and window_start. The source workbook governs no narrower denominator status set.",
    decisionRef: null,
    matrixRef: "STR-KPI-006",
  },
  {
    metricId: "STR-KPI-007",
    category: "strategic",
    metricKey: "inspection_coverage",
    titleEn: "Inspection coverage",
    titleAr: "تغطية التفتيش",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "distinct due factories with a qualifying completion / distinct factories due under the published inspection-cycle policy",
    denominatorRule: "distinct factories due under the published inspection-cycle policy",
    drillRoute: "/analytics/coverage",
    ownerRole: "leadership",
    implementation: "not_configured",
    note: "No inspection-cycle / eligibility / due-date policy table exists. Returns 'Not configured' until a governed cycle policy is published via ADM-DASH-005.",
    decisionRef: "DEC-DASH-007",
    matrixRef: "STR-KPI-007",
  },
  {
    metricId: "STR-KPI-008",
    category: "strategic",
    metricKey: "uninspected_by_segment",
    titleEn: "Uninspected factories by stage, sector and region",
    titleAr: "المصانع غير المفتشة حسب المرحلة والقطاع والمنطقة",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "classify each eligible factory Never inspected / Due / Overdue / Covered using the published cycle policy",
    denominatorRule: "all eligible factories in the selected grouping",
    drillRoute: "/analytics/coverage",
    ownerRole: "leadership",
    implementation: "not_configured",
    note: "Shares the single inspection-cycle/eligibility policy with STR-KPI-007. Not computable until that policy is published.",
    decisionRef: "DEC-DASH-007",
    matrixRef: "STR-KPI-008",
  },
  {
    metricId: "STR-KPI-009",
    category: "strategic",
    metricKey: "checklist_items_by_authority",
    titleEn: "Checklist items by issuing authority",
    titleAr: "بنود قائمة التحقق حسب الجهة المُصدرة",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count distinct effective published inspection items grouped by the issuing authority of their linked regulation",
    denominatorRule: "n/a",
    drillRoute: "/admin/items",
    ownerRole: "compliance_admin",
    implementation: "implemented",
    note: "Counts each active global inspection_items record once and groups it by its published regulation's issuing_authority. Package reuse does not duplicate the global item.",
    decisionRef: null,
    matrixRef: "STR-KPI-009",
  },
  {
    metricId: "STR-KPI-010",
    category: "strategic",
    metricKey: "risk_to_attention_mismatch",
    titleEn: "Risk-to-attention mismatch",
    titleAr: "فجوة المخاطر مقابل الاهتمام",
    unit: "ratio",
    formulaVersion: "1.0.0",
    formula: "per stored current risk band: total visits in the selected period / distinct factories currently in that band",
    denominatorRule: "distinct factories carrying the stored current risk band",
    drillRoute: "/analytics/risk",
    ownerRole: "leadership",
    implementation: "implemented",
    note: "dashboard.xlsx governs a band comparison, not a threshold or composite score. Uses the stored current factories.risk_band and exposes the numerator and denominator per band; no mismatch threshold is invented.",
    decisionRef: null,
    matrixRef: "STR-KPI-010",
  },
  {
    metricId: "STR-KPI-011",
    category: "strategic",
    metricKey: "repeat_violation_rate",
    titleEn: "Repeat violation rate",
    titleAr: "معدل تكرار المخالفات",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "distinct factories where the same checklist item failed 2+ times within 12 months / distinct factories with >= 1 official violation",
    denominatorRule: "distinct factories with >= 1 official violation",
    drillRoute: "/analytics/violations",
    ownerRole: "compliance_admin",
    implementation: "unavailable",
    note: "dashboard.xlsx governs the threshold and window as the same checklist item failing 2+ times within 12 months. Stable item-version lineage and an official violation issue date are not available, so no substitute identity or date is used.",
    decisionRef: "DEC-DASH-011",
    matrixRef: "STR-KPI-011",
  },
  {
    metricId: "STR-KPI-012",
    category: "strategic",
    metricKey: "strategic_summary",
    titleEn: "Evidence-grounded Strategic Summary",
    titleAr: "الملخص الاستراتيجي المستند إلى الأدلة",
    unit: "none",
    formulaVersion: "1.0.0",
    formula: "3-5 ranked findings across strategic KPIs, one traceable sentence each, every sentence citing underlying records; advisory only",
    denominatorRule: "n/a",
    drillRoute: null,
    ownerRole: "leadership",
    implementation: "not_configured",
    note: "AI sub-capability (Phase 2 note defers the AI generation only). Requires ADM-DASH-011 source/evidence policy to be enabled and every claim linkable to evidence_refs. Disabled until configured.",
    decisionRef: "DEC-DASH-012",
    matrixRef: "STR-KPI-012",
  },

  // -------------------------------------------------------------- OPERATIONAL
  {
    metricId: "OPS-KPI-001",
    category: "operational",
    metricKey: "visit_pipeline",
    titleEn: "Visit pipeline",
    titleAr: "مسار الزيارات",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "as-of count of distinct visits grouped exactly by Draft, Published, Returned, and Cancelled planning status",
    denominatorRule: "n/a",
    drillRoute: "/planning",
    ownerRole: "ops",
    implementation: "implemented",
    note: "Planning status and operational state stay separate; other planning statuses are excluded from this workbook-defined pipeline.",
    decisionRef: null,
    matrixRef: "OPS-KPI-001",
  },
  {
    metricId: "OPS-KPI-002",
    category: "operational",
    metricKey: "expiring_soon",
    titleEn: "Expiring soon",
    titleAr: "قريب الانتهاء",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "published, not-started visits with window_end within the configured lead time from now",
    denominatorRule: "n/a",
    drillRoute: "/planning",
    ownerRole: "ops",
    implementation: "not_configured",
    note: "The expiring-soon lead time is an SLA/urgency policy parameter (ADM-DASH-007) and must not be hard-coded (48h in the workbook is illustrative). Overdue (window_end < now) is available; the lead-time window is not.",
    decisionRef: "DEC-DASH-007b",
    matrixRef: "OPS-KPI-002",
  },
  {
    metricId: "OPS-KPI-003",
    category: "operational",
    metricKey: "active_executions",
    titleEn: "Active executions",
    titleAr: "عمليات التنفيذ النشطة",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "distinct visits in operational_state on_the_way/arrived/executing with inspection not submitted",
    denominatorRule: "n/a",
    drillRoute: "/operations",
    ownerRole: "ops",
    implementation: "implemented",
    note: "Journey and inspection states reconciled in the shared projection.",
    decisionRef: null,
    matrixRef: "OPS-KPI-003",
  },
  {
    metricId: "OPS-KPI-004",
    category: "operational",
    metricKey: "pending_approvals",
    titleEn: "Pending approvals",
    titleAr: "الاعتمادات المعلقة",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "submitted inspections with no Level 2 decision",
    denominatorRule: "n/a",
    drillRoute: "/reviews",
    ownerRole: "reviewer",
    implementation: "implemented",
    note: "Includes submitted inspections without a review row and reviews without a decision. Aging bands require an SLA policy (ADM-DASH-007); base count is live.",
    decisionRef: null,
    matrixRef: "OPS-KPI-004",
  },
  {
    metricId: "OPS-KPI-005",
    category: "operational",
    metricKey: "pending_publish",
    titleEn: "Pending publish (admin only)",
    titleAr: "بانتظار النشر (للإدارة فقط)",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count draft configuration objects by object type and owning admin role",
    denominatorRule: "n/a",
    drillRoute: "/admin",
    ownerRole: "compliance_admin",
    implementation: "deferred",
    note: "Admin-only widget. Requires aggregating draft counts across config engines (compliance requests, packages, dashboard config). Definition seeded; projection wiring is a follow-on once the object-type set is confirmed.",
    decisionRef: null,
    matrixRef: "OPS-KPI-005",
  },
  {
    metricId: "OPS-KPI-006",
    category: "operational",
    metricKey: "today_schedule_load",
    titleEn: "Today's schedule load by inspector",
    titleAr: "حِمل جدول اليوم حسب المفتش",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count eligible visits whose execution window starts today (Asia/Riyadh), grouped by assigned inspector",
    denominatorRule: "n/a",
    drillRoute: "/planning",
    ownerRole: "ops",
    implementation: "implemented",
    note: "No overloaded/underloaded judgement is applied unless a capacity policy is published.",
    decisionRef: null,
    matrixRef: "OPS-KPI-006",
  },
  {
    metricId: "OPS-KPI-007",
    category: "operational",
    metricKey: "gps_overrides_today",
    titleEn: "GPS overrides today",
    titleAr: "تجاوزات نظام تحديد المواقع اليوم",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count governed override events recorded today (Asia/Riyadh) for out-of-geofence arrival confirmation",
    denominatorRule: "n/a",
    drillRoute: "/operations",
    ownerRole: "ops",
    implementation: "implemented",
    note: "Official/planner/observed coordinates remain separate; overrides are auditable and never rewrite the official pin.",
    decisionRef: null,
    matrixRef: "OPS-KPI-007",
  },
  {
    metricId: "OPS-KPI-008",
    category: "operational",
    metricKey: "live_activity_feed",
    titleEn: "Live activity feed",
    titleAr: "سجل النشاط المباشر",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "latest permission-visible immutable audit/timeline events ordered by occurred_at desc",
    denominatorRule: "n/a",
    drillRoute: null,
    ownerRole: "ops",
    implementation: "implemented",
    note: "Events come from immutable audit data; no fabricated narrative.",
    decisionRef: null,
    matrixRef: "OPS-KPI-008",
  },
  {
    metricId: "OPS-KPI-009",
    category: "operational",
    metricKey: "operational_nudges",
    titleEn: "Evidence-grounded operational nudges",
    titleAr: "تنبيهات تشغيلية مستندة إلى الأدلة",
    unit: "none",
    formulaVersion: "1.0.0",
    formula: "3-5 deterministic-trigger nudges ranked by deadline proximity; each opens a pre-filtered CTA and never executes the action",
    denominatorRule: "n/a",
    drillRoute: null,
    ownerRole: "ops",
    implementation: "not_configured",
    note: "Requires ADM-DASH-012 nudge trigger/CTA policy. Disabled until configured.",
    decisionRef: "DEC-DASH-012b",
    matrixRef: "OPS-KPI-009",
  },

  // ---------------------------------------------------------------- INSPECTOR
  {
    metricId: "IPAD-KPI-001",
    category: "inspector",
    metricKey: "today_visits",
    titleEn: "Today's visits",
    titleAr: "زيارات اليوم",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "count RLS-visible visits assigned to the inspector whose execution window starts today (Asia/Riyadh)",
    denominatorRule: "n/a",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Only the logged-in inspector's own assignments (RLS-scoped).",
    decisionRef: null,
    matrixRef: "IPAD-KPI-001",
  },
  {
    metricId: "IPAD-KPI-002",
    category: "inspector",
    metricKey: "remaining_visits",
    titleEn: "Remaining visits",
    titleAr: "الزيارات المتبقية",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "today's assigned visits minus visits whose inspector execution is complete (submitted)",
    denominatorRule: "n/a",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Completion uses the governed field submitted state, NOT Level-2 approval (which is outside inspector control). Sponsor may override via documented decision.",
    decisionRef: "DEC-DASH-013",
    matrixRef: "IPAD-KPI-002",
  },
  {
    metricId: "IPAD-KPI-003",
    category: "inspector",
    metricKey: "pending_attention",
    titleEn: "Pending attention",
    titleAr: "بانتظار الانتباه",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "own current returned inspections + resumable drafts + unsent sync-queue items, without double counting",
    denominatorRule: "n/a",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Server-side buckets (returned + resumable draft) computed here; the offline sync-queue count is contributed by the device and merged without double counting.",
    decisionRef: null,
    matrixRef: "IPAD-KPI-003",
  },
  {
    metricId: "IPAD-KPI-004",
    category: "inspector",
    metricKey: "daily_progress",
    titleEn: "Daily progress",
    titleAr: "التقدم اليومي",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "submitted own visits today / today's assigned visits (x100)",
    denominatorRule: "today's assigned visits",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Shows N/A when there are no visits; never divides by zero.",
    decisionRef: null,
    matrixRef: "IPAD-KPI-004",
  },
  {
    metricId: "IPAD-KPI-005",
    category: "inspector",
    metricKey: "approval_outcomes",
    titleEn: "Approval outcomes",
    titleAr: "نتائج الاعتماد",
    unit: "count",
    formulaVersion: "1.0.0",
    formula: "latest Level-2 decision per own submitted inspection, grouped Approve/Return/Reject",
    denominatorRule: "n/a",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Correctly NAMED as approval outcomes — this fixes the P0 defect where the iPad mislabelled approvals as 'Compliance rate'. Approval is not compliance.",
    decisionRef: null,
    matrixRef: "IPAD-KPI-005",
  },
  {
    metricId: "IPAD-KPI-006",
    category: "inspector",
    metricKey: "checklist_compliance",
    titleEn: "Checklist compliance",
    titleAr: "امتثال قائمة التحقق",
    unit: "percent",
    formulaVersion: "1.0.0",
    formula: "compliant eligible answers / (compliant + non_compliant) over own inspections; exclude na, unknown, incomplete",
    denominatorRule: "compliant + non_compliant eligible answers",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "implemented",
    note: "Uses the SAME canonical countChecklistCompliance as STR-KPI-001. This is the correctly-calculated inspector compliance the workbook requires.",
    decisionRef: null,
    matrixRef: "IPAD-KPI-006",
  },
  {
    metricId: "IPAD-KPI-007",
    category: "inspector",
    metricKey: "personal_trends",
    titleEn: "Personal trends",
    titleAr: "الاتجاهات الشخصية",
    unit: "none",
    formulaVersion: "1.0.0",
    formula: "own submitted-visit and compliance series over trailing configured periods",
    denominatorRule: "n/a",
    drillRoute: "/field",
    ownerRole: "inspector",
    implementation: "deferred",
    note: "Trailing-period trend series; definition seeded. Projection wiring is a follow-on once the trailing-period parameter is confirmed (ADM-DASH-002).",
    decisionRef: null,
    matrixRef: "IPAD-KPI-007",
  },
] as const;

export const KPI_BY_ID: ReadonlyMap<string, KpiDefinition> = new Map(
  KPI_DEFINITIONS.map((d) => [d.metricId, d]),
);

export function kpiDefinition(metricId: string): KpiDefinition | undefined {
  return KPI_BY_ID.get(metricId);
}

export function kpisByCategory(category: MetricCategory): KpiDefinition[] {
  return KPI_DEFINITIONS.filter((d) => d.category === category);
}
