// TASK-FACTORY-360-COMPLETE-010 · WA-M4-AC-006
// Reviewed Modern Standard Arabic fallbacks for generic Factory 360 interface
// copy. The governed ui_strings catalogue remains authoritative and overrides
// these values. Legal obligations, regulation text, classifications, penalty
// values, risk thresholds and SLA commitments are deliberately absent.
export const FACTORY360_AR_FALLBACK: Record<string, string> = {
  "enum.high": "مرتفع",
  "enum.medium": "متوسط",
  "enum.low": "منخفض",
  "f360.title": "المصنع 360",
  "f360.empty.title": "لا توجد مصانع في القائمة",
  "f360.empty.desc": "تتزامن سجلات هوية المصانع من المصدر الوطني.",
  "f360.err.load": "تعذّر تحميل المصانع.",
  "f360.err.neutral": "قائمة المصانع غير متاحة مؤقتاً. لم يتم تغيير أي شيء.",
  "f360.err.retry": "أعد المحاولة",
  "f360.list.region": "المنطقة",
  "f360.list.allRegions": "جميع المناطق",
  "f360.list.city": "المدينة",
  "f360.list.allCities": "جميع المدن",
  "f360.list.license.groupAria": "التصفية حسب حالة الترخيص",
  "f360.list.license.all": "الكل",
  "f360.list.license.licensed": "مرخصة",
  "f360.list.license.unlicensed": "غير مرخصة",
  "f360.list.portfolio": "اختيار مصنع",
  "f360.list.licensedCount": "المصانع المرخصة",
  "f360.list.unlicensedCount": "المنشآت غير المرخصة",
  "f360.list.regionsCount": "المناطق الممثلة",
  "f360.list.of": "من",
  "f360.list.factoriesWord": "مصانع",
  "f360.list.emptyRegion.title": "لا توجد مصانع في هذه المنطقة",
  "f360.list.emptyRegion.desc": "امسح عامل التصفية لعرض السجل كاملاً.",
  "f360.list.th.factory": "المصنع",
  "f360.list.th.cr": "السجل التجاري",
  "f360.list.th.region": "المنطقة",
  "f360.list.th.city": "المدينة",
  "f360.list.th.risk": "المخاطر",
  "f360.list.dossier": "عرض المصنع",
  "f360.permission.title": "يلزم تصريح الوصول إلى ملف المصنع 360",
  "f360.permission.body": "ليس لديك صلاحية الوصول إلى ملف هذا المصنع.",
  "f360.notFound.title": "ملف المصنع الشامل غير متاح",
  "f360.notFound.desc": "تسجيل المصنع غير موجود أو غير متاح لك.",
  "f360.id.cr": "السجل التجاري",
  "f360.id.license": "الرخصة",
  "f360.meta.source": "المصدر",
  "f360.meta.synced": "متزامن",
  "f360.risk.heading": "المخاطر — قابلة لإعادة الإنتاج (EV-004)",
  "f360.hsCode": "رمز HS",
  "f360.cr.noAggregate": "بيانات جميع التراخيص فقط. لا يُحتسب معدل مخاطر أو نسبة امتثال على مستوى السجل التجاري.",
  "f360.cr.portfolio": "جميع التراخيص",
  "f360.enforcement.heading": "سجل العقوبات",
  "f360.source.degraded": "متدهور",
  "f360.source.notAvailable": "غير متاح",
  "f360.source.empty": "متاح — لا توجد سجلات",
  "f360.source.available": "متاح",
  "f360.compare.cr": "رقم السجل التجاري",
  "f360.compare.license": "الرخصة الصناعية",
  "f360.compare.plant": "رقم المصنع",
  "f360.compare.factory": "اسم المصنع",
  "f360.compare.region": "المنطقة",
  "f360.compare.city": "المدينة",
  "f360.compare.source": "نظام المصدر",
  "f360.timeline.crIssued": "إصدار السجل التجاري",
  "f360.timeline.crExpiry": "انتهاء السجل التجاري",
  "f360.timeline.licenseIssued": "إصدار الرخصة الصناعية المحددة",
  "f360.timeline.licenseExpiry": "انتهاء الرخصة الصناعية المحددة",
  "f360.timeline.reportSubmitted": "إرسال تقرير التفتيش",
  "f360.timeline.governmentRecorded": "استلام سجل حكومي",
  "f360.timeline.penaltyIssued": "إصدار إشعار عقوبة",
  "f360.timeline.riskCalculated": "اكتمال احتساب محرك المخاطر",
  "f360.licenses.degraded": "بيانات الرخص الصناعية متدهورة مؤقتاً؛ تظل هوية السجل التجاري متاحة.",
  "f360.licenses.heading": "الرخص والمصانع",
  "f360.licenses.count": "رخص",
  "f360.plant": "المصنع",
  "f360.license.type": "النوع",
  "f360.license.stage": "المرحلة",
  "common.status": "الحالة",
  "f360.risk.level": "مستوى المخاطر",
  "f360.licenses.empty": "لا توجد رخصة صناعية مرتبطة بهذا السجل التجاري.",
  "f360.cr.heading": "السجل التجاري والهوية النظامية",
  "f360.cr.number": "رقم السجل التجاري",
  "f360.cr.unified": "الرقم الموحد",
  "f360.cr.legalEn": "الاسم النظامي (بالإنجليزية)",
  "f360.cr.legalAr": "الاسم النظامي (بالعربية)",
  "f360.cr.dates": "الإصدار / الانتهاء",
  "f360.cr.owner": "بيانات المالك",
  "f360.cr.totalLicenses": "إجمالي الرخص",
  "f360.cr.licenseStates": "سارية / منتهية / معلقة",
  "f360.cr.highestRisk": "الرخصة الأعلى خطورة",
  "f360.compliance.notAvailable": "غير متاح",
  "f360.cr.approvedInspections": "التفتيشات المعتمدة",
  "f360.cr.openViolations": "المخالفات المفتوحة",
  "f360.cr.openViolationsUnavailable": "غير متاح — لا تحدد مخالفات التشغيل الحالية حالة مفتوحة أو مغلقة محكومة",
  "f360.cr.activePenalties": "العقوبات النشطة",
  "f360.cr.activePenaltiesUnavailable": "غير متاح — لا تحدد حالات العقوبات الحالية حالات نشطة أو منتهية أو ملغاة",
  "f360.license.heading": "الرخصة والمصنع والعنوان المحددة",
  "f360.id.factory": "المصنع",
  "f360.id.licenseStatus": "الحالة / المرحلة",
  "f360.id.licenseDates": "الإصدار / الانتهاء",
  "f360.id.licenseHolder": "صاحب الرخصة",
  "f360.location": "العنوان",
  "f360.coordinates": "الإحداثيات",
  "f360.exportsProducts": "هل يصدّر منتجات؟",
  "f360.exportsProducts.unknown": "غير معروف",
  "common.yes": "نعم",
  "common.no": "لا",
  "f360.license.unavailable": "حدد رخصة صناعية مرتبطة لتحميل بيانات المصنع.",
  "f360.observed.heading": "البيانات الرسمية مقارنة بآخر لقطة رصد معتمدة",
  "f360.observed.rule": "يعرض عمود الرصد البيانات الرسمية كما كانت عند إرسال تقرير أصبح معتمداً لاحقاً. ولا يغيّر البيانات الرسمية الحالية.",
  "common.field": "الحقل",
  "f360.observed.official": "البيانات الرسمية الحالية",
  "f360.observed.captured": "البيانات المرصودة عند الإرسال",
  "f360.observed.result": "المقارنة",
  "f360.observed.same": "دون تغيير",
  "f360.observed.changed": "تغيرت أو غير متاحة",
  "f360.observed.capturedAt": "وقت الحفظ",
  "f360.observed.origin": "التقرير المعتمد المصدر",
  "f360.section.degraded": "هذا القسم من المصدر متدهور؛ تظل الأقسام الأخرى متاحة.",
  "f360.observed.empty": "لا يحتوي أي تقرير معتمد حتى الآن على لقطة مصنع محكومة للرخصة المحددة.",
  "f360.compliance.heading": "امتثال التفتيشات المعتمدة",
  "f360.compliance.rule": "يُحتسب فقط من أحدث نسخة نهائية مرسلة من التفتيشات المعتمدة ونسخة قائمة التحقق المستخدمة في التفتيش. تظل التفتيشات المعادة أو المرفوضة ظاهرة أدناه، لكنها لا تؤثر في هذه النسبة.",
  "f360.compliance.na": "لا توجد إجابات معتمدة مؤهلة للاحتساب",
  "f360.compliance.trend": "اتجاه الامتثال المعتمد",
  "f360.reports.heading": "تقارير التفتيش",
  "f360.report.number": "التفتيش",
  "common.date": "التاريخ",
  "f360.report.version": "أحدث نسخة نهائية",
  "f360.report.compliance": "الامتثال المعتمد",
  "f360.report.notSubmitted": "لم يُرسل",
  "f360.report.open": "فتح التقرير",
  "f360.reports.empty": "لا توجد تقارير تفتيش للمصنع المحدد.",
  "f360.violations.heading": "مخالفات التفتيش المعتمدة والإجراءات التصحيحية",
  "f360.violation.title": "المخالفة",
  "f360.violation.severity": "الدرجة",
  "f360.violation.corrective": "الإجراء التصحيحي",
  "f360.violation.grace": "فترة السماح",
  "f360.violation.origin": "التقرير المعتمد المصدر",
  "common.days": "أيام",
  "f360.violations.empty": "لا تظهر ضمن نطاقك مخالفات من تقارير تفتيش معتمدة.",
  "f360.industrial.heading": "المعلومات الصناعية",
  "common.type": "النوع",
  "common.name": "الاسم",
  "f360.quantity": "الكمية / الطاقة",
  "f360.production": "الإنتاج الفعلي / الأقصى",
  "f360.pricePrimary": "السعر / أساسي",
  "f360.source": "المصدر",
  "f360.industrial.empty": "لا تتوفر منتجات أو قطع غيار أو آلات أو خطوط إنتاج أو مواد خام مدعومة بالمصدر.",
  "f360.government.heading": "السجلات الحكومية",
  "common.reference": "المرجع",
  "f360.validity": "الصلاحية",
  "f360.government.empty": "سجلات الجهات الحكومية غير متاحة حتى يوفرها عقد مصدر محكوم.",
  "f360.chemicalCustoms.heading": "تصاريح المواد الكيميائية والإعفاءات الجمركية",
  "f360.chemicalCustoms.noPlant": "لا يوجد رقم مصنع في الرخصة المحددة — تُستعلم تصاريح المواد الكيميائية والإعفاءات الجمركية برقم المصنع.",
  "f360.chemicalPermits.heading": "تصاريح المواد الكيميائية",
  "f360.chemicalPermits.approval": "رقم الموافقة",
  "f360.chemicalPermits.empty": "لا توجد تصاريح مواد كيميائية لهذا المصنع.",
  "f360.customsExemptions.heading": "الإعفاءات الجمركية",
  "f360.customsExemptions.decree": "رقم القرار",
  "f360.customsExemptions.empty": "لا توجد إعفاءات جمركية لهذا المصنع.",
  "f360.documents.heading": "المستندات ووسائط المصنع",
  "f360.restricted": "مقيد",
  "f360.documents.restricted": "تتطلب بيانات المستندات تصريح مستندات المصنع.",
  "common.category": "الفئة",
  "common.title": "العنوان",
  "common.download": "تنزيل",
  "f360.download.unavailable": "الملف غير متاح",
  "f360.download.restricted": "التنزيل مقيد",
  "f360.documents.empty": "لا تتوفر بيانات وصفية للمستندات مدعومة بالمصدر.",
  "f360.media.official": "المعرض الرسمي للمصنع",
  "f360.media.alt": "صورة رسمية للمصنع",
  "f360.media.boundary": "تظهر هنا فقط وسائط المصنع أو ملفه الرسمية. تظل أدلة التفتيش مرتبطة بتقريرها ولا تُدمج مطلقاً في هذا المعرض.",
  "f360.media.evidence": "أدلة التفتيش المرتبطة",
  "f360.media.origin": "السياق المصدر",
  "f360.media.ocr": "التعرف السياقي على النص",
  "f360.media.evidenceEmpty": "لا تظهر ضمن نطاقك أدلة مرتبطة بالتفتيش أو الوصول أو المخالفة.",
  "f360.timeline.heading": "الخط الزمني لأحداث الأعمال",
  "f360.timeline.boundary": "السجل التجاري + الرخصة المحددة",
  "f360.timeline.rule": "أحداث أعمال مدعومة بالمصدر فقط. زيارات التشغيل مستبعدة عمداً.",
  "f360.timeline.empty": "لا توجد أحداث أعمال للرخصة المحددة.",
  "f360.xpc.heading": "تسوية المصادر ومزودي البيانات",
  "f360.xpc.conflicts": "تعارضات",
  "f360.xpc.unverified": "مصدر رئيسي غير متحقق",
  "f360.xpc.reconciled": "تمت التسوية",
  "f360.xpc.rule": "تُفحص البيانات مرة واحدة بواسطة النظام. بيانات Industry Shared الرئيسية غير محقّقة بعد، لذلك لا تُستخدم؛ قيم واجهة التفتيش سياقية؛ وبيانات التقارير المعتمدة هي الأكثر موثوقية. عند وجود تعارض في البيانات، نعرضه ولا نخفيه أو نكتب فوقه أبداً.",
  "f360.xpc.cr": "السجل التجاري",
  "f360.xpc.license": "الرخصة الصناعية",
  "f360.xpc.plant": "المصنع",
  "f360.xpc.activities": "الأنشطة / المنتجات / المواد",
  "f360.xpc.workforce": "القوى العاملة / جهات الاتصال / التفويضات",
  "f360.xpc.package": "نسخة قائمة التحقق / نسخة الإرسال",
  "f360.xpc.discrepancies": "التسوية",
  "f360.xpc.none": "لا توجد بيانات قابلة للتسوية",
  "f360.context.heading": "السياق المحدد",
  "f360.source.heading": "حالة المصدر وحداثة البيانات",
  "f360.source.system": "نظام المصدر",
  "f360.source.timestamp": "وقت المزامنة المسجل",
  "f360.source.noSla": "تُعرض الحداثة كبيان من المصدر؛ ولا يُستنتج أي حد غير معتمد لقدم البيانات.",
  "f360.risk.restricted": "تتطلب تفاصيل المخاطر تصريح مخاطر المصنع.",
  "f360.risk.version": "النموذج",
  "f360.risk.snapshots": "لقطات محفوظة",
  "f360.risk.ai.title": "شرح المخاطر المحفوظة",
  "f360.risk.ai.description": "للاستشارة فقط. يقتصر الشرح على بيانات محرك المخاطر المحفوظة ولا يمكنه إعادة احتساب المخاطر أو تغييرها.",
  "f360.risk.ai.generate": "شرح العوامل المسجلة",
  "f360.risk.ai.unavailable": "شرح الذكاء الاصطناعي غير متاح",
  "f360.risk.ai.evidence": "مراجع المصدر",
  "f360.risk.ai.advisory": "يلزم قرار بشري",
  "f360.enforcement.origin": "التقرير المصدر",
  "f360.enforcement.empty": "لا تظهر ضمن نطاقك إشعارات عقوبات.",
  "common.actions": "الإجراءات",
  "f360.actions.openMap": "فتح الخريطة",
  "f360.actions.createInspection": "إنشاء تفتيش",
  "f360.actions.planSingle": "تخطيط زيارة واحدة",
  "f360.actions.exportPdf": "طباعة / حفظ ملف PDF المصرح به",
  "f360.actions.restricted": "لا يُسمح لدورك بإنشاء تفتيش أو تصدير الملف.",
  "f360.actions.submissionBlocked": "يبقى إرسال التفتيش غير متاح ما دام القرار غير محسوم.",
};
