import type { ChemicalPermit, CommercialRegistration, CustomsExemption, IndustrialLicense, IndustrialPlant, InspectionObservation, InspectionObservationWire, InspectionTaskDetail, LabelValue, PlantAddress, ProductionLineItem, ProductionLinePage, Regulation, RegulationItem, SenaeiLoginResult, SenaeiOperationResult, SenaeiTaskSummary, SenaeiUserProfile } from "./types";

type JsonRecord = Record<string, unknown>;
const record = (value: unknown): JsonRecord | null => value !== null && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : null;
const array = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const text = (value: unknown): string | null => typeof value === "string" ? value : typeof value === "number" ? String(value) : null;
const numeric = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) ? value : typeof value === "string" && value.trim() !== "" && Number.isFinite(Number(value)) ? Number(value) : null;
const truth = (value: unknown): boolean | null => typeof value === "boolean" ? value : value === 1 || value === "1" ? true : value === 0 || value === "0" ? false : null;
function requiredId(value: unknown, context: string): string { const id = text(value); if (!id) throw new Error(`${context} is missing an external id`); return id; }
function labelValue(value: unknown): LabelValue | null { const row = record(value); return row ? { value: text(row.value), label: text(row.label) } : null; }
function address(value: unknown): PlantAddress | null { const row = record(value); if (!row) return null; const city = record(row.city); const region = record(row.region); return { externalId: text(row.address_id), addressLine1: text(row.address_line_1), districtEn: text(row.district_en), districtAr: text(row.district_ar), buildingNumber: text(row.building_number), additionalNumber: text(row.additional_number), zipCode: text(row.zip_code), unitNumber: text(row.unit_no), streetNameEn: text(row.street_name_en), streetNameAr: text(row.street_name_ar), latitude: numeric(row.latitude), longitude: numeric(row.longitude), cityNameEn: text(city?.name_en), cityNameAr: text(city?.name_ar), regionNameEn: text(region?.name_en), regionNameAr: text(region?.name_ar) }; }
function commercialRegistration(value: unknown): CommercialRegistration | null { const row = record(value); return row ? { number: text(row.number), unifiedNumber: text(row.unified_number), nameEn: text(row.name_en), nameAr: text(row.name_ar) } : null; }
function plant(value: unknown): IndustrialPlant | null { const row = record(value); if (!row) return null; return { externalId: requiredId(row.id, "plant"), plantNumber: text(row.plant_number ?? row.number), state: labelValue(row.state), licenseNumber: text(row.license_number), mainActivityCodeL2: text(row.main_activity_code_l2), mainActivityCodeL4: text(row.main_activity_code_l4), hasApprovedManpower: truth(row.has_approved_manpower), insideIndustrialCity: truth(row.inside_industrial_city), startedProductionAt: text(row.started_production_at), closedAt: text(row.closed_at), establishedAt: text(row.established_at), canceledAt: text(row.canceled_at), landProvider: row.land_provider ?? null, industrialCity: row.industrial_city ?? null, address: address(row.address), commercialRegistration: commercialRegistration(row.commercial_entity) }; }
function license(value: unknown): IndustrialLicense | null { const row = record(value); return row ? { externalId: requiredId(row.id, "license"), licenseNumber: text(row.license_number), type: labelValue(row.license_type), status: labelValue(row.status), investmentType: labelValue(row.investment_type), investmentSize: numeric(row.investment_size) } : null; }

export function parseTaskDetail(payload: unknown): InspectionTaskDetail { const root = record(payload); const row = record(root?.data); if (!row) throw new Error("task detail response is missing data"); const visit = record(row.visit); const inspector = record(visit?.inspector); return { externalId: requiredId(row.id, "task"), number: text(row.number), workflow: text(row.workflow), status: text(record(row.status)?.value ?? row.status), createdAt: text(row.created_at), license: license(row.license), visit: visit ? { externalId: requiredId(visit.id, "visit"), type: labelValue(visit.type), method: labelValue(visit.method), visitDate: text(visit.visit_date), facilityName: text(visit.facility_name), crNumber: text(visit.cr_number), notes: text(visit.notes), inspector: inspector ? { externalId: text(inspector.id), name: text(inspector.name) } : null, plant: plant(visit.plant) } : null }; }
function productionItem(value: unknown): ProductionLineItem { const row = record(value); if (!row) throw new Error("production-line item is not an object"); const product = record(row.product); const unit = record(row.unit); const activity = record(product?.activity); return { externalId: requiredId(row.id, "production-line item"), externalPlantId: text(row.plant_id), externalProductId: text(row.product_id), externalUnitId: text(row.unit_id), quantity: numeric(row.quantity), isPrimary: truth(row.is_primary), realProduction: numeric(row.real_production), maximumProduction: numeric(row.maximum_production), price: numeric(row.price), hsCode: text(product?.hs_code), hsCodeType: text(product?.hs_code_type), nameEn: text(product?.name_en), nameAr: text(product?.name_ar), isSparePart: truth(product?.is_spare_part), isMachine: truth(product?.is_machine), isEndProduct: truth(product?.is_end_product), isRawMaterial: truth(product?.is_raw_material), unitCode: text(unit?.code), unitNameEn: text(unit?.name_en), unitNameAr: text(unit?.name_ar), activityIsicCode: text(activity?.isic_code), activityNameEn: text(activity?.name_en), activityNameAr: text(activity?.name_ar), createdAt: text(row.created_at), updatedAt: text(row.updated_at) }; }
export function parseProductionLinePage(payload: unknown): ProductionLinePage { const row = record(payload); if (!row) throw new Error("production-line response is not an object"); return { currentPage: numeric(row.current_page) ?? 1, lastPage: numeric(row.last_page) ?? 1, perPage: numeric(row.per_page) ?? 0, total: numeric(row.total) ?? 0, items: array(row.data).map(productionItem) }; }
function regulationItem(value: unknown): RegulationItem { const row = record(value); if (!row) throw new Error("regulation item is not an object"); return { externalId: requiredId(row.id, "regulation item"), name: text(row.name), description: text(row.description), type: labelValue(row.type), administrativeName: labelValue(row.administrative_name), reportKind: labelValue(row.report_kind), approvalOption: labelValue(row.approval_option), rejectionOption: labelValue(row.rejection_option), status: labelValue(row.status), attachmentMode: labelValue(row.attachment_mode), entityNotification: truth(row.entity_notification), appearedInSelfAssessment: truth(row.appeared_in_self_assessment), mandatoryForInspector: truth(row.is_mandatory_for_inspector) }; }
function regulation(value: unknown): Regulation { const row = record(value); if (!row) throw new Error("regulation is not an object"); return { externalId: requiredId(row.id, "regulation"), name: text(row.name), number: text(row.number), issueDate: text(row.issue_date), active: truth(row.status), issuingAuthorities: array(row.issuing_authorities).map(labelValue).filter((x): x is LabelValue => x !== null), items: array(row.items).map(regulationItem), createdAt: text(row.created_at) }; }
export function parseRegulationList(payload: unknown): Regulation[] { return array(record(payload)?.data).map(regulation); }
export function parseRegulationDetail(payload: unknown): Regulation { return regulation(record(payload)?.data); }
export function mapInspectionObservation(wire: InspectionObservationWire): InspectionObservation { return { isDisrupted: truth(wire.is_distrupted), disruptionReason: text(wire.distrubtion_reason), otherDisruptionReason: text(wire.other_distrubtion_reason), isExempted: truth(wire.is_exmpted), administratorsNumber: numeric(wire.administrators_number) }; }

function userProfile(value: unknown): SenaeiUserProfile {
  const row = record(value);
  if (!row) throw new Error("user profile is not an object");
  return { externalId: requiredId(row.id, "user"), legacyId: text(row.old_id), username: text(row.username), firstName: text(row.first_name), lastName: text(row.last_name), nationalId: text(row.national_id), email: text(row.email), mobile: text(row.mobile), entity: text(row.entity), dateOfBirth: text(row.date_of_birth), language: text(row.language), emailVerifiedAt: text(row.email_verified_at), mobileVerifiedAt: text(row.mobile_verified_at), blockedAt: text(row.blocked_at), disabledAt: text(row.disabled_at), createdAt: text(row.created_at), updatedAt: text(row.updated_at), lastLoginAt: text(row.last_login_at), ndbSyncedAt: text(row.ndb_synched_at), ndbLastOperationsAt: text(row.ndb_last_ops_at) };
}
export function parseLogin(payload: unknown): SenaeiLoginResult { const row = record(payload); const token = text(row?.token); if (!row || row.success !== true || !token) throw new Error("login response is incomplete"); return { token, user: userProfile(row.user) }; }
export function parseProfile(payload: unknown): SenaeiUserProfile { const row = record(payload); return userProfile(row?.user); }
export function parseOperation(payload: unknown): SenaeiOperationResult { const row = record(payload); if (!row || typeof row.success !== "boolean") throw new Error("operation response is incomplete"); return { success: row.success, message: text(row.message) }; }
export function parseTaskList(payload: unknown): SenaeiTaskSummary[] {
  const root = record(payload);
  return array(root?.data).map(value => {
    const row = record(value); if (!row) throw new Error("task summary is not an object");
    const visit = record(row.visit); const inspector = record(visit?.inspector);
    return { externalId: requiredId(row.id, "task"), number: text(row.number), workflow: text(row.workflow), status: text(record(row.status)?.value ?? row.status), createdAt: text(row.created_at), visit: visit ? { externalId: requiredId(visit.id, "visit"), type: labelValue(visit.type), method: labelValue(visit.method), visitDate: text(visit.visit_date), facilityName: text(visit.facility_name), crNumber: text(visit.cr_number), notes: text(visit.notes), inspector: inspector ? { externalId: text(inspector.id), name: text(inspector.name) } : null } : null };
  });
}

export function parseChemicalPermitList(payload: unknown): ChemicalPermit[] {
  const root = record(payload);
  return array(root?.data).map(value => {
    const row = record(value); if (!row) throw new Error("chemical permit is not an object");
    return { externalId: requiredId(row.id, "chemical permit"), approvalNumber: text(row.approval_number), requestNumber: text(row.request_number), type: labelValue(row.type), decreeNumber: text(row.decree_number), decreeIsn: text(row.decree_ISN), fasahRefNumber: text(row.fasah_ref_number), approvedAt: text(row.approved_at), startsAt: text(row.starts_at), endsAt: text(row.ends_at), status: labelValue(row.status), plantId: text(row.plant_id), itemsCount: numeric(row.items_count) };
  });
}

export function parseCustomsExemptionList(payload: unknown): CustomsExemption[] {
  const root = record(payload);
  return array(root?.data).map(value => {
    const row = record(value); if (!row) throw new Error("customs exemption is not an object");
    return { externalId: requiredId(row.id, "customs exemption"), requestNumber: text(row.request_number), type: labelValue(row.type), decreeNumber: numeric(row.decree_number), decreeIsn: numeric(row.decree_ISN), approvedAt: text(row.approved_at), startsAt: text(row.starts_at), endsAt: text(row.ends_at), status: labelValue(row.status), plantId: text(row.plant_id), itemsCount: numeric(row.items_count), productsCount: numeric(row.products_count) };
  });
}
