import type { ReviewQueueStrings, Translator } from "./types";

export function buildQueueStrings(t: Translator): ReviewQueueStrings {
  return {
    searchPlaceholder: t("review.list.searchPh", "factory, code or inspector…"),
    searchAria: t("review.list.searchAria", "Search the review queue"),
    allStatuses: t("review.list.allStatuses", "All statuses"),
    allRisks: t("review.list.allRisks", "All risk levels"),
    overdueOnly: t("review.list.overdueOnly", "Overdue only"),
    clearFilters: t("review.list.clearFilters", "Clear filters"),
    showing: t("review.list.showing", "{shown} of {total}"),
    noMatch: t("review.list.noMatch", "No reviews match the filters"),
    noMatchBody: t("review.list.noMatchBody", "Adjust or clear the search, status, risk and overdue filters."),
    colFactory: t("review.list.colFactory", "Factory"),
    colInspector: t("review.list.colInspector", "Inspector"),
    colTypeMode: t("review.list.colTypeMode", "Type · mode"),
    colVersion: t("review.list.colVersion", "Version"),
    colFingerprint: t("review.list.colFingerprint", "Review readiness"),
    colStatus: t("review.list.colStatus", "Status"),
    colOpen: t("review.list.colOpen", "Review"),
    open: t("review.list.open", "Open review"),
    openHint: t("review.list.openHint", "Opens the review as read-only. Starting and deciding happen there, and we record both."),
    fpTitle: t("review.list.fpTitle", "Review readiness"),
    fpHint: t("review.list.fpHint", "Facts come from records you are allowed to see. Anything outside your scope shows as unavailable."),
    fp: {
      sla: t("review.list.fp.sla", "Deadline"),
      slaOverdue: t("review.list.fp.slaOverdue", "overdue"),
      slaOnTime: t("review.list.fp.slaOnTime", "on time"),
      slaUnavailable: t("review.list.fp.slaUnavailable", "Deadline not available — a needed setting or timestamp is missing"),
      risk: t("review.list.fp.risk", "Risk"),
      critical: t("review.list.fp.critical", "critical (L1)"),
      priority: t("review.list.fp.priority", "priority"),
      checklist: t("review.list.fp.checklist", "Checklist"),
      evidence: t("review.list.fp.evidence", "Evidence"),
      ack: t("review.list.fp.ack", "Acknowledgement"),
      factory: t("review.list.fp.factory", "Factory verify"),
      present: t("review.list.fp.present", "present"),
      missing: t("review.list.fp.missing", "missing"),
      verified: t("review.list.fp.verified", "verified"),
      updated: t("review.list.fp.updated", "updated"),
      unavailable: t("review.list.fp.unavailable", "not available"),
      readyBlockTag: t("review.list.fp.readyBlockTag", "derived"),
      noEvidenceTitle: t("review.list.fp.noEvidenceTitle", "Evidence not yet readable"),
      noEvidenceBody: t("review.list.fp.noEvidenceBody", "A linked source could not be read. It is not counted as ready."),
      unassignedTitle: t("review.list.fp.unassignedTitle", "Unassigned reviewer"),
      unassignedBlocked: t("review.list.fp.unassignedBlocked", "claim/reassign not available"),
    },
  };
}
