// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/access" | "/admin/audit" | "/admin/gis" | "/admin/items" | "/admin/localization" | "/admin/packages" | "/admin/regulations" | "/admin/risk" | "/admin/violations" | "/admin/workflows" | "/dashboard" | "/factories" | "/factories/[id]" | "/field" | "/field/[visitId]" | "/field/inspection/[id]" | "/launch" | "/launch/no-workspace" | "/login" | "/operations" | "/operations/live" | "/planning" | "/planning/bulk" | "/planning/bulk/review" | "/planning/immediate" | "/planning/plans" | "/planning/plans/[id]" | "/planning/single" | "/reports/inspection/[id]" | "/reset" | "/reviews" | "/reviews/[id]" | "/virtual" | "/virtual/[id]" | "/visits" | "/visits/[id]" | "/visits/calendar" | "/visits/workload"
type AppRouteHandlerRoutes = "/locale" | "/signout"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/access": {}
  "/admin/audit": {}
  "/admin/gis": {}
  "/admin/items": {}
  "/admin/localization": {}
  "/admin/packages": {}
  "/admin/regulations": {}
  "/admin/risk": {}
  "/admin/violations": {}
  "/admin/workflows": {}
  "/dashboard": {}
  "/factories": {}
  "/factories/[id]": { "id": string; }
  "/field": {}
  "/field/[visitId]": { "visitId": string; }
  "/field/inspection/[id]": { "id": string; }
  "/launch": {}
  "/launch/no-workspace": {}
  "/locale": {}
  "/login": {}
  "/operations": {}
  "/operations/live": {}
  "/planning": {}
  "/planning/bulk": {}
  "/planning/bulk/review": {}
  "/planning/immediate": {}
  "/planning/plans": {}
  "/planning/plans/[id]": { "id": string; }
  "/planning/single": {}
  "/reports/inspection/[id]": { "id": string; }
  "/reset": {}
  "/reviews": {}
  "/reviews/[id]": { "id": string; }
  "/signout": {}
  "/virtual": {}
  "/virtual/[id]": { "id": string; }
  "/visits": {}
  "/visits/[id]": { "id": string; }
  "/visits/calendar": {}
  "/visits/workload": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
