// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/access">> = Specific
  const handler = {} as typeof import("../../src/app/admin/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/gis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gis">> = Specific
  const handler = {} as typeof import("../../src/app/admin/gis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/items">> = Specific
  const handler = {} as typeof import("../../src/app/admin/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/localization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/localization">> = Specific
  const handler = {} as typeof import("../../src/app/admin/localization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/regulations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/regulations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/regulations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/risk">> = Specific
  const handler = {} as typeof import("../../src/app/admin/risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/violations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/violations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/violations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/workflows">> = Specific
  const handler = {} as typeof import("../../src/app/admin/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/factories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/factories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/factories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/factories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/factories">> = Specific
  const handler = {} as typeof import("../../src/app/factories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/field/[visitId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/[visitId]">> = Specific
  const handler = {} as typeof import("../../src/app/field/[visitId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/field/inspection/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/inspection/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/field/inspection/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/field/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field">> = Specific
  const handler = {} as typeof import("../../src/app/field/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/launch/no-workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/launch/no-workspace">> = Specific
  const handler = {} as typeof import("../../src/app/launch/no-workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/launch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/launch">> = Specific
  const handler = {} as typeof import("../../src/app/launch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/live">> = Specific
  const handler = {} as typeof import("../../src/app/operations/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../src/app/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/bulk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/planning/bulk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/bulk/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bulk/review">> = Specific
  const handler = {} as typeof import("../../src/app/planning/bulk/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/immediate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/immediate">> = Specific
  const handler = {} as typeof import("../../src/app/planning/immediate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../src/app/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/plans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/plans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/planning/plans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/plans">> = Specific
  const handler = {} as typeof import("../../src/app/planning/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/single/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/single">> = Specific
  const handler = {} as typeof import("../../src/app/planning/single/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/inspection/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/inspection/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/reports/inspection/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../src/app/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/virtual/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/virtual/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/virtual/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/virtual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/virtual">> = Specific
  const handler = {} as typeof import("../../src/app/virtual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visits/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visits/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/visits/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visits/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visits/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/visits/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visits">> = Specific
  const handler = {} as typeof import("../../src/app/visits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visits/workload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visits/workload">> = Specific
  const handler = {} as typeof import("../../src/app/visits/workload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/locale">> = Specific
  const handler = {} as typeof import("../../src/app/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/signout">> = Specific
  const handler = {} as typeof import("../../src/app/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
