#!/usr/bin/env python3
"""
Per-screen build spec: what a developer needs open beside the Figma frame.

A frame shows what a screen looks like. It does not say which route it serves, who may
see it, which regions are mandatory, which states must exist, or which React component
each block maps to. That is the difference between a picture and a contract, and it is
what this generates — one section per screen, joining:

  screen_route_catalogue.csv   route, personas, regions, actions, states, permission
  requirement-screen-map.csv   how many requirements ride on the screen, and their ids
  component-map.json           Figma component -> React import path

  python3 docs/design/figma/handoff/build-screen-spec.py
    -> docs/design/figma/handoff/SCREEN-SPEC.md
"""
import csv, json, pathlib, re, collections

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[3]

screens = list(csv.DictReader(open(ROOT / "product-contract/screens/screen_route_catalogue.csv",
                                   encoding="utf-8")))
reqmap = list(csv.DictReader(open(ROOT / "docs/design/figma/traceability/requirement-screen-map.csv",
                                  encoding="utf-8")))
cmap = json.loads((HERE / "component-map.json").read_text(encoding="utf-8"))

req_by_screen = collections.defaultdict(list)
for r in reqmap:
    req_by_screen[r["screen_id"]].append(r)

# Where each screen actually lives in the Figma file. Frames are named
# "<screen_id> — <name> — <route> — <section>", except the legacy ones which lead with
# the screen name; those carry their screen_id now too where one exists.
FIGMA_FRAME = {
    "SCR-WEB-100": "SCR-WEB-100 — Planning — /planning",
    "SCR-WEB-300": "SCR-WEB-300 — Review & Approval — /reviews",
    "SCR-WEB-500": "SCR-WEB-500 — Operations Center — /operations",
}

OUT_OF_SCOPE = {"iPad"}

L = ["# Screen build spec\n",
     "Generated by `docs/design/figma/handoff/build-screen-spec.py`. One section per",
     "in-scope governed screen.\n",
     "**How to use this.** Open the Figma frame named in *Figma frame*, and this section",
     "beside it. The frame is the visual contract; everything below is the part of the",
     "contract a picture cannot carry. Where the two disagree, this file is wrong and the",
     "catalogue wins — regenerate rather than editing by hand.\n",
     "**Rules that override anything a frame appears to show** (`CLAUDE.md`):\n",
     "- No new CSS, no new tokens. Every element renders with a class that already exists",
     "  in `apps/web/src/app/saqeel-components.css`. A missing class is a design-system",
     "  change request, not a page-level fix.",
     "- Status is text plus shape, never colour alone.",
     "- RTL via logical properties only — `padding-inline`, `margin-inline-start`,",
     "  `inset-inline-start`, `border-inline-end`. Never `left`/`right`.",
     "- Arabic comes from the i18n layer, never from a component.",
     "- Never invent a governed value. Absent data renders as a state: *Not configured* /",
     "  *Unavailable* / *Insufficient evidence*.\n",
     "---\n"]

for s in sorted((x for x in screens if x["channel"] not in OUT_OF_SCOPE),
                key=lambda x: x["screen_id"]):
    sid = s["screen_id"]
    reqs = req_by_screen.get(sid, [])
    strong = [r for r in reqs if r["tier"] == "STRONG"]
    states = [x.strip() for x in re.split(r"[;,]", s["states"]) if x.strip()]
    regions = [x.strip() for x in re.split(r"[;,]", s["mandatory_regions"]) if x.strip()]
    actions = [x.strip() for x in re.split(r"[;,]", s["primary_actions"]) if x.strip()]

    L.append(f"## {sid} — {s['screen']}\n")
    L.append(f"- **Route:** `{s['route'].replace(':id', '[id]')}`")
    L.append(f"- **Channel:** {s['channel']} · **Process:** {s['process']}")
    # The admin screens live on their own page, built on the ad-* shell; the web and
    # virtual screens are in the section on the — SCREENS — page.
    where = ("page `Admin Shell`" if sid.startswith("SCR-ADM-")
             else "page `— SCREENS —`, section `SCREENS — EN · Light`")
    L.append(f"- **Figma frame:** `{FIGMA_FRAME.get(sid, sid + ' — ' + s['screen'])}`"
             f" on {where}")
    L.append(f"- **Personas:** {s['personas']}")
    L.append(f"- **Permission:** {s['permission_rule']}")
    L.append(f"- **Requirements riding on this screen:** {len(reqs)}"
             f" ({len(strong)} strong)")
    L.append(f"\n**Purpose.** {s['purpose']}\n")

    L.append("**Mandatory regions.** Every one must render. A region with no governed data")
    L.append("renders its state, not an empty div.\n")
    for r in regions:
        L.append(f"- {r}")
    L.append("")

    if actions:
        L.append("**Primary actions.**\n")
        for a in actions:
            L.append(f"- {a}")
        L.append("")

    L.append("**States.** Each has its own frame in `SCREENS — STATES · EN · Light`,")
    L.append(f"named `{sid} — {s['screen']} — … — STATE: <state>`.\n")
    L.append("| State | Frame suffix |")
    L.append("|---|---|")
    for st in states:
        L.append(f"| {st} | `STATE: {st}` |")
    L.append("")

L.append("---\n")
L.append("## Figma → React\n")
L.append("Full map in `component-map.json`. The entries a screen most often needs:\n")
L.append("| Figma | React | Kind |")
L.append("|---|---|---|")
for k, v in cmap.items():
    if k.startswith("_") or not isinstance(v, dict):
        continue
    if v.get("kind") == "icon":
        continue
    react = f"`components/saqeel/{v['react']}`" if v.get("react") else "—"
    L.append(f"| `{k}` | {react} | {v.get('kind','')} |")

L.append("\n### Not a component\n")
L.append("`panel-content/*` blocks are per-screen content, not reusable components. Build")
L.append("them as JSX inside the route. The name after the slash is screen + region.\n")

(HERE / "SCREEN-SPEC.md").write_text("\n".join(L) + "\n", encoding="utf-8")

in_scope = [x for x in screens if x["channel"] not in OUT_OF_SCOPE]
total_states = sum(len([y for y in re.split(r"[;,]", x["states"]) if y.strip()]) for x in in_scope)
print(f"screens documented : {len(in_scope)}")
print(f"states documented  : {total_states}")
print(f"component mappings : {len([k for k,v in cmap.items() if not k.startswith('_')])}")
print(f"wrote {HERE / 'SCREEN-SPEC.md'}")
