-- ============================================================================
-- Migration 0020 — FIX WAVE F2 · Evidence & media depth + inspection numbering
--   + audit-trigger gap closure.
-- Closes: M04-163 (replace-with-archive), M04-164 (soft delete + audit event),
--         M04-209 (inspection numbering), M04-136/137 (prior approved
--         inspection comparison read), M04-093/130/152/169 + FND-014 audit leg
--         (checklist_responses / evidence audit triggers).
-- NOT applied by the build agent; the orchestrator applies migrations.
-- RLS: every touched table already has RLS enabled (0001) — re-asserted
-- idempotently below; new access paths are explicit named policies.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1 · Evidence lifecycle columns (M04-163 / M04-164) — never destructive.
--     REPLACE archives the old row and points it at its successor.
--     DELETE is soft: deleted_at + mandatory reason; the row (and its stored
--     file + sha256 custody chain) survives for audit.
-- ---------------------------------------------------------------------------
alter table evidence enable row level security;                 -- idempotent re-assert
alter table evidence
  add column if not exists archived_at   timestamptz,
  add column if not exists superseded_by uuid references evidence(id),
  add column if not exists deleted_at    timestamptz,
  add column if not exists delete_reason text;
comment on column evidence.archived_at   is 'Set when the file was replaced (M04-163) — archived, never destroyed.';
comment on column evidence.superseded_by is 'Evidence row that replaced this one (M04-163 replace-with-archive).';
comment on column evidence.deleted_at    is 'Soft delete (M04-164) — removed from the inspection package, retained for audit.';
comment on column evidence.delete_reason is 'Mandatory reason accompanying a soft delete (M04-164).';

-- Soft delete requires a reason (M04-164)
do $$ begin
  alter table evidence add constraint evidence_delete_reason_ck
    check (deleted_at is null or (delete_reason is not null and length(trim(delete_reason)) > 0));
exception when duplicate_object then null; end $$;

-- Existing guards keep holding: evidence_rw (0002) scopes updates to the
-- assigned inspector; trg_guard_evd (0002) rejects any mutation once the
-- inspection is submitted — archive/delete are only possible while in progress.

-- ---------------------------------------------------------------------------
-- 2 · Inspection numbering (M04-209) — 'INS-YYYY-000123' from a DB sequence.
--     Stamped at inspection start: the startup flow calls next_inspection_no()
--     and inserts the value; the BEFORE INSERT trigger backstops any writer
--     that skips the RPC so no inspection is ever unnumbered.
-- ---------------------------------------------------------------------------
alter table inspections enable row level security;              -- idempotent re-assert
create sequence if not exists inspection_no_seq;
alter table inspections add column if not exists inspection_no text unique;
comment on column inspections.inspection_no is 'Official inspection number INS-YYYY-NNNNNN (M04-209), generated by next_inspection_no() at start.';

create or replace function next_inspection_no() returns text
language sql security definer set search_path = public as
$$ select 'INS-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('inspection_no_seq')::text, 6, '0') $$;
revoke all on function next_inspection_no() from public;
grant execute on function next_inspection_no() to authenticated;

create or replace function stamp_inspection_no() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.inspection_no is null then new.inspection_no := next_inspection_no(); end if;
  return new;
end $$;
drop trigger if exists trg_inspection_no on inspections;
create trigger trg_inspection_no before insert on inspections
  for each row execute function stamp_inspection_no();

-- ---------------------------------------------------------------------------
-- 3 · Audit-trigger gap (ENG-12 / FND-003 · M04-093/130/152/169, FND-014 leg):
--     extend the generic append-only audit trigger (0002/0004) to
--     checklist_responses and evidence. Answer changes, evidence custody,
--     archive and soft-delete events all land in audit_events.
-- ---------------------------------------------------------------------------
alter table checklist_responses enable row level security;      -- idempotent re-assert
drop trigger if exists trg_audit_checklist_responses on checklist_responses;
create trigger trg_audit_checklist_responses
  after insert or update or delete on checklist_responses
  for each row execute function audit_row_change();
drop trigger if exists trg_audit_evidence on evidence;
create trigger trg_audit_evidence
  after insert or update or delete on evidence
  for each row execute function audit_row_change();

-- ---------------------------------------------------------------------------
-- 4 · Previous-inspection comparison read (M04-136 / M04-137):
--     an inspector assigned to any visit of a factory may READ that factory's
--     APPROVED prior inspections (answers + evidence) for field comparison.
--     SECURITY DEFINER helper mirrors is_assigned_inspector (0002) to avoid
--     nested-RLS recursion inside policy expressions.
-- ---------------------------------------------------------------------------
create or replace function inspects_same_factory(v uuid) returns boolean
language sql stable security definer set search_path = public as
$$ select exists (
     select 1
     from visits target
     join visits mine on mine.factory_id = target.factory_id
     join assignments a on a.visit_id = mine.id
     where target.id = v and a.inspector_id = auth.uid()) $$;

do $$ begin
  create policy inspections_read_prior_approved on inspections for select using (
    status = 'approved' and inspects_same_factory(visit_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy responses_read_prior_approved on checklist_responses for select using (
    exists (select 1 from inspections i where i.id = inspection_id
            and i.status = 'approved' and inspects_same_factory(i.visit_id)));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy evidence_read_prior_approved on evidence for select using (
    exists (select 1 from inspections i where i.id = inspection_id
            and i.status = 'approved' and inspects_same_factory(i.visit_id)));
exception when duplicate_object then null; end $$;

-- Prior-approved lookup path: latest approved inspection per factory.
create index if not exists idx_inspections_status_started
  on inspections (status, started_at desc);
create index if not exists idx_evidence_superseded_by on evidence (superseded_by);
