-- Admin revamp localization completion: seeds the admin.* keys introduced by
-- the SAQEEL admin surface revamp (configuration journey, package designer
-- create/handoff copy, violations CCR cutover notices, route-boundary refusal)
-- that had English-only t() fallbacks and no ui_strings source.
-- Draft translations are intentionally reviewable and never overwrite rows
-- that a human localization reviewer has already promoted beyond draft status.

with strings(key, en, ar) as (values
  ('admin.reg.r1.status.active', 'Active', 'فعال'),
  ('admin.reg.r1.status.scheduled', 'Scheduled', 'مجدول'),
  ('admin.reg.requestOnly.title', 'Request-controlled content', 'محتوى خاضع لطلب تغيير'),
  ('admin.reg.requestOnly.create', 'Create configuration request', 'إنشاء طلب تهيئة'),
  ('admin.reg.lifecycle.activationReason', 'Activation reason', 'سبب التفعيل'),
  ('admin.reg.lifecycle.deactivationReason', 'Deactivation reason', 'سبب إلغاء التفعيل'),
  ('admin.reg.lifecycle.applying', 'Applying…', 'جارٍ التطبيق…'),
  ('admin.reg.lifecycle.activate', 'Activate regulation', 'تفعيل اللائحة'),
  ('admin.reg.lifecycle.deactivate', 'Deactivate regulation', 'إلغاء تفعيل اللائحة'),
  ('admin.reg.lifecycle.alreadyMatched', 'State already matched.', 'الحالة مطابقة بالفعل.'),
  ('admin.reg.lifecycle.changedTo', 'Lifecycle changed to {status}.', 'تم تغيير دورة الحياة إلى {status}.'),
  ('admin.reg.lifecycle.cascaded', 'Cascaded: {items} items, {violations} violations, {penalties} penalties.', 'تم تطبيق التغيير على: {items} بنود، {violations} مخالفات، {penalties} جزاءات.'),
  ('admin.reg.lifecycle.childrenNotReactivated', 'Child configurations were not reactivated.', 'لم تتم إعادة تفعيل التهيئات التابعة.'),
  ('admin.reg.lifecycle.missingReference', 'Missing regulation reference.', 'مرجع اللائحة مفقود.'),
  ('admin.reg.lifecycle.reasonRequired', 'A lifecycle reason is required.', 'سبب تغيير دورة الحياة مطلوب.'),
  ('admin.reg.lifecycle.denied', 'You are not authorized to change regulation lifecycle state.', 'ليست لديك صلاحية تغيير حالة دورة حياة اللائحة.'),
  ('admin.reg.lifecycle.notFound', 'The regulation no longer exists or is outside your scope.', 'اللائحة غير موجودة أو خارج نطاق صلاحيتك.'),
  ('admin.reg.lifecycle.providerError', 'The lifecycle change could not be completed. Retry safely.', 'تعذر إكمال تغيير دورة الحياة. أعد المحاولة بأمان.'),
  ('admin.revamp.survey.governance.validate', 'Publish revalidates sections, items, response mappings, evidence and action-form dependencies.', 'يعيد النشر التحقق من الأقسام والبنود وربط الإجابات والأدلة واعتماديات نماذج الإجراءات.'),
  ('admin.revamp.survey.governance.maker', 'Maker-checker approval is enforced by the existing publish actions and database guards.', 'يُفرض فصل المُعدّ عن المعتمد عبر إجراءات النشر وضوابط قاعدة البيانات الحالية.'),
  ('admin.revamp.survey.governance.runtime', 'Execution consumes only the locked package version selected for the visit.', 'يستخدم التنفيذ فقط إصدار الحزمة المقفل المختار للزيارة.'),
  ('admin.revamp.survey.subtitle', 'Inspection forms, sections and response rules', 'نماذج التفتيش والأقسام وقواعد الإجابة'),
  ('admin.revamp.hub.rules', 'Rules & content', 'القواعد والمحتوى'),
  ('admin.revamp.governance', 'Governance on this surface', 'الحوكمة في هذه الواجهة'),
  ('admin.revamp.reconstruction', 'Reconstruction note', 'ملاحظة إعادة البناء'),
  ('admin.revamp.survey.metric.published', 'Published packages', 'الحزم المنشورة'),
  ('admin.revamp.survey.metric.published.note', 'Currently effective versions only', 'الإصدارات النافذة حالياً فقط'),
  ('admin.revamp.survey.metric.drafts', 'Draft packages', 'مسودات الحزم'),
  ('admin.revamp.survey.metric.drafts.note', 'Not selectable by live visits', 'غير قابلة للاختيار للزيارات الفعلية'),
  ('admin.revamp.survey.tabs.packages', 'Packages', 'الحزم'),
  ('admin.revamp.survey.tabs.items', 'Sections & items', 'الأقسام والبنود'),
  ('admin.revamp.survey.tabs.forms', 'Action forms', 'نماذج الإجراءات'),
  ('admin.revamp.survey.tabs.versions', 'Versions', 'الإصدارات'),
  ('admin.recordDrawer.code', 'Code', 'الرمز'),
  ('admin.recordDrawer.actionForms', 'Action forms', 'نماذج الإجراءات'),
  ('admin.recordDrawer.effective', 'Effective period', 'فترة النفاذ'),
  ('admin.reg.r1.detailTitle', 'Regulation record', 'سجل اللائحة'),
  ('admin.reg.requests', 'Configuration Requests', 'طلبات التهيئة'),
  ('admin.configurationJourney.ariaLabel', 'Configuration journey', 'مسار التهيئة'),
  ('admin.configurationJourney.eyebrow', 'Governed configuration', 'تهيئة محكومة'),
  ('admin.configurationJourney.title', 'Regulation to inspection package', 'من اللائحة إلى حزمة التفتيش'),
  ('admin.configurationJourney.description', 'Publish the legal source, prepare immutable templates, then assemble and publish the inspection package that references them.', 'انشر المصدر القانوني، وجهّز القوالب غير القابلة للتغيير، ثم جمّع حزمة التفتيش التي تشير إليها وانشرها.'),
  ('admin.configurationJourney.regulations', 'Regulations', 'اللوائح'),
  ('admin.configurationJourney.templates', 'Templates', 'القوالب'),
  ('admin.configurationJourney.packages', 'Packages', 'الحزم'),
  ('admin.configurationJourney.current', 'Current step', 'الخطوة الحالية'),
  ('admin.reg.attachments.unknown', 'Attachment footprint is unknown for this canonical version; no zero claim is made.', 'عدد المرفقات غير معروف لهذه النسخة المعتمدة؛ ولا يُدّعى أنه صفر.'),
  ('admin.pkg.create.heading', 'Create a new package', 'إنشاء حزمة جديدة'),
  ('admin.pkg.create.codeLabel', 'Package code', 'رمز الحزمة'),
  ('admin.pkg.create.codePlaceholder', 'Example: PKG-CHEM-001', 'مثال: PKG-CHEM-001'),
  ('admin.pkg.create.titleLabel', 'Package title', 'عنوان الحزمة'),
  ('admin.pkg.create.titlePlaceholder', 'Example: Chemical Storage Inspection', 'مثال: تفتيش تخزين المواد الكيميائية'),
  ('admin.pkg.create.scopeLabel', 'Scope (optional)', 'النطاق (اختياري)'),
  ('admin.pkg.create.scopePlaceholder', 'Example: Chemical facilities', 'مثال: المنشآت الكيميائية'),
  ('admin.pkg.create.create', 'Create package', 'إنشاء الحزمة'),
  ('admin.pkg.create.created', 'Package created', 'تم إنشاء الحزمة'),
  ('admin.pkg.editor.evidence.photo', 'Photo', 'صورة'),
  ('admin.pkg.editor.evidence.video', 'Video', 'فيديو'),
  ('admin.pkg.editor.evidence.document', 'Document', 'مستند'),
  ('admin.pkg.editor.evidence.comment', 'Comment', 'تعليق'),
  ('admin.template.type.form', 'Form', 'نموذج'),
  ('admin.template.type.report', 'Report', 'تقرير'),
  ('admin.template.type.actionForm', 'Action form', 'نموذج إجراء'),
  ('admin.template.type.penalty', 'Penalty', 'عقوبة'),
  ('admin.pkg.empty.bodyReady', 'No packages exist yet. Create one above.', 'لا توجد حزم بعد. أنشئ واحدة أعلاه.'),
  ('admin.pkg.empty.bodyReadOnly', 'No packages exist yet. Creating one needs write access.', 'لا توجد حزم بعد. يتطلب إنشاؤها صلاحية كتابة.'),
  ('admin.pkg.handoff.plan', 'Plan a visit using this version', 'خطط زيارة باستخدام هذه النسخة'),
  ('admin.pkg.handoff.note', 'Planner access and the current package contract are verified again on opening.', 'يُتحقق مجددًا من صلاحية المخطط ومن عقد الحزمة الحالي عند الفتح.'),
  ('admin.viol.error.ccrRequired', 'Violation and penalty configuration must use a governed Compliance Configuration Request. Direct writes remain disabled until typed validation and guarded transitions are deployed.', 'يجب أن تمر تهيئة المخالفات والعقوبات عبر طلب تهيئة امتثال محكوم. تبقى الكتابة المباشرة معطلة حتى نشر التحقق المصنّف والتحولات المحمية.'),
  ('admin.viol.ccrRequired.title', 'Configuration Request required.', 'يلزم طلب تهيئة.'),
  ('admin.viol.ccrRequired.link', 'Open Compliance Configuration Requests', 'فتح طلبات تهيئة الامتثال'),
  ('admin.unauthorized.request', 'Request access', 'طلب صلاحية الوصول'),
  ('admin.unauthorized.detail', 'Administration routes are guarded by the administrator role family. A Planner reaches the destination and is refused at the boundary.', 'مسارات الإدارة محمية بعائلة أدوار المسؤول. يصل المخطط إلى الوجهة ويُرفض عند الحد.')
)
insert into ui_strings (key, en, ar, status, context)
select key, en, ar, 'draft', 'Admin revamp localization completion 2026-08-08'
from strings
on conflict (key) do update set
  en = excluded.en,
  ar = excluded.ar,
  context = excluded.context,
  updated_at = now()
where ui_strings.status = 'draft';
