-- CD-010 (SCR-ADM-040 · Violation Catalogue) + CD-011 (SCR-ADM-041 · Penalty
-- Mapping, logical penalty mode inside /admin/violations) — Arabic localization seed.
-- Arabic values are machine/unreviewed draft copy for already-accepted EN UI strings;
-- no new Arabic scope, policy, monetary value, or behaviour is introduced.
-- Seeded status='draft' (migration 0013 gate). The guarded upsert NEVER overwrites a
-- row a human already reviewed, and keeps shared keys consistent. EN mirrors the exact
-- in-code fallback so the two never drift.

insert into ui_strings (key, en, ar, status, context) values
  -- form (CD-010 create violation code)
  ('admin.viol.form.code',            'Code', 'الرمز', 'draft', 'CD-010 form'),
  ('admin.viol.form.title',           'Title', 'العنوان', 'draft', 'CD-010 form'),
  ('admin.viol.form.titlePlaceholder','Violation title', 'عنوان المخالفة', 'draft', 'CD-010 form placeholder'),
  ('admin.viol.form.level',           'Level', 'المستوى', 'draft', 'CD-010 form'),
  ('admin.viol.form.levelPlaceholder','Level…', 'المستوى…', 'draft', 'CD-010 form placeholder'),
  ('admin.viol.form.clause',          'Clause', 'البند', 'draft', 'CD-010 form'),
  ('admin.viol.form.selectClause',    'Select clause…', 'اختر البند…', 'draft', 'CD-010 form placeholder'),
  ('admin.viol.form.activeFrom',      'Active from', 'ساري من', 'draft', 'CD-010 form'),
  ('admin.viol.form.creating',        'Creating…', 'جارٍ الإنشاء…', 'draft', 'CD-010 form pending'),
  ('admin.viol.form.create',          'Create violation code', 'إنشاء رمز مخالفة', 'draft', 'CD-010 form action'),
  ('admin.viol.form.created',         'created', 'تم الإنشاء', 'draft', 'CD-010 form success'),
  -- mapping form (CD-011 create penalty mapping)
  ('admin.viol.map.penaltyRef',       'Penalty ref', 'مرجع العقوبة', 'draft', 'CD-011 mapping form'),
  ('admin.viol.map.legalBasis',       'Legal basis', 'الأساس القانوني', 'draft', 'CD-011 mapping — mandatory'),
  ('admin.viol.map.legalBasisPlaceholder','SBC-801 §5.1 / M-43', 'SBC-801 §5.1 / M-43', 'draft', 'CD-011 mapping placeholder (ref token, LTR)'),
  ('admin.viol.map.mappingVersion',   'Mapping version', 'إصدار الربط', 'draft', 'CD-011 mapping form'),
  ('admin.viol.map.penaltyRange',     'Range preset', 'إعداد النطاق', 'draft', 'CD-011 mapping — token not amount'),
  ('admin.viol.map.rangeApproved',    'Approved schedule', 'الجدول المعتمد', 'draft', 'CD-011 mapping preset'),
  ('admin.viol.map.rangeNone',        'None', 'لا شيء', 'draft', 'CD-011 mapping preset'),
  ('admin.viol.map.repeatRule',       'Repeat-rule preset', 'قاعدة التكرار', 'draft', 'CD-011 mapping — token'),
  ('admin.viol.map.repeatEscalate',   'Repeat in 12mo → escalate one level', 'التكرار خلال 12 شهرًا ← تصعيد مستوى واحد', 'draft', 'CD-011 mapping preset'),
  ('admin.viol.map.repeatNone',       'None', 'لا شيء', 'draft', 'CD-011 mapping preset'),
  ('admin.viol.map.mapping',          'Mapping…', 'جارٍ الربط…', 'draft', 'CD-011 mapping pending'),
  ('admin.viol.map.mapTo',            'Map penalty to', 'اربط العقوبة بـ', 'draft', 'CD-011 mapping action'),
  ('admin.viol.map.done',             'mapped', 'تم الربط', 'draft', 'CD-011 mapping success'),
  ('admin.viol.map.versionRef',       '— immutable reference for inspection results (FLD-PEN-001); the row itself is not locked.', '— مرجع ثابت لنتائج التفتيش (FLD-PEN-001)؛ السجل نفسه غير مقفل.', 'draft', 'CD-011 FLD-PEN-001'),
  -- action-level validation errors
  ('admin.viol.err.session',          'Session expired — sign in again.', 'انتهت الجلسة — سجّل الدخول مجددًا.', 'draft', 'CD-010/011 action error'),
  ('admin.viol.err.codeTitle',        'Code and title are required.', 'الرمز والعنوان مطلوبان.', 'draft', 'CD-010 validation'),
  ('admin.viol.err.level',            'Level must be L1, L2 or L3.', 'يجب أن يكون المستوى L1 أو L2 أو L3.', 'draft', 'CD-010 validation'),
  ('admin.viol.err.clause',           'A regulation clause is required (legal anchor).', 'يلزم بند تنظيمي (مرساة قانونية).', 'draft', 'CD-010 validation'),
  ('admin.viol.err.activeFrom',       'Active-from date is required.', 'تاريخ بدء السريان مطلوب.', 'draft', 'CD-010 validation'),
  ('admin.viol.err.dupCode',          'A violation code with this identifier already exists.', 'يوجد بالفعل رمز مخالفة بهذا المعرّف.', 'draft', 'CD-010 unique-constraint negative'),
  ('admin.viol.err.write',            'The change could not be saved. Nothing was changed. Try again.', 'تعذّر حفظ التغيير. لم يتغيّر شيء. حاول مجددًا.', 'draft', 'CD-010/011 neutral write error'),
  ('admin.viol.map.err.pickViolation','Pick the violation code to map.', 'اختر رمز المخالفة المراد ربطه.', 'draft', 'CD-011 validation'),
  ('admin.viol.map.err.refVersion',   'Penalty ref and mapping version are required.', 'مرجع العقوبة وإصدار الربط مطلوبان.', 'draft', 'CD-011 validation'),
  ('admin.viol.map.err.legalBasis',   'Legal basis is required (never invent one).', 'الأساس القانوني مطلوب (لا يُختلق أبدًا).', 'draft', 'CD-011 validation'),
  ('admin.viol.map.err.range',        'Pick a penalty range preset.', 'اختر إعداد نطاق العقوبة.', 'draft', 'CD-011 validation'),
  ('admin.viol.map.err.repeat',       'Pick a repeat rule preset.', 'اختر إعداد قاعدة التكرار.', 'draft', 'CD-011 validation'),
  ('admin.viol.map.err.dupMapping',   'This violation already has a penalty mapping (one mapping per violation).', 'لهذه المخالفة ربط عقوبة بالفعل (ربط واحد لكل مخالفة).', 'draft', 'CD-011 one-to-one negative'),
  -- severity + derived lifecycle
  ('admin.viol.severity',             'severity', 'الخطورة', 'draft', 'CD-010 severity — glyph+word+colour'),
  ('admin.viol.lc.active',            'active', 'ساري', 'draft', 'CD-010 derived lifecycle'),
  ('admin.viol.lc.future',            'not yet active', 'لم يبدأ سريانه بعد', 'draft', 'CD-010 derived lifecycle'),
  ('admin.viol.lc.deactivated',       'deactivated', 'مُلغى التفعيل', 'draft', 'CD-010 derived lifecycle'),
  ('admin.viol.derived',              'Lifecycle derived from active-from', 'دورة الحياة مشتقة من تاريخ بدء السريان', 'draft', 'CD-010 explicit derivation'),
  ('admin.viol.to',                   'active-to', 'ساري حتى', 'draft', 'CD-010 derivation'),
  ('admin.viol.asOf',                 'as of today', 'حتى تاريخ اليوم', 'draft', 'CD-010 derivation'),
  -- mode tabs + titles
  ('admin.viol.mode.label',           'Catalogue view', 'عرض الفهرس', 'draft', 'CD-010/011 tablist label'),
  ('admin.viol.mode.catalogue',       'Violation catalogue', 'فهرس المخالفات', 'draft', 'CD-010 mode tab'),
  ('admin.viol.mode.penalty',         'Penalty mapping', 'ربط العقوبات', 'draft', 'CD-011 mode tab'),
  ('admin.viol.title',                'Violation Catalogue', 'فهرس المخالفات', 'draft', 'CD-010 page title'),
  ('admin.viol.penalty.title',        'Penalty Mapping', 'ربط العقوبات', 'draft', 'CD-011 page title'),
  -- stale / error / recovery / read-only
  ('admin.viol.readAt',               'Read at', 'قُرئت في', 'draft', 'CD-010/011 stale — read fact'),
  ('admin.viol.stale',                'data may have changed since — reopen to refresh (no staleness verdict exists).', 'قد تكون البيانات تغيّرت منذ ذلك — أعد فتح الصفحة للتحديث (لا يوجد حكم تقادم).', 'draft', 'CD-010/011 stale — no invented duration'),
  ('admin.viol.error.title',          'Couldn’t load the violation catalogue.', 'تعذّر تحميل فهرس المخالفات.', 'draft', 'CD-010/011 degraded'),
  ('admin.viol.error.body',           'The requested data is temporarily unavailable. Nothing was changed. Try again.', 'البيانات المطلوبة غير متاحة مؤقتًا. لم يتغيّر شيء. حاول مجددًا.', 'draft', 'CD-010/011 neutral load error'),
  ('admin.viol.error.retry',          'Retry', 'إعادة المحاولة', 'draft', 'CD-010/011 recovery'),
  ('admin.viol.readonly',             'Read-only view — configuration writes require the compliance-admin or form-admin role (RLS). No route guard blocks this page; visibility is not authority.', 'عرض للقراءة فقط — تتطلب كتابة التهيئة دور مشرف الامتثال أو مشرف النماذج (RLS). لا يحجب هذه الصفحة حارس مسار؛ الظهور ليس صلاحية.', 'draft', 'CD-010/011 read-only (guard BLOCKED)'),
  -- penalty mode: lens + columns
  ('admin.viol.lens.title',           'Mapping Validation Lens', 'عدسة التحقق من الربط', 'draft', 'CD-011 signature'),
  ('admin.viol.lens.intro',           'Creating a mapping passes exactly four proven checks. No lifecycle, approval, or monetary value exists on this table.', 'يجتاز إنشاء الربط أربعة فحوص مثبتة بالضبط. لا توجد دورة حياة أو اعتماد أو قيمة مالية في هذا الجدول.', 'draft', 'CD-011 lens intro'),
  ('admin.viol.lens.c1',              'The violation is not already mapped (one mapping per violation).', 'ألا تكون المخالفة مرتبطة بالفعل (ربط واحد لكل مخالفة).', 'draft', 'CD-011 lens check 1'),
  ('admin.viol.lens.c2',              'A second mapping is rejected by the database unique constraint.', 'يرفض قيد التفرد في قاعدة البيانات أي ربط ثانٍ.', 'draft', 'CD-011 lens check 2'),
  ('admin.viol.lens.c3',              'Legal basis is present before create (never invented).', 'وجود الأساس القانوني قبل الإنشاء (لا يُختلق أبدًا).', 'draft', 'CD-011 lens check 3'),
  ('admin.viol.lens.c4',              'Range and repeat presets are governed tokens, not amounts.', 'إعدادات النطاق والتكرار رموز محكومة، وليست مبالغ.', 'draft', 'CD-011 lens check 4'),
  ('admin.viol.lens.mapped',          'one-to-one mapping satisfied', 'تحقّق الربط الأحادي', 'draft', 'CD-011 lens status'),
  ('admin.viol.lens.unmapped',        'no mapping yet — one is required', 'لا يوجد ربط بعد — الربط مطلوب', 'draft', 'CD-011 lens status'),
  ('admin.viol.penalty.col.violation','Violation', 'المخالفة', 'draft', 'CD-011 workspace column'),
  ('admin.viol.penalty.col.lens',     'Validation lens', 'عدسة التحقق', 'draft', 'CD-011 workspace column'),
  ('admin.viol.penalty.col.record',   'Penalty mapping record', 'سجل ربط العقوبة', 'draft', 'CD-011 workspace column'),
  ('admin.viol.penalty',              'Penalty', 'العقوبة', 'draft', 'CD-011 record'),
  ('admin.viol.penalty.readonly',     'Unmapped — a compliance/form admin can add the mapping.', 'غير مربوط — يمكن لمشرف الامتثال/النماذج إضافة الربط.', 'draft', 'CD-011 read-only unmapped'),
  ('admin.viol.penalty.empty.title',  'No violation codes to map', 'لا توجد رموز مخالفات لربطها', 'draft', 'CD-011 empty'),
  ('admin.viol.penalty.empty.body',   'Create a violation code in the catalogue first; a penalty maps one-to-one onto it.', 'أنشئ رمز مخالفة في الفهرس أولًا؛ تُربط العقوبة به ربطًا أحاديًا.', 'draft', 'CD-011 empty'),
  ('admin.viol.penalty.footer',       'One violation = one penalty (M09-004) — the database rejects a second mapping. Presets are governed tokens, never monetary or legal values. The contract route /admin/penalties is not a live URL; this is its logical mode.', 'مخالفة واحدة = عقوبة واحدة (M09-004) — ترفض قاعدة البيانات أي ربط ثانٍ. الإعدادات رموز محكومة، وليست قيمًا مالية أو قانونية. المسار التعاقدي /admin/penalties ليس رابطًا فعليًا؛ هذا وضعه المنطقي.', 'draft', 'CD-011 footer'),
  -- catalogue mode: rows + empty + footer
  ('admin.viol.empty.title',          'No violation codes configured', 'لا توجد رموز مخالفات مُهيأة', 'draft', 'CD-010 empty'),
  ('admin.viol.empty.body',           'Violations generate automatically from configured responses (M09-003). Add the first catalogue code above.', 'تُولَّد المخالفات تلقائيًا من الإجابات المُهيأة (M09-003). أضف أول رمز في الفهرس أعلاه.', 'draft', 'CD-010 empty'),
  ('admin.viol.mapped',               'penalty mapped', 'العقوبة مربوطة', 'draft', 'CD-010 mapped chip'),
  ('admin.viol.unmapped',             'unmapped', 'غير مربوط', 'draft', 'CD-010 unmapped chip'),
  ('admin.viol.trace',                'Legal trace', 'التتبّع القانوني', 'draft', 'CD-010 clause-link trace'),
  ('admin.viol.noAnchor',             'No clause anchor', 'لا توجد مرساة بند', 'draft', 'CD-010 trace'),
  ('admin.viol.footer',               'Violations generate automatically from configured responses; the inspector can never type or override one (M09-003/026). Legal basis belongs to the penalty mapping, not the code row. Config violation_codes is distinct from runtime violations, and has no audit trigger.', 'تُولَّد المخالفات تلقائيًا من الإجابات المُهيأة؛ ولا يمكن للمفتش كتابتها أو تجاوزها (M09-003/026). الأساس القانوني يخص ربط العقوبة لا صفّ الرمز. جدول violation_codes للتهيئة يختلف عن جدول violations وقت التشغيل، ولا يملك مُطلق تدقيق.', 'draft', 'CD-010 footer'),
  -- blocked contract targets (shared heading + per-leg labels)
  ('admin.viol.blocked.heading',      'Contract targets — not enabled on this schema', 'أهداف تعاقدية — غير مفعّلة على هذا المخطط', 'draft', 'CD-010/011 blocked heading'),
  ('admin.viol.blocked.body',         'These capabilities are HANDOFF_BLOCKED: no column, policy, trigger, or route exists for them yet.', 'هذه القدرات محجوبة (HANDOFF_BLOCKED): لا يوجد عمود أو سياسة أو مُطلق أو مسار لها بعد.', 'draft', 'CD-011 blocked body'),
  ('admin.viol.blocked.catBody',      'violation_codes has no category, applicability, edit, version, deactivate, usage count, trace query, or audit trigger. Each stays HANDOFF_BLOCKED.', 'لا يملك violation_codes فئة أو انطباقًا أو تعديلًا أو إصدارًا أو إلغاء تفعيل أو عدّ استخدام أو استعلام تتبّع أو مُطلق تدقيق. يبقى كلٌّ منها محجوبًا (HANDOFF_BLOCKED).', 'draft', 'CD-010 blocked body'),
  ('admin.viol.blocked.title',        'contract target, not enabled', 'هدف تعاقدي، غير مفعّل', 'draft', 'CD-010/011 blocked target tooltip'),
  ('admin.viol.blk.category',         'Category', 'الفئة', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.applicability',    'Applicability', 'الانطباق', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.edit',             'Edit code', 'تعديل الرمز', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.version',          'Version history', 'سجل الإصدارات', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.deactivate',       'Deactivate', 'إلغاء التفعيل', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.usage',            'Usage count', 'عدد الاستخدام', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.trace',            'Trigger-trace query', 'استعلام تتبّع الإطلاق', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.audit',            'Audit timeline', 'مسار التدقيق الزمني', 'draft', 'CD-010 blocked leg'),
  ('admin.viol.blk.effective',        'Effective periods', 'فترات السريان', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.overlap',          'Overlap / gap engine', 'محرّك التداخل/الفجوات', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.cardinality',      'Cardinality > 1:1', 'تعدّدية أكبر من 1:1', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.lifecycle',        'Submit → approve → publish', 'تقديم ← اعتماد ← نشر', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.makerChecker',     'Maker-checker', 'المُنشئ-المدقّق', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.immutability',     'Mapping row lock', 'قفل صفّ الربط', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.mappingAudit',     'Mapping audit timeline', 'مسار تدقيق الربط الزمني', 'draft', 'CD-011 blocked leg'),
  ('admin.viol.blk.routeGuard',       'Admin-family route guard', 'حارس مسار عائلة الإدارة', 'draft', 'CD-011 blocked leg')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';   -- never clobber a human-reviewed translation
