-- Migration 20260721090000 — Phase-3 performance remediation (K-013 / K-014).
-- REVIEW BEFORE APPLY: generated by the independent perf post-mortem
-- (docs/performance/kimi-independent-review.md). NOT yet applied to any live
-- database. Verify index names do not collide with concurrently-created
-- indexes, then apply through the normal migration review flow.
--
-- K-013 — missing indexes on hot filter/sort/join columns. The foundation
-- migration (0001) created these tables with PKs only; the dashboard, visits
-- list, field home, shell region scan and inspection workspace all filter or
-- order on these columns per navigation.
--
-- K-014 — RLS initplan: has_role / has_any_role / is_assigned_inspector call
-- bare auth.uid(), so Postgres re-evaluates it per candidate row. Wrapping as
-- (select auth.uid()) lets the planner cache it once per statement — the same
-- pattern the team already applied to two individual policies in
-- 0029_cd023_rls_initplan.sql and 20260719040000_dec_f_rls_initplan_fix.sql.
-- Fixing the three shared functions covers every policy that uses them at
-- once. Bodies are behavior-identical (same predicate, plan-cached).

create index if not exists visits_window_start_idx
  on public.visits (window_start);
create index if not exists visits_planning_status_idx
  on public.visits (planning_status);
create index if not exists checklist_responses_inspection_idx
  on public.checklist_responses (inspection_id);
create index if not exists violations_inspection_idx
  on public.violations (inspection_id);
create index if not exists factories_region_idx
  on public.factories (region);
create index if not exists assignments_inspector_idx
  on public.assignments (inspector_id);
-- dashboard timeline: collectLatestAudit filters object_id IN (...) + occurred_at range
create index if not exists audit_events_object_occurred_idx
  on public.audit_events (object_id, occurred_at desc);

create or replace function has_role(r text) returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from user_roles where user_id = (select auth.uid()) and role_key = r) $$;

create or replace function has_any_role(rs text[]) returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from user_roles where user_id = (select auth.uid()) and role_key = any(rs)) $$;

create or replace function is_assigned_inspector(v uuid) returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from assignments a where a.visit_id = v and a.inspector_id = (select auth.uid())) $$;
