-- Plain-language terminology remediation — Arabic strings (Wave 4)
-- Guarded upsert: never clobbers a human-reviewed translation (status='draft' only).
-- English source values here mirror the code fallbacks already shipped in Waves 1-3.
insert into ui_strings (key, en, ar, status, context) values
  ('admin.bulkvio.factoriesError', 'The factory list is unavailable in this environment.', 'قائمة المنشآت غير متاحة في هذه البيئة.', 'draft', 'Error banner when factory data fails to load, /admin/bulk-violations (already paired inline in source, reused verbatim)'),
  ('admin.bulkvio.title', 'Issue Multiple Violations', 'إصدار عدة مخالفات', 'draft', 'Page title / Shell title, /admin/bulk-violations'),
  ('admin.bulkvio.unauthorized.body', 'Issue Multiple Violations (DEC-L) is available to Operations and Compliance Admin roles only.', 'إصدار عدة مخالفات (DEC-L) متاح لدوري العمليات ومسؤول الامتثال فقط.', 'draft', 'Unauthorized-role empty state body, /admin/bulk-violations (already paired inline in source, reused verbatim)'),
  ('admin.overview.r2.family.audit', 'Activity Log', 'سجل النشاط', 'draft', 'Admin landing page — configuration evidence spine, family label (renamed from ''Audit trail'')'),
  ('admin.overview.r2.family.compliance', 'Inspection Rules', 'قواعد التفتيش', 'draft', 'Admin landing page — configuration evidence spine, family label (renamed from ''Compliance Library'')'),
  ('admin.overview.r2.family.enforcement', 'Violations & Penalties', 'المخالفات والعقوبات', 'draft', 'Admin landing page — configuration evidence spine, family label (renamed from ''Enforcement Library'')'),
  ('admin.pkg.immutable.title', 'Published version — locked and cannot be edited.', 'نسخة منشورة — مقفلة ولا يمكن تعديلها.', 'draft', 'Admin > Package designer — published version banner'),
  ('admin.pkg.impact.pinnedHint', 'Existing work stays on the checklist version it downloaded; publishing never silently re-versions it.', 'يظل العمل القائم على نسخة قائمة التفتيش التي جرى تنزيلها؛ النشر لا يُغيّر نسختها دون علم أحد.', 'draft', 'Admin > Package designer — publish impact panel hint'),
  ('admin.pkg.overview.body', 'Drafts are editable. Publishing runs dependency validation and maker-checker approval; published and locked definitions remain final and cannot be edited.', 'المسودات قابلة للتعديل. النشر يشغّل التحقق من الاعتماديات ويتطلب اعتماد المُراجِع؛ التعريفات المنشورة والمقفلة تبقى نهائية ولا يمكن تعديلها.', 'draft', 'Admin > Packages overview — hero description'),
  ('admin.pkg.publish.published', 'Version published. It is now locked and cannot be edited.', 'تم نشر النسخة. أصبحت الآن مقفلة ولا يمكن تعديلها.', 'draft', 'Admin > Package designer — publish confirmation toast'),
  ('admin.reg.lineage.heading', 'Version history', 'سجل الإصدارات', 'draft', 'Version lineage section heading in regulation detail, /admin/regulations'),
  ('admin.reg.r1.detail.auditNote', 'Regulation-row changes are audit-tracked by the generic trigger. Clause additions on this record are audit-tracked too (trg_audit_regulation_clauses).', 'تُدقَّق تغييرات صف اللائحة عبر المُشغّل العام، كما تُدقَّق إضافات البنود في هذا السجل أيضًا (trg_audit_regulation_clauses).', 'draft', 'Helper caption under regulation detail status lozenge, /admin/regulations'),
  ('admin.reg.r1.empty.body', 'The read succeeded — the list is genuinely empty (MVP1-M09-001: regulations are the parents of inspection items).', 'نجحت القراءة — القائمة فارغة فعلًا (MVP1-M09-001: اللوائح هي أصول عناصر الفحص).', 'draft', 'Empty-state body shown to read-only persona when no regulations exist, /admin/regulations'),
  ('admin.reg.r1.empty.body.writer', 'The read succeeded — the list is genuinely empty. Create the first regulation above (MVP1-M09-001: regulations are the parents of inspection items).', 'نجحت القراءة — القائمة فارغة فعلًا. أنشئ أول لائحة بالأعلى (MVP1-M09-001: اللوائح هي أصول عناصر الفحص).', 'draft', 'Empty-state body shown to writer persona when no regulations exist, /admin/regulations'),
  ('admin.reg.r1.openDossier', 'Open record', 'فتح السجل', 'draft', 'Row action opening a regulation-clause detail record, /admin/regulations'),
  ('admin.reg.r1.title', 'Inspection Rules — regulation register', 'قواعد التفتيش — سجل اللوائح', 'draft', 'Compliance Library (Inspection Rules) page title, /admin/regulations'),
  ('admin.risk.title', 'Risk Settings', 'إعدادات المخاطر', 'draft', 'Page title, /admin/risk (Risk Studio)'),
  ('admin.template.historical', 'Final historical template version.', 'نسخة قالب سابقة نهائية.', 'draft', 'Admin > Governed template registry — historical version label'),
  ('admin.template.intro', 'Create versioned bilingual form, report, action-form, or penalty templates. Published versions are locked and cannot be edited, but can be referenced by package action forms and penalty mappings.', 'أنشئ نسخًا مرقّمة وثنائية اللغة من قوالب النماذج أو التقارير أو نماذج الإجراءات أو الغرامات. النسخ المنشورة مقفلة ولا يمكن تعديلها، لكن يمكن الإشارة إليها من نماذج إجراءات الحزم وربط الغرامات.', 'draft', 'Admin > Governed template registry — intro text'),
  ('admin.wf.empty.title', 'No workflow settings published', 'لا توجد إعدادات سير عمل منشورة', 'draft', 'Empty-state title when no workflow configs exist, /admin/workflows'),
  ('admin.wf.error.title', 'Couldn’t load workflow settings. Nothing was changed. Try again.', 'تعذّر تحميل إعدادات سير العمل. لم يتغيّر أي شيء. حاول مرة أخرى.', 'draft', 'Critical error banner on load failure, /admin/workflows'),
  ('admin.wf.title', 'Workflow Settings', 'إعدادات سير العمل', 'draft', 'Page title, /admin/workflows'),
  ('cmte.off', 'The committee decision record is not enabled here. PKI/EBDA verification is held.', 'سجل قرار اللجنة غير مُفعَّل هنا. التحقق عبر البنية التحتية للمفتاح العام/إبدأ موقوف.', 'draft', 'Committee page — NotYetBoundary consequence text when FEATURE_DECISION_DOSSIER is off'),
  ('f360.cr.noAggregate', 'All-licenses facts only. No CR-level risk score or compliance rate is calculated.', 'بيانات جميع التراخيص فقط. لا يُحتسب معدل مخاطر أو نسبة امتثال على مستوى السجل التجاري.', 'draft', 'Factory 360 CR page, portfolio section caption'),
  ('f360.cr.portfolio', 'All licenses', 'جميع التراخيص', 'draft', 'Factory 360 CR page, all-licenses portfolio section heading'),
  ('f360.enforcement.heading', 'Penalty history', 'سجل العقوبات', 'draft', 'Factory 360 CR page, penalty history section heading'),
  ('f360.err.neutral', 'The Factory list is temporarily unavailable. Nothing was changed.', 'قائمة المصانع غير متاحة مؤقتًا. لم يتم تغيير أي شيء.', 'draft', 'Factory 360 degraded-source error body (web + field)'),
  ('f360.list.dossier', 'View factory', 'عرض ملف المصنع', 'draft', 'Factory list table row action link (web + field variants)'),
  ('f360.notFound.desc', 'Factory registration not found or not available to you.', 'تسجيل المصنع غير موجود أو غير متاح لك.', 'draft', 'Factory 360 not-found empty state title (web + field, CR variant)'),
  ('f360.notFound.title', 'Factory 360 profile unavailable', 'ملف المصنع الشامل غير متاح', 'draft', 'Factory 360 not-found screen title (web + field)'),
  ('f360.permission.body', 'You do not have access to this factory profile.', 'ليس لديك صلاحية الوصول إلى ملف هذا المصنع.', 'draft', 'Factory 360 access-denied empty state body (web + field)'),
  ('field.ws.ev.deleted', 'Evidence removed from the checklist — soft-deleted with reason, audit event recorded (M04-164)', 'تمت إزالة الدليل من قائمة التحقق — حذف مؤقت مع سبب، وتم تسجيل حدث تدقيق (M04-164)', 'draft', 'Field inspection workspace, evidence-deleted confirmation message'),
  ('field.ws.panel.pkg', 'Checklist version used for the inspection (locked)', 'نسخة قائمة التحقق المستخدمة في التفتيش (مقفلة)', 'draft', 'Field inspection workspace, factory info panel label'),
  ('field.ws.returnedNote', 'Only these sections are editable; resubmission creates the next final submitted version (STM-COR-001/002).', 'هذه الأقسام فقط قابلة للتعديل؛ إعادة الإرسال تُنشئ النسخة النهائية المُقدَّمة التالية (STM-COR-001/002).', 'draft', 'Field inspection workspace, returned-for-correction note'),
  ('field.ws.sig.hint', 'Sign in the box below. The signature image, name and timestamp are stored inside the final submitted version (DEC-009).', 'وقّع داخل المربع أدناه. تُحفظ صورة التوقيع والاسم والطابع الزمني ضمن النسخة النهائية المُقدَّمة (DEC-009).', 'draft', 'Field inspection workspace, factory representative signature dialog hint'),
  ('field.ws.submitBtn', 'Review & submit — final version', 'المراجعة والإرسال — النسخة النهائية', 'draft', 'Field inspection workspace, submit button label'),
  ('field.ws.submittedTitle', 'Submitted — final submitted version.', 'تم الإرسال — النسخة النهائية المُقدَّمة.', 'draft', 'Field inspection workspace, submitted-state banner title'),
  ('field.ws.submitting', 'Submitting final version v{v} (idempotency-protected)…', 'جارٍ إرسال النسخة النهائية v{v} (محمية من التكرار)…', 'draft', 'Field inspection workspace, submitting-in-progress status text'),
  ('gis.empty.body', 'The factory list is empty — geofences appear here once factories are synced (FND-007).', 'قائمة المصانع فارغة — تظهر الأسيجة الجغرافية هنا بمجرد مزامنة المصانع (FND-007).', 'draft', 'Empty-state body when no factories registered, /admin/gis'),
  ('gis.title', 'Map Settings — geofencing', 'إعدادات الخرائط — التسييج الجغرافي', 'draft', 'Page title, /admin/gis (GIS Studio)'),
  ('l10n.error.load', 'Could not load the translation dictionary. Nothing was changed. Try again.', 'تعذّر تحميل قاموس الترجمة. لم يتغيّر شيء. حاول مرة أخرى.', 'draft', 'Localization admin page — error banner when the ui_strings load fails'),
  ('l10n.title', 'Language & Translations', 'اللغة والترجمات', 'draft', 'Localization admin page title (Shell header)'),
  ('mvp3.integrations.title', 'System Connections', 'اتصالات النظام', 'draft', 'Page title, /admin/integrations (integration trust console)'),
  ('mvp3.operations.title', 'System operations and resilience', 'عمليات المنظومة والصمود', 'draft', 'Operations admin page title (Shell header)'),
  ('ops.err.partial', 'Some information could not be loaded.', 'تعذّر تحميل بعض المعلومات.', 'draft', 'Operations Center — partial load-error banner'),
  ('ops.export.sla', 'Deadline alerts', 'تنبيهات المواعيد النهائية', 'draft', 'Operations Center — CSV export dataset label'),
  ('ops.live.th.operational', 'Visit status', 'حالة الزيارة', 'draft', 'Operations Center — live monitoring table column header'),
  ('ops.map.heading', 'Live inspection map', 'خريطة التفتيش المباشرة', 'draft', 'Operations Center — live map section heading'),
  ('ops.map.selectHint', 'Click a pin to open the visit or factory profile.', 'انقر على دبوس لفتح الزيارة أو ملف المصنع.', 'draft', 'Operations Center — live map selection hint'),
  ('ops.override.heading', 'Location exception requests', 'طلبات استثناء الموقع', 'draft', 'Operations Center — override queue section heading'),
  ('ops.sla.empty.title', 'No deadline alerts in scope', 'لا توجد تنبيهات مواعيد نهائية ضمن النطاق', 'draft', 'Operations Center — deadline alerts empty state title'),
  ('ops.sla.heading', 'Deadline alerts', 'تنبيهات المواعيد النهائية', 'draft', 'Operations Center — deadline alerts (SLA watch) section heading'),
  ('ops.sla.th.sla', 'Deadline status', 'حالة الموعد النهائي', 'draft', 'Operations Center — deadline alerts table column header'),
  ('report.hist.immutable', 'final', 'نهائية', 'draft', 'Official inspection report — submission versions history table tag'),
  ('report.integrityBlocked.body', 'This inspection is recorded as approved but has no final submitted version on file. The approval is not valid and must not be relied on as an official decision until a final submitted version exists (DEF-WF-006).', 'هذا التفتيش مسجَّل كمعتمَد لكن لا توجد نسخة نهائية مُقدَّمة له في السجل. هذا الاعتماد غير صالح ويجب عدم الاعتماد عليه كقرار رسمي إلى أن توجد نسخة نهائية مُقدَّمة (DEF-WF-006).', 'draft', 'Official inspection report — data-integrity warning banner'),
  ('report.integrityBlocked.status', 'approval invalid — no final submitted version', 'الاعتماد غير صالح — لا توجد نسخة نهائية مُقدَّمة', 'draft', 'Official inspection report — invalid-approval status label'),
  ('report.items.heading', 'Checklist responses — final v{n}', 'إجابات قائمة التفتيش — النسخة النهائية {n}', 'draft', 'Official inspection report — checklist responses section heading'),
  ('report.notSubmitted.title', 'No final submitted version yet.', 'لا توجد نسخة نهائية مُقدَّمة حتى الآن.', 'draft', 'Official inspection report — not-submitted warning banner'),
  ('review.cmp.heading', 'Version comparison — Tamper-evident Scope Rail', 'مقارنة النسخ — شريط النطاق الكاشف للتلاعب', 'draft', 'Review workspace — version comparison panel heading'),
  ('review.cmp.tamperBody', 'An answer changed outside the sections the reviewer returned. Read every flagged row before deciding.', 'تغيّرت إجابة خارج الأقسام التي أعادها المراجع. اقرأ كل صف مُعلَّم قبل اتخاذ القرار.', 'draft', 'Review workspace — out-of-scope change alert body'),
  ('review.list.colFingerprint', 'Review readiness', 'جاهزية المراجعة', 'draft', 'Review queue table — readiness column header'),
  ('review.list.colOpen', 'Review', 'المراجعة', 'draft', 'Review queue table — open-review column header'),
  ('review.list.context', 'Read-only queue', 'قائمة للاطّلاع فقط', 'draft', 'Review queue — header context lozenge'),
  ('review.list.empty', 'No inspections awaiting review', 'لا توجد عمليات تفتيش بانتظار المراجعة', 'draft', 'Review queue — empty state title'),
  ('review.list.fp.readyBlockTag', 'derived', 'مُستنتج', 'draft', 'Review queue — readiness fingerprint, derived-value tag'),
  ('review.list.fp.sla', 'Deadline', 'الموعد النهائي', 'draft', 'Review queue — readiness fingerprint, deadline row label'),
  ('review.list.fp.slaUnavailable', 'Deadline unavailable — required config/timestamp missing', 'الموعد النهائي غير متاح — إعداد أو طابع زمني مطلوب غير موجود', 'draft', 'Review queue — readiness fingerprint, deadline unavailable state'),
  ('review.list.fpTitle', 'Review readiness', 'جاهزية المراجعة', 'draft', 'Review queue — readiness fingerprint panel heading'),
  ('review.list.open', 'Open review', 'فتح المراجعة', 'draft', 'Review queue table — open review row action'),
  ('review.list.scanTitle', 'Review overview', 'نظرة عامة على المراجعة', 'draft', 'Review queue — read-only overview banner title'),
  ('review.list.searchAria', 'Search the review queue', 'البحث في قائمة انتظار المراجعة', 'draft', 'Review queue — search input accessible label'),
  ('review.list.title', 'Inspection review queue', 'قائمة انتظار مراجعة التفتيش', 'draft', 'Review queue — page title'),
  ('review.list.unauthBody', 'This queue requires the Level 2 Reviewer role and matching scope. Navigation visibility is not authorization.', 'تتطلب هذه القائمة دور مراجع المستوى الثاني والنطاق المطابق له. ظهور الرابط في التنقل لا يعني وجود صلاحية.', 'draft', 'Review queue — unauthorized-access message'),
  ('review.ws.approveWarnTitle', 'Irreversible:', 'لا رجعة فيه:', 'draft', 'Review workspace — decision panel, approve warning label'),
  ('review.ws.audited', 'Audited: reviewer, reason, sections, prior/new status, version, timestamp.', 'مُدقَّق: المراجِع، السبب، الأقسام، الحالة السابقة/الجديدة، النسخة، الطابع الزمني.', 'draft', 'Review workspace — decision panel, audit note'),
  ('review.ws.fvNote', 'Observations never modify the Senaei source record; checks are audit-logged with before/after values.', 'لا تُعدِّل الملاحظات سجل سنائي المصدر أبدًا؛ وتُسجَّل عمليات التحقق في سجل التدقيق بقيم ما قبل/بعد.', 'draft', 'Review workspace — factory-verification section note'),
  ('review.ws.loadingDesc', 'Fetching checklist, evidence, factory verification and version comparison data.', 'يجري جلب بيانات قائمة التفتيش والأدلة والتحقق من المصنع ومقارنة النسخ.', 'draft', 'Review workspace — loading state description'),
  ('review.ws.readOnlyTitle', 'Read-only submitted version.', 'نسخة مُقدَّمة للاطّلاع فقط.', 'draft', 'Review workspace — read-only submitted-version banner'),
  ('review.ws.rejectWarnTitle', 'Final:', 'نهائي:', 'draft', 'Review workspace — decision panel, reject warning label'),
  ('review.ws.returnScopeHint', 'Only selected sections unlock; the rest stays locked.', 'تُفتح الأقسام المحدَّدة فقط؛ وتبقى بقية الأقسام مقفلة.', 'draft', 'Review workspace — decision panel, return-scope hint'),
  ('review.ws.timelineHeading', 'Timeline — audit trail', 'الجدول الزمني — سجل التدقيق', 'draft', 'Review workspace — audit timeline section heading'),
  ('review.ws.timelineNote', 'Append-only rows from audit_events; the database rejects edits and deletes.', 'صفوف تُضاف فقط من audit_events؛ وترفض قاعدة البيانات أي تعديل أو حذف لها.', 'draft', 'Review workspace — audit timeline note'),
  ('review.ws.unauthBody', 'This workspace requires the Level 2 Reviewer role and matching scope. Navigation visibility is not authorization.', 'تتطلب مساحة العمل هذه دور مراجع المستوى الثاني والنطاق المطابق له. ظهور الرابط في التنقل لا يعني وجود صلاحية.', 'draft', 'Review workspace — unauthorized-access message'),
  ('shell.nav.audit', 'Activity Log', 'سجل النشاط', 'draft', 'Admin landing page — link-only nav list item, mirrors admin.overview.r2.family.audit (renamed from ''Audit Log'')'),
  ('shell.nav.gis', 'Map Settings', 'إعدادات الخريطة', 'draft', 'Admin landing page — link-only nav list item (renamed from ''GIS Engine'')'),
  ('shell.nav.localization', 'Language & Translations', 'اللغة والترجمات', 'draft', 'Admin landing page — link-only nav list item, mirrors l10n.title (renamed from ''Localization'')'),
  ('shell.nav.risk', 'Risk Settings', 'إعدادات المخاطر', 'draft', 'Admin landing page — link-only nav list item (renamed from ''Risk Engine'')'),
  ('shell.nav.workflows', 'Workflow Settings', 'إعدادات سير العمل', 'draft', 'Admin landing page — link-only nav list item (renamed from ''Workflow Engine'')'),
  ('visit.detail.auditHeading', 'Planning history — cannot be edited, only added to (ENG-12, latest 30)', 'سجل التخطيط — لا يمكن تعديله، تُضاف إليه أحداث جديدة فقط (ENG-12، آخر 30 حدثًا)', 'draft', 'Visit detail — planning history / audit section heading'),
  ('visit.detail.immutable', 'final', 'نهائية', 'draft', 'Visit detail — submission version tag / dual-state ribbon inspection event'),
  ('visit.detail.journeyHeading', 'Journey & location events — cannot be edited (EV-005)', 'أحداث الرحلة والموقع — لا يمكن تعديلها (EV-005)', 'draft', 'Visit detail — journey & location events section heading'),
  ('visit.detail.notFoundDesc', 'IDs never change or get reused (FLD-VIS-001).', 'المعرّفات لا تتغيّر ولا يُعاد استخدامها أبدًا (FLD-VIS-001).', 'draft', 'Visit detail — visit-not-found empty state description'),
  ('visit.list.colOperational', 'Visit status', 'حالة الزيارة', 'draft', 'Visits list table column header'),
  ('visit.ribbon.operational', 'Visit status', 'حالة الزيارة', 'draft', 'Visit detail — Dual-State Ribbon, operational track domain label'),
  ('visit.ribbon.src.insp', 'inspection engine — submissions are final', 'محرّك التفتيش — النسخ المُقدَّمة نهائية', 'draft', 'Visit detail — Dual-State Ribbon, inspection track source label')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';
