-- CD-006..CD-011 frontend completion strings.
-- Draft translations are intentionally reviewable and never overwrite rows that
-- a human localization reviewer has already promoted beyond draft status.

with strings(key, en, ar) as (values
  ('admin.permissionsUnavailable.title', 'Permissions unavailable', 'الصلاحيات غير متاحة'),
  ('admin.permissionsUnavailable.body', 'Your configuration permissions could not be verified. Writes are disabled; retry the page.', 'تعذّر التحقق من صلاحيات التهيئة. تم تعطيل الكتابة؛ أعد تحميل الصفحة.'),
  ('admin.unauthorized.title', 'Authorized configuration role required', 'يلزم دور تهيئة مصرح له'),
  ('admin.unauthorized.heading', 'This control-plane module is outside your role', 'وحدة التحكم هذه خارج نطاق دورك'),
  ('admin.unauthorized.body', 'No configuration data has been loaded. Return to your assigned workspace or ask an administrator for the required role.', 'لم تُحمّل بيانات التهيئة. ارجع إلى مساحة عملك أو اطلب من المسؤول الدور المطلوب.'),
  ('admin.unauthorized.return', 'Return to my workspace', 'العودة إلى مساحة عملي'),
  ('admin.reg.publish', 'Approve and publish', 'اعتماد ونشر'),
  ('admin.reg.r1.detail.publish.direct', 'Publication runs mapped-clause validation and database maker-checker controls before changing status.', 'يتحقق النشر من ربط البنود ومن ضوابط المُعدّ والمراجع في قاعدة البيانات قبل تغيير الحالة.'),
  ('admin.reg.r1.detail.validation.title', 'Publish validation', 'التحقق قبل النشر'),
  ('admin.reg.r1.detail.validation.unmapped', '{count} clause(s) still need an inspection-item mapping.', 'ما زال {count} من البنود بحاجة إلى ربط بعنصر فحص.'),
  ('admin.reg.attachments.truth', 'Files are uploaded to governed private storage, checksummed, and retrieved through short-lived signed links.', 'تُرفع الملفات إلى تخزين خاص محكوم، وتُحسب بصمتها، وتُسترجع عبر روابط موقعة قصيرة الأجل.'),
  ('admin.reg.r1.readonly.body', 'You can view configuration; creating, adding clauses, and publishing require a Compliance or Form Admin role and are enforced by row-level security. The route guard and database permissions are independent controls.', 'يمكنك عرض التهيئة؛ ويتطلب الإنشاء وإضافة البنود والنشر دور مسؤول امتثال أو نماذج وتفرضه سياسات الصفوف. حماية المسار وصلاحيات قاعدة البيانات ضابطان مستقلان.'),
  ('admin.items.r2.gov.body', 'Item changes are server-authorized, row-level secured, and recorded in scoped audit history.', 'تُعتمد تغييرات العناصر من الخادم، وتحميها سياسات الصفوف، وتُسجل في سجل تدقيق محدد.'),
  ('admin.items.r2.preview.conditional', 'Visible when {condition}', 'يظهر عندما {condition}'),
  ('admin.items.r2.audit.body', 'Open Audit on one item to inspect its object-scoped configuration history; broad audit-table access is not granted.', 'افتح التدقيق لعنصر واحد لعرض سجل تهيئته المحدد؛ لا يُمنح وصول واسع إلى جدول التدقيق.'),
  ('admin.items.r2.audit.empty', 'No scoped audit events returned — verified zero.', 'لم تُرجع أحداث تدقيق محددة — صفر مؤكد.'),
  ('admin.items.r2.audit.heading', 'Scoped item audit', 'تدقيق العنصر المحدد'),
  ('admin.items.r2.audit.notFound', 'The selected item is no longer in the readable catalogue.', 'العنصر المحدد لم يعد موجودًا في الدليل المقروء.'),
  ('admin.items.r2.audit.open', 'Audit', 'التدقيق'),
  ('admin.items.r2.audit.select', 'No item selected.', 'لم يُحدد عنصر.'),
  ('admin.items.r2.audit.unavailable', 'Audit unavailable — reload to retry; history is not reported as empty.', 'التدقيق غير متاح — أعد التحميل للمحاولة؛ لا يُعرض السجل كفارغ.'),
  ('admin.items.r2.empty.body', 'Items belong to regulation clauses and are reused across packages (M09-002). Add the first item above.', 'تنتمي العناصر إلى بنود اللوائح ويُعاد استخدامها عبر الحزم (M09-002). أضف أول عنصر أعلاه.'),
  ('admin.items.r2.empty.title', 'No inspection items configured', 'لا توجد عناصر فحص مهيأة'),
  ('admin.items.r2.form.evidenceCommentNc', 'Comment mandatory on non-compliant', 'التعليق إلزامي عند عدم الامتثال'),
  ('admin.items.r2.form.evidenceDocumentNc', 'Document mandatory on non-compliant', 'المستند إلزامي عند عدم الامتثال'),
  ('admin.items.r2.form.evidenceVideoNc', 'Video mandatory on non-compliant', 'الفيديو إلزامي عند عدم الامتثال'),
  ('admin.items.r2.form.deactivationReason', 'Deactivation reason', 'سبب إلغاء التفعيل'),
  ('admin.items.r2.toggle.reasonNote', 'History is preserved; the required reason and item-row change are recorded in audit history.', 'يُحفظ السجل؛ ويُسجل السبب المطلوب وتغيير العنصر في سجل التدقيق.'),
  ('admin.items.r2.form.mandatoryWhenVisible', 'Mandatory when visible', 'إلزامي عند الظهور'),
  ('admin.items.r2.form.requirementConditional', 'Conditional', 'مشروط'),
  ('admin.items.r2.form.requirementMode', 'Requirement mode', 'وضع الإلزام'),
  ('admin.items.r2.form.requirementOptional', 'Optional', 'اختياري'),
  ('admin.items.r2.form.requirementRequired', 'Required', 'إلزامي'),
  ('admin.items.r2.form.scoringDisabled', 'Scoring disabled', 'التقييم معطل'),
  ('admin.items.r2.form.scoringEnabled', 'Scoring enabled', 'التقييم مفعل'),
  ('admin.items.r2.form.visibleWhen', 'Visible when', 'يظهر عندما'),
  ('admin.items.r2.form.visibleWhenHint', 'Use the governed key=value grammar.', 'استخدم الصيغة المعتمدة key=value.'),
  ('admin.items.r2.preview.evidenceRequired', '{type} required when non-compliant (min {min})', '{type} مطلوب عند عدم الامتثال (الحد الأدنى {min})'),
  ('admin.items.r2.preview.mandatoryVisible', 'mandatory when visible', 'إلزامي عند الظهور'),
  ('admin.items.r2.preview.optional', 'Optional', 'اختياري'),
  ('admin.items.r2.preview.required', 'Required', 'إلزامي'),
  ('admin.items.r2.preview.scoringOff', 'scoring disabled; all responses excluded', 'التقييم معطل؛ جميع الإجابات مستبعدة'),
  ('admin.items.r2.readonly.action', 'Read only', 'للقراءة فقط'),
  ('admin.items.r2.readonly.body', 'Your role can inspect item semantics, usage and runtime previews. Creating or changing active state requires Compliance or Form Admin and is enforced by the server guard and RLS.', 'يمكن لدورك عرض دلالات العناصر واستخدامها ومعاينتها. يتطلب الإنشاء أو تغيير الحالة مسؤول امتثال أو نماذج وتفرضه حماية الخادم وأمن الصفوف.'),
  ('admin.items.r2.readonly.title', 'Read-only catalogue', 'دليل للقراءة فقط'),
  ('admin.items.r2.sem.onNc', 'on NC', 'عند عدم الامتثال'),
  ('admin.items.r2.sem.scoringOff', 'scoring off', 'التقييم متوقف'),
  ('admin.items.r2.usage.counts', '{packages} package(s) · {versions} version(s)', '{packages} حزمة · {versions} إصدار'),
  ('admin.items.r2.usage.writerOnly', 'Available to configuration writers', 'متاح لمحرري التهيئة'),

  ('admin.pkg.blockers.body', 'Effective dates, scheduled activation, a stored supersede lifecycle, package footprint/fingerprint counts, package-level item reordering or policy authoring, simulation, circular-rule detection, and an Admin-family route guard remain unavailable. No value or working control is fabricated for them.', 'تظل تواريخ السريان والتفعيل المجدول ودورة الاستبدال المخزنة وبصمة الحزمة وإعادة ترتيب العناصر أو تأليف سياساتها والمحاكاة واكتشاف القواعد الدائرية وحارس مسار الإدارة غير متاحة. لا تُختلق لها قيم أو عناصر تحكم.'),
  ('admin.pkg.blockers.title', 'Boundaries kept visible', 'حدود ظاهرة بوضوح'),
  ('admin.pkg.col.definition', 'Definition', 'التعريف'),
  ('admin.pkg.col.published', 'Published', 'تاريخ النشر'),
  ('admin.pkg.col.state', 'State', 'الحالة'),
  ('admin.pkg.col.version', 'Version', 'الإصدار'),
  ('admin.pkg.derivedSuperseded', 'older than current publish (derived)', 'أقدم من الإصدار المنشور الحالي (مشتقة)'),
  ('admin.pkg.editor.blankSection', 'Section {key} needs a title.', 'يحتاج القسم {key} إلى عنوان.'),
  ('admin.pkg.editor.blocked', 'Not enabled', 'غير مفعل'),
  ('admin.pkg.editor.blockedOwner', 'requires a package-definition backend contract', 'يتطلب عقد واجهة خلفية لتعريف الحزمة'),
  ('admin.pkg.editor.canvas', '2 · Field canvas', '2 · مساحة العمل الميدانية'),
  ('admin.pkg.editor.duplicateItem', 'Item {code} appears in more than one section.', 'يظهر العنصر {code} في أكثر من قسم.'),
  ('admin.pkg.editor.emptyBody', 'Add the first section to begin this draft.', 'أضف أول قسم لبدء هذه المسودة.'),
  ('admin.pkg.editor.emptyTitle', 'No sections yet', 'لا توجد أقسام بعد'),
  ('admin.pkg.editor.itemCount', '{n} item(s)', '{n} عنصر'),
  ('admin.pkg.editor.noChanges', 'No unsaved changes', 'لا تغييرات غير محفوظة'),
  ('admin.pkg.editor.preview', '3 · Read-only preview', '3 · معاينة للقراءة فقط'),
  ('admin.pkg.editor.structure', '1 · Structure', '1 · البنية'),
  ('admin.pkg.editor.targetConditions', 'Author conditions in this package', 'تأليف الشروط في هذه الحزمة'),
  ('admin.pkg.editor.targetForms', 'Author action forms', 'تأليف نماذج الإجراءات'),
  ('admin.pkg.editor.targetPolicies', 'Edit scoring or evidence policy here', 'تحرير سياسة التقييم أو الأدلة هنا'),
  ('admin.pkg.editor.targetReorder', 'Reorder items', 'إعادة ترتيب العناصر'),
  ('admin.pkg.editor.targetSimulation', 'Run simulation / circular-rule detection', 'تشغيل المحاكاة أو اكتشاف القواعد الدائرية'),
  ('admin.pkg.editor.targetsTitle', 'Governed contract targets', 'أهداف العقد المحكومة'),
  ('admin.pkg.editor.unsaved', 'Unsaved changes', 'تغييرات غير محفوظة'),
  ('admin.pkg.editor.validationClear', 'The editable structure has no duplicate items or blank section titles. Full dependency validation runs again at publish.', 'لا تحتوي البنية القابلة للتحرير على عناصر مكررة أو عناوين أقسام فارغة. يُعاد التحقق الكامل من التبعيات عند النشر.'),
  ('admin.pkg.editor.validationTitle', 'Draft checks', 'فحوصات المسودة'),
  ('admin.pkg.empty.body', 'The package read succeeded and returned no rows. Package creation is not exposed by this route, so no unsupported create control is shown.', 'نجحت قراءة الحزم ولم تُرجع صفوفًا. لا يتيح هذا المسار إنشاء الحزم، لذلك لا يظهر عنصر إنشاء غير مدعوم.'),
  ('admin.pkg.empty.title', 'No packages configured', 'لا توجد حزم مهيأة'),
  ('admin.pkg.error.body', 'The requested data is temporarily unavailable. Nothing was changed. Try again.', 'البيانات المطلوبة غير متاحة مؤقتًا. لم يتغير شيء. حاول مرة أخرى.'),
  ('admin.pkg.error.title', 'Couldn''t load the package library.', 'تعذّر تحميل مكتبة الحزم.'),
  ('admin.pkg.immutable.body', 'The database rejects definition and label edits. Create a new draft to change this package while existing inspections stay pinned to their downloaded version.', 'ترفض قاعدة البيانات تعديل التعريف والتسمية. أنشئ مسودة جديدة لتغيير الحزمة مع بقاء عمليات الفحص الحالية مرتبطة بإصدارها المنزّل.'),
  ('admin.pkg.items', 'item(s)', 'عنصر'),
  ('admin.pkg.itemsUnavailable.body', 'Package versions and impact remain visible, but editing and field preview are paused because their item dependency could not be read. This is not an empty catalogue.', 'تظل إصدارات الحزم وأثرها ظاهرة، لكن التحرير والمعاينة الميدانية متوقفان لتعذر قراءة العناصر التابعة. هذا ليس دليلاً فارغًا.'),
  ('admin.pkg.itemsUnavailable.title', 'Item catalogue unavailable.', 'دليل العناصر غير متاح.'),
  ('admin.pkg.newDraft.placeholder', 'Example: v2026.08', 'مثال: v2026.08'),
  ('admin.pkg.noVersions', 'No versions yet', 'لا توجد إصدارات بعد'),
  ('admin.pkg.overview.body', 'Drafts are editable. Publishing runs dependency validation and maker-checker approval; published and locked definitions remain immutable.', 'المسودات قابلة للتحرير. يجري النشر التحقق من التبعيات واعتماد المنشئ والمراجع؛ وتبقى التعريفات المنشورة والمقفلة غير قابلة للتغيير.'),
  ('admin.pkg.overview.title', 'Version-governed inspection packages', 'حزم فحص محكومة بالإصدارات'),
  ('admin.pkg.preview.mandatoryWhenVisible', 'Mandatory when visible', 'إلزامي عند الظهور'),
  ('admin.pkg.preview.optional', 'Optional', 'اختياري'),
  ('admin.pkg.preview.required', 'Required', 'إلزامي'),
  ('admin.pkg.preview.scoringDisabled', 'Scoring disabled', 'التقييم معطل'),
  ('admin.pkg.publish.heading', 'Publish gate', 'بوابة النشر'),
  ('admin.pkg.publish.hint', 'Publish rechecks item, evidence, condition, violation, penalty and action-form dependencies. The approver must differ from the creator (RBAC-002).', 'يعيد النشر فحص تبعيات العناصر والأدلة والشروط والمخالفات والعقوبات ونماذج الإجراءات. يجب أن يختلف المعتمد عن المنشئ (RBAC-002).'),
  ('admin.pkg.publish.published', 'Version published. It is now immutable.', 'نُشر الإصدار وأصبح غير قابل للتغيير.'),
  ('admin.pkg.readAt', 'Read from source at', 'قُرئت من المصدر في'),
  ('admin.pkg.reader', 'Read-only access', 'وصول للقراءة فقط'),
  ('admin.pkg.readonly.body', 'You can inspect versions, previews and publish impact. Creating, saving and publishing require compliance_admin or form_admin; navigation access does not grant write permission.', 'يمكنك عرض الإصدارات والمعاينات وأثر النشر. يتطلب الإنشاء والحفظ والنشر مسؤول امتثال أو نماذج؛ ولا يمنح الوصول عبر التنقل صلاحية الكتابة.'),
  ('admin.pkg.readonly.title', 'Read-only package access', 'وصول الحزم للقراءة فقط'),
  ('admin.pkg.readonly.unknown', 'Your write permissions could not be verified, so all mutation controls are hidden. Reload to retry; RLS remains authoritative.', 'تعذر التحقق من صلاحيات الكتابة، لذا أُخفيت جميع عناصر التعديل. أعد التحميل للمحاولة؛ ويظل أمن الصفوف هو المرجع.'),
  ('admin.pkg.refresh', 'Refresh to reconcile', 'تحديث للمطابقة'),
  ('admin.pkg.retry', 'Reload to try again', 'أعد التحميل للمحاولة'),
  ('admin.pkg.scopeNone', 'No scope recorded', 'لا يوجد نطاق مسجل'),
  ('admin.pkg.sections', 'section(s)', 'قسم'),
  ('admin.pkg.stale', 'Data may have changed since this source read; no freshness threshold is defined.', 'قد تكون البيانات تغيرت منذ قراءة المصدر؛ لا توجد عتبة حداثة محددة.'),
  ('admin.pkg.versions', 'versions', 'إصدارات'),
  ('admin.pkg.writer', 'Configuration writer', 'محرر التهيئة'),

  ('admin.reg.attachment.add', 'Add attachment metadata', 'إضافة بيانات المرفق'),
  ('admin.reg.attachment.added', 'Attachment added', 'أُضيف المرفق'),
  ('admin.reg.attachment.adding', 'Adding…', 'جارٍ الإضافة…'),
  ('admin.reg.attachment.hash', 'SHA-256 (optional)', 'SHA-256 (اختياري)'),
  ('admin.reg.attachment.name', 'File name', 'اسم الملف'),
  ('admin.reg.attachment.path', 'Governed storage path', 'مسار التخزين المحكوم'),
  ('admin.reg.attachment.type', 'Media type', 'نوع الوسائط'),
  ('admin.reg.attachments.empty', 'No attachment metadata recorded — verified zero.', 'لا توجد بيانات مرفقات مسجلة — صفر مؤكد.'),
  ('admin.reg.attachments.heading', 'Source attachments', 'مرفقات المصدر'),
  ('admin.reg.attachments.truth', 'This records governed storage metadata; it does not upload or fabricate a file.', 'يسجل هذا بيانات التخزين المحكومة؛ ولا يرفع ملفًا أو يختلقه.'),
  ('admin.reg.audit.empty', 'No scoped audit events returned — verified zero.', 'لم تُرجع أحداث تدقيق محددة — صفر مؤكد.'),
  ('admin.reg.audit.error', 'The audit timeline is unavailable. Reload to retry; no empty-history claim is made.', 'الخط الزمني للتدقيق غير متاح. أعد التحميل للمحاولة؛ لا يُدعى أن السجل فارغ.'),
  ('admin.reg.audit.heading', 'Configuration audit timeline', 'الخط الزمني لتدقيق التهيئة'),
  ('admin.reg.audit.readonly', 'The scoped author timeline is available to configuration writers; this read-only persona is not granted that RPC.', 'يتاح سجل المؤلف المحدد لمحرري التهيئة؛ ولا تُمنح هذه الشخصية المقروءة استدعاء RPC.'),
  ('admin.reg.deactivate', 'Deactivate regulation', 'إلغاء تفعيل اللائحة'),
  ('admin.reg.deactivated', 'Regulation deactivated', 'أُلغي تفعيل اللائحة'),
  ('admin.reg.deactivated.readonly', 'Deactivated — read-only', 'غير مفعلة — للقراءة فقط'),
  ('admin.reg.deactivating', 'Deactivating…', 'جارٍ إلغاء التفعيل…'),
  ('admin.reg.edit.save', 'Save draft', 'حفظ المسودة'),
  ('admin.reg.edit.saved', 'Draft saved', 'حُفظت المسودة'),
  ('admin.reg.edit.saving', 'Saving…', 'جارٍ الحفظ…'),
  ('admin.reg.form.effectiveFrom', 'Effective from', 'سارية من'),
  ('admin.reg.r1.detail.validation.noClauses', 'Blocked: add at least one clause.', 'محظور: أضف بندًا واحدًا على الأقل.'),
  ('admin.reg.r1.detail.validation.ready', 'Ready: every clause has at least one mapped inspection item.', 'جاهز: لكل بند عنصر فحص مرتبط واحد على الأقل.'),
  ('admin.reg.r1.filter.deactivated', 'Deactivated {n}', 'غير مفعلة {n}'),
  ('admin.reg.r1.status.deactivated', 'Deactivated', 'غير مفعلة'),
  ('admin.reg.status.deactivated', 'Deactivated', 'غير مفعلة'),

  ('admin.viol.audit.actor', 'actor', 'المنفذ'),
  ('admin.viol.audit.code', 'Violation audit events', 'أحداث تدقيق المخالفة'),
  ('admin.viol.audit.empty', 'No audit events returned for this object.', 'لم تُرجع أحداث تدقيق لهذا الكائن.'),
  ('admin.viol.audit.mapping', 'Mapping audit events', 'أحداث تدقيق الربط'),
  ('admin.viol.audit.unavailable', 'Audit history unavailable — no zero-event claim was made.', 'سجل التدقيق غير متاح — لم يُدّع وجود صفر من الأحداث.'),
  ('admin.viol.audit.writerOnly', 'Audit history is available to configuration writers.', 'سجل التدقيق متاح لمحرري التهيئة.'),
  ('admin.viol.form.activeTo', 'Active to', 'فعّالة حتى'),
  ('admin.viol.form.deactivate', 'Deactivate', 'إلغاء التفعيل'),
  ('admin.viol.form.deactivated', 'deactivated', 'غير مفعلة'),
  ('admin.viol.form.deactivating', 'Deactivating…', 'جارٍ إلغاء التفعيل…'),
  ('admin.viol.map.approve', 'Approve and publish mapping', 'اعتماد ربط العقوبة ونشره'),
  ('admin.viol.map.publishing', 'Publishing mapping…', 'جارٍ نشر الربط…'),
  ('admin.viol.map.published', 'mapping published', 'تم نشر الربط'),
  ('admin.viol.lens.draft', 'draft awaiting a distinct approver', 'مسودة تنتظر معتمدًا مختلفًا'),
  ('admin.viol.err.futureActiveTo', 'Deactivation must take effect today or earlier; future dates are scheduled expiry, not deactivation.', 'يجب أن يسري إلغاء التفعيل اليوم أو قبله؛ التاريخ المستقبلي انتهاء مجدول وليس إلغاء تفعيل.'),
  ('admin.viol.map.err.effectiveFrom', 'A valid effective-from date is required.', 'يلزم تاريخ سريان صالح.'),
  ('admin.viol.map.err.missing', 'Missing penalty mapping draft.', 'مسودة ربط العقوبة مفقودة.'),
  ('admin.viol.map.err.makerChecker', 'A different configuration writer must approve this draft.', 'يجب أن يعتمد هذه المسودة محرر تهيئة مختلف.'),
  ('admin.viol.map.err.effectiveOrder', 'The successor effective date must follow the active mapping.', 'يجب أن يأتي تاريخ سريان الربط اللاحق بعد الربط النشط.'),
  ('admin.viol.clausesUnavailable.title', 'Regulation clauses are unavailable', 'بنود اللوائح غير متاحة'),
  ('admin.viol.clausesUnavailable.body', 'Violation creation is disabled because its required legal-anchor source could not be read. Retry before authoring.', 'تم تعطيل إنشاء المخالفة لتعذّر قراءة مرجعها النظامي المطلوب. أعد المحاولة قبل الإنشاء.'),
  ('admin.viol.clausesEmpty', 'No regulation clauses exist. Create and publish the legal source before creating a violation code.', 'لا توجد بنود لوائح. أنشئ المرجع النظامي وانشره قبل إنشاء رمز مخالفة.'),
  ('admin.pkg.loading', 'Loading package versions and their governed dependencies…', 'جارٍ تحميل إصدارات الحزم واعتمادياتها المحكومة…'),
  ('admin.pkg.newDraft.effectiveFrom', 'Effective from', 'يسري من'),
  ('admin.pkg.blockers.body', 'Package footprint/fingerprint counts, visual simulation, and richer package-level policy authoring remain unavailable. Effective windows, supersede lineage, item ordering, condition validation and circular-rule rejection are enforced. No value or working control is fabricated.', 'لا تزال أعداد بصمة الحزمة والمحاكاة المرئية وتأليف سياسات الحزمة المتقدم غير متاحة. تُفرض فترات السريان وتسلسل الاستبدال وترتيب العناصر والتحقق من الشروط ورفض الدورات. لا تُختلق قيم أو عناصر تحكم.'),
  ('admin.viol.readonly', 'Read-only view — configuration writes require the compliance-admin or form-admin role (RLS). Route visibility does not grant write authority.', 'عرض للقراءة فقط — تتطلب كتابة التهيئة دور مسؤول الامتثال أو النماذج وتفرضها سياسات الصفوف. ظهور المسار لا يمنح صلاحية الكتابة.'),
  ('admin.viol.loading.aria', 'Loading violation configuration', 'جارٍ تحميل تهيئة المخالفات'),
  ('admin.viol.loading', 'Loading violation catalogue and penalty mappings…', 'جارٍ تحميل دليل المخالفات وربط العقوبات…'),
  ('admin.viol.lens.needsAttention', 'Needs attention', 'تحتاج إلى انتباه'),
  ('admin.viol.lens.pass', 'Pass', 'ناجح'),
  ('admin.viol.lens.proven', 'Proven rule', 'قاعدة مثبتة'),
  ('admin.viol.usage.heading', 'Usage and audit', 'الاستخدام والتدقيق'),
  ('admin.viol.usage.items', 'Item references', 'مراجع العناصر'),
  ('admin.viol.usage.runtime', 'Runtime references', 'مراجع التشغيل'),
  ('admin.viol.usage.unavailable', 'Usage unavailable — no zero-count claim was made.', 'الاستخدام غير متاح — لم يُدّع أن العدد صفر.'),
  ('admin.viol.usage.writerOnly', 'Usage counts are available to configuration writers.', 'أعداد الاستخدام متاحة لمحرري التهيئة.')
)
insert into ui_strings (key, en, ar, status, context)
select key, en, ar, 'draft', 'CD-006..011 frontend completion 2026-07-15'
from strings
on conflict (key) do update set
  en = excluded.en,
  ar = excluded.ar,
  context = excluded.context,
  updated_at = now()
where ui_strings.status = 'draft';
