-- CD-007 / SCR-ADM-020 / /admin/items — Inspection Item Catalogue · Arabic localization seed
-- Arabic values pair the EN source strings authored in the CD-007 R2 code layer
-- (apps/web/src/app/admin/items/{page.tsx,Controls.tsx,loading.tsx}). Seeded as
-- status='draft' (machine/unreviewed) — human localization review is the gate to
-- 'reviewed'. The upsert NEVER overwrites a row a human already reviewed.
-- Not a product-scope change: Arabic values for already-accepted EN UI strings only;
-- no new Arabic scope, policy, threshold, or behaviour is introduced.

insert into ui_strings (key, en, ar, status, context) values
  ('admin.items.r2.title',                    'Inspection Item Catalogue', 'كتالوج بنود التفتيش', 'draft', 'CD-007 SCR-ADM-020'),
  ('admin.items.r2.readAt',                   'catalogue read {time} — a source fact, not a freshness verdict', 'قُرئ الكتالوج {time} — حقيقة مصدر لا حكم على الحداثة', 'draft', 'CD-007 header — {time}'),
  ('admin.items.r2.degraded.clause',          'clause list unavailable', 'قائمة البنود اللائحية غير متاحة', 'draft', 'CD-007 header lozenge'),
  ('admin.items.r2.degraded.body',            'The clause list couldn’t be read. The catalogue below still rendered; only the clause control is unavailable.', 'تعذّرت قراءة قائمة البنود اللائحية. عُرض الكتالوج أدناه؛ عنصر اختيار البند فقط غير متاح.', 'draft', 'CD-007 S08 degraded sr-only'),
  ('admin.items.r2.error.title',              'Couldn’t load the item catalogue.', 'تعذّر تحميل كتالوج البنود.', 'draft', 'CD-007 S08 error'),
  ('admin.items.r2.error.body',               'The requested data is temporarily unavailable. Nothing was changed. Try again.', 'البيانات المطلوبة غير متاحة مؤقتًا. لم يتغيّر شيء. حاول مجددًا.', 'draft', 'CD-007 error body'),
  ('admin.items.r2.error.retry',              'Reload the page to try again.', 'أعد تحميل الصفحة للمحاولة مجددًا.', 'draft', 'CD-007 error retry'),
  ('admin.items.r2.loading',                  'Loading the item catalogue…', 'جارٍ تحميل كتالوج البنود…', 'draft', 'CD-007 S02 loading'),
  ('admin.items.r2.gov.heading',              'How this catalogue is governed', 'كيف يُحكم هذا الكتالوج', 'draft', 'CD-007 governance'),
  ('admin.items.r2.gov.body',                 'Anyone signed in can read the catalogue; creating items and changing active state require compliance_admin or form_admin — RLS is the authority and navigation visibility grants nothing. Deactivation preserves history and stores no reason. inspection_items has no audit trigger, so item changes are not recorded as audit events.', 'يستطيع أي مستخدم مسجَّل قراءة الكتالوج؛ أما إنشاء البنود وتغيير حالة التفعيل فيتطلب دور compliance_admin أو form_admin — سياسات RLS هي المرجع، والظهور في التنقل لا يمنح صلاحية. إلغاء التفعيل يحفظ التاريخ ولا يخزّن سببًا. جدول inspection_items لا يملك مُشغِّل تدقيق، لذا لا تُسجَّل تغييرات البنود كأحداث تدقيق.', 'draft', 'CD-007 governance body'),
  ('admin.items.r2.create.heading',           'Add an inspection item', 'إضافة بند تفتيش', 'draft', 'CD-007 create section'),
  ('admin.items.r2.form.code',                'Code', 'الرمز', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.title',               'Title', 'العنوان', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.titlePlaceholder',    'Inspection item title', 'عنوان بند التفتيش', 'draft', 'CD-007 form placeholder'),
  ('admin.items.r2.form.clause',              'Clause (M09-002)', 'البند اللائحي (M09-002)', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.selectClause',        'Select clause…', 'اختر بندًا…', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.clauseUnavailable',   'Clause list unavailable — try again', 'قائمة البنود غير متاحة — حاول مجددًا', 'draft', 'CD-007 form degraded'),
  ('admin.items.r2.form.weight',              'Weight', 'الوزن', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.responseModel',       'Response model (M09-019)', 'نموذج الاستجابة (M09-019)', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.evidenceRule',        'Evidence rule (M09-005)', 'قاعدة الإثبات (M09-005)', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.evidenceNone',        'No base evidence rule', 'لا توجد قاعدة إثبات أساسية', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.evidencePhotoNc',     'Photo mandatory on non-compliant', 'صورة إلزامية عند عدم الامتثال', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.evidenceSource',      'Configured policy — governed preset, not free text (M09-005/025).', 'سياسة مُهيّأة — إعداد محكوم مسبقًا لا نص حر (M09-005/025).', 'draft', 'CD-007 form evidence source'),
  ('admin.items.r2.form.guidance',            'Guidance (EN)', 'الإرشاد (إنجليزي)', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.guidancePlaceholder', 'What the inspector verifies', 'ما الذي يتحقق منه المفتش', 'draft', 'CD-007 form placeholder'),
  ('admin.items.r2.form.creating',            'Creating…', 'جارٍ الإنشاء…', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.create',              'Create item', 'إنشاء بند', 'draft', 'CD-007 form'),
  ('admin.items.r2.form.created',             'Item created', 'تم إنشاء البند', 'draft', 'CD-007 form success'),
  ('admin.items.r2.form.duplicate',           'That item code already exists — codes are unique.', 'رمز البند موجود مسبقًا — الرموز فريدة.', 'draft', 'CD-007 S04 duplicate'),
  ('admin.items.r2.toggle.saving',            'Saving…', 'جارٍ الحفظ…', 'draft', 'CD-007 toggle'),
  ('admin.items.r2.toggle.deactivate',        'Deactivate', 'إلغاء التفعيل', 'draft', 'CD-007 toggle'),
  ('admin.items.r2.toggle.reactivate',        'Reactivate', 'إعادة التفعيل', 'draft', 'CD-007 toggle'),
  ('admin.items.r2.toggle.reasonNote',        'History is preserved; no reason is captured and no item-row audit trigger exists.', 'يُحفظ التاريخ؛ لا يُلتقط سبب ولا يوجد مُشغِّل تدقيق لصفوف البنود.', 'draft', 'CD-007 toggle note'),
  ('admin.items.r2.preview.heading',          'Runtime preview — what the inspector sees', 'معاينة التشغيل — ما يراه المفتش', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.select',           'Preview item', 'معاينة البند', 'draft', 'CD-007 preview select'),
  ('admin.items.r2.preview.empty',            'No items to preview yet.', 'لا توجد بنود للمعاينة بعد.', 'draft', 'CD-007 preview empty'),
  ('admin.items.r2.preview.responsesLabel',   'Response the inspector records', 'الاستجابة التي يسجّلها المفتش', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.evidenceLabel',    'Evidence policy', 'سياسة الإثبات', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.evidenceNone',     'No base evidence required', 'لا يلزم إثبات أساسي', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.evidencePhoto',    'Photo required when non-compliant (min {min})', 'صورة مطلوبة عند عدم الامتثال (الحد الأدنى {min})', 'draft', 'CD-007 preview — {min}'),
  ('admin.items.r2.preview.evidenceSource',   'configured policy — source: engine settings', 'سياسة مُهيّأة — المصدر: إعدادات المحركات', 'draft', 'CD-007 preview evidence source'),
  ('admin.items.r2.preview.guidanceLabel',    'Inspector guidance', 'إرشاد المفتش', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.guidanceNone',     'No guidance recorded', 'لا يوجد إرشاد مسجَّل', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.scoringLabel',     'Scoring', 'الاحتساب', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.weight',           'weight {weight}', 'الوزن {weight}', 'draft', 'CD-007 preview — {weight}'),
  ('admin.items.r2.preview.noWeight',         'no score weight', 'لا وزن احتساب', 'draft', 'CD-007 preview'),
  ('admin.items.r2.preview.scoreExcluded',    'excluded from score on: {responses}', 'مستثنى من الاحتساب عند: {responses}', 'draft', 'CD-007 preview — {responses}'),
  ('admin.items.r2.preview.ncMaps',           'Non-compliant maps to: {target}', 'عدم الامتثال يُربط بـ: {target}', 'draft', 'CD-007 preview — {target}'),
  ('admin.items.r2.preview.conditional',      'Conditional logic present (display only — authoring not wired)', 'يوجد منطق شرطي (عرض فقط — التأليف غير موصول)', 'draft', 'CD-007 preview conditional'),
  ('admin.items.r2.preview.readonly',         'Read-only projection of stored configuration — nothing here is editable.', 'إسقاط للقراءة فقط للتهيئة المخزّنة — لا شيء هنا قابل للتعديل.', 'draft', 'CD-007 preview readonly'),
  ('admin.items.r2.preview.deactivated',      'This item is deactivated — hidden from new package versions; existing history is preserved.', 'هذا البند مُلغى التفعيل — مخفي عن إصدارات الحزم الجديدة؛ ويُحفظ التاريخ القائم.', 'draft', 'CD-007 preview deactivated'),
  ('admin.items.r2.status.active',            'active', 'مفعّل', 'draft', 'CD-007 status — paired with glyph'),
  ('admin.items.r2.status.deactivated',       'deactivated', 'مُلغى التفعيل', 'draft', 'CD-007 status — paired with glyph'),
  ('admin.items.r2.catalogue.heading',        'Catalogue', 'الكتالوج', 'draft', 'CD-007 catalogue'),
  ('admin.items.r2.col.code',                 'Code', 'الرمز', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.title',                'Title', 'العنوان', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.clause',               'Clause', 'البند اللائحي', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.semantics',            'Runtime semantics', 'دلالات التشغيل', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.weight',               'Weight', 'الوزن', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.usage',                'Published use', 'الاستخدام المنشور', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.status',               'Status', 'الحالة', 'draft', 'CD-007 col'),
  ('admin.items.r2.col.actions',              'Actions', 'الإجراءات', 'draft', 'CD-007 col'),
  ('admin.items.r2.sem.nc',                   'NC→', 'عدم امتثال←', 'draft', 'CD-007 semantics'),
  ('admin.items.r2.sem.evidence',             'photo on NC', 'صورة عند عدم الامتثال', 'draft', 'CD-007 semantics'),
  ('admin.items.r2.sem.scoreExcluded',        'score-excluded', 'مستثنى من الاحتساب', 'draft', 'CD-007 semantics'),
  ('admin.items.r2.sem.conditional',          'conditional (display only)', 'شرطي (عرض فقط)', 'draft', 'CD-007 semantics'),
  ('admin.items.r2.usage.unavailable',        'unavailable', 'غير متاح', 'draft', 'CD-007 usage — paired with glyph'),
  ('admin.items.r2.usage.note',               'This route provides no published-use count (HANDOFF_BLOCKED · backend).', 'هذا المسار لا يوفّر عدد الاستخدام المنشور (HANDOFF_BLOCKED · الواجهة الخلفية).', 'draft', 'CD-007 usage note'),
  ('admin.items.r2.blocked.heading',          'Contract targets — not yet wired', 'أهداف تعاقدية — غير موصولة بعد', 'draft', 'CD-007 blocked'),
  ('admin.items.r2.blocked.body',             'These are contract capabilities with no proven runtime leg today. They render as disabled targets so the design never implies they work.', 'هذه قدرات تعاقدية لا يوجد لها مسار تشغيل مُثبت اليوم. تظهر كأهداف معطّلة كي لا يوحي التصميم بأنها تعمل.', 'draft', 'CD-007 blocked body'),
  ('admin.items.r2.blocked.edit',             'Edit item / new version', 'تعديل البند / إصدار جديد', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.conditional',      'Author conditional rule', 'تأليف قاعدة شرطية', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.usage',            'Published-use warning — unavailable', 'تحذير الاستخدام المنشور — غير متاح', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.reason',           'Deactivation reason capture', 'التقاط سبب إلغاء التفعيل', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.audit',            'Item change audit trail', 'سجل تدقيق تغييرات البند', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.guard',            'Route guard / unauthorized redirect', 'حارس المسار / إعادة توجيه غير المصرّح', 'draft', 'CD-007 blocked target'),
  ('admin.items.r2.blocked.tag',              'not yet wired', 'غير موصول بعد', 'draft', 'CD-007 blocked tag'),
  ('admin.items.r2.blocked.editNote',         'Item edit / new version is a contract target (HANDOFF_BLOCKED · backend).', 'تعديل البند / إصدار جديد هدف تعاقدي (HANDOFF_BLOCKED · الواجهة الخلفية).', 'draft', 'CD-007 blocked row note'),
  ('admin.items.r2.blocked.editShort',        'Edit', 'تعديل', 'draft', 'CD-007 blocked row button'),
  ('admin.items.r2.owner.backend',            'owner: backend', 'المالك: الواجهة الخلفية', 'draft', 'CD-007 blocked owner'),
  ('admin.items.r2.owner.platform',           'owner: platform', 'المالك: المنصّة', 'draft', 'CD-007 blocked owner'),
  ('admin.items.r2.footer',                   'Items belong to regulations and are reused across packages (M09-002/007); deactivation preserves history (M09-014). Writes require compliance_admin/form_admin — RLS is the authority. inspection_items has no audit trigger.', 'تنتمي البنود إلى اللوائح وتُعاد عبر الحزم (M09-002/007)؛ إلغاء التفعيل يحفظ التاريخ (M09-014). تتطلب الكتابة دور compliance_admin/form_admin — سياسات RLS هي المرجع. جدول inspection_items لا يملك مُشغِّل تدقيق.', 'draft', 'CD-007 footer'),
  ('enum.value_date',                         'value date', 'تاريخ القيمة', 'draft', 'CD-007 response enum (shared)')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';   -- never clobber a human-reviewed translation
