-- CD-025 / SCR-WEB-150 / P03 — Plan Review & Publish · Arabic localization seed
-- Arabic values are the authored copy from the CD-025 R2 Claude Design pack
-- (project 20cb0dce-94f1-4423-b923-00d6fd0d2c24, D.ar dictionary in cd25-stage.js).
-- Seeded as status='draft' (machine/unreviewed) — human localization review is the
-- gate to 'reviewed', per migration 0013. Upsert is guarded so it NEVER overwrites
-- a row a human already reviewed, and shared keys keep their existing values.
-- Not a product-scope change: these are Arabic values for already-accepted EN UI
-- strings; no new Arabic scope, policy, or behaviour is introduced.

insert into ui_strings (key, en, ar, status, context) values
  -- phases
  ('plan.review.title',            'Plan review & publish', 'مراجعة الخطة والنشر', 'draft', 'CD-025 SCR-WEB-150'),
  ('plan.review.context',          'SCR-WEB-150 · review · publish', 'SCR-WEB-150 · مراجعة · نشر', 'draft', 'CD-025'),
  ('plan.review.loading',          'Loading your selection…', 'جارٍ تحميل تحديدك…', 'draft', 'CD-025'),
  ('plan.review.loadingNote',      'Validating factories, package, Inspectors and duplicates…', 'جارٍ التحقق من المصانع والحزمة والمفتشين والتكرارات…', 'draft', 'CD-025'),
  ('plan.review.staged',           'Staged review. No plan record exists yet — nothing is saved until you publish.', 'مراجعة مرحلية. لا يوجد سجل خطة بعد — لا يُحفظ شيء حتى تقوم بالنشر.', 'draft', 'CD-025'),
  ('plan.review.stagedSub',        'Selected factories carried from targeting · verifying sources', 'المصانع المحددة منقولة من الاستهداف · جارٍ التحقق من المصادر', 'draft', 'CD-025'),
  ('plan.review.unavailable',      'Planning data is temporarily unavailable (ERR-OPS-001). Return to targeting and try again.', 'بيانات التخطيط غير متاحة مؤقتًا (ERR-OPS-001). عُد إلى الاستهداف وحاول مرة أخرى.', 'draft', 'CD-025'),
  ('plan.review.emptyTitle',       'No factories selected', 'لا توجد مصانع محددة', 'draft', 'CD-025'),
  ('plan.review.emptyBody',        'Select target factories on the targeting screen, then continue to review.', 'حدّد المصانع المستهدفة في شاشة الاستهداف، ثم تابع إلى المراجعة.', 'draft', 'CD-025'),
  ('plan.review.back',             'Back to targeting', 'العودة إلى الاستهداف', 'draft', 'CD-025'),
  -- context card
  ('plan.review.method',           'Bulk plan — periodic compliance campaign', 'خطة جماعية — حملة الامتثال الدوري', 'draft', 'CD-025'),
  ('plan.review.freshness',        'Sources last checked', 'آخر فحص للمصادر', 'draft', 'CD-025 — provenance, not a policy threshold (FND-013)'),
  ('plan.review.selected',         'Selected', 'المحددة', 'draft', 'CD-025'),
  ('plan.review.retained',         'Retained', 'المُبقاة', 'draft', 'CD-025'),
  ('plan.review.visits',           'Proposed visits', 'الزيارات المقترحة', 'draft', 'CD-025'),
  ('plan.review.assignments',      'Assignments', 'الإسنادات', 'draft', 'CD-025'),
  ('plan.review.manual',           'manual', 'يدوي', 'draft', 'CD-025'),
  ('plan.review.auto',             'automatic', 'تلقائي', 'draft', 'CD-025'),
  ('plan.review.mode',             'Mode', 'النمط', 'draft', 'CD-025'),
  ('plan.review.scope',            'Scope', 'النطاق', 'draft', 'CD-025'),
  -- readiness
  ('plan.review.readiness',        'Readiness', 'الجاهزية', 'draft', 'CD-025'),
  ('plan.review.blockedTag',       'Blocked', 'محظور', 'draft', 'CD-025'),
  ('plan.review.readyTag',         'Ready', 'جاهز', 'draft', 'CD-025'),
  ('plan.review.blockersN',        '{n} items must be resolved before publishing', 'يجب معالجة {n} عنصر قبل النشر', 'draft', 'CD-025'),
  ('plan.review.clearAll',         'All checks pass — the plan is ready to publish', 'اجتازت جميع الفحوصات — الخطة جاهزة للنشر', 'draft', 'CD-025'),
  -- targets table
  ('plan.review.targetsH',         'Targets & proposed visits', 'المصانع والزيارات المقترحة', 'draft', 'CD-025'),
  ('plan.review.selectedLabel',    'selected', 'محدد', 'draft', 'CD-025'),
  ('plan.review.retainedLabel',    'retained', 'مُبقى', 'draft', 'CD-025'),
  ('plan.review.colCity',          'City', 'المدينة', 'draft', 'CD-025'),
  ('plan.review.colVisit',         'Proposed visit', 'الزيارة المقترحة', 'draft', 'CD-025'),
  ('plan.review.colAssign',        'Assignment & evidence', 'الإسناد والأدلة', 'draft', 'CD-025'),
  ('plan.review.autoLabel',        'Automatic — chosen at publish', 'تلقائي — يُختار عند النشر', 'draft', 'CD-025'),
  ('plan.review.autoNote',         'First eligible Inspector available in the window, decided by the server at publish. Not promised beforehand.', 'أول مفتش مؤهَّل ومتاح ضمن النافذة، يقرره الخادم عند النشر. لا يُوعد به مسبقًا.', 'draft', 'CD-025'),
  ('plan.review.excluded',         'Duplicate — excluded', 'مكرر — مستبعد', 'draft', 'CD-025'),
  ('plan.review.assignH',          'Assignment evidence', 'أدلة الإسناد', 'draft', 'CD-025'),
  ('plan.review.manualNamed',      'Manual — named now', 'يدوي — مُسمّى الآن', 'draft', 'CD-025'),
  ('plan.review.autoChosen',       'Automatic — chosen at publish', 'تلقائي — يُختار عند النشر', 'draft', 'CD-025'),
  ('plan.review.manualEvidenceNote','Named Inspectors are fixed into the plan. Overlaps in the window are flagged above and block publishing.', 'المفتشون المُسمَّون مثبتون في الخطة. تُعلَّم التعارضات في النافذة أعلاه وتمنع النشر.', 'draft', 'CD-025'),
  ('plan.review.splitLine',        '{manual} manual · {auto} automatic', '{manual} يدوي · {auto} تلقائي', 'draft', 'CD-025'),
  -- consequence ledger
  ('plan.review.ledgerH',          'Publish consequence ledger', 'سجل نتائج النشر', 'draft', 'CD-025'),
  ('plan.review.ledgerLead',       'Exactly what crossing the publish boundary will and will not do, bound to the current retained scope.', 'ما الذي سيفعله وما لن يفعله تجاوز حدود النشر بالضبط، مرتبطًا بالنطاق المُبقى الحالي.', 'draft', 'CD-025'),
  ('plan.review.gCreate',          'Will be created on successful commit', 'سيُنشأ عند نجاح الالتزام', 'draft', 'CD-025'),
  ('plan.review.gRef',             'Will be referenced for those visits', 'سيُرجَع إليه لتلك الزيارات', 'draft', 'CD-025'),
  ('plan.review.gRecord',          'Will be recorded or queued', 'سيُسجَّل أو يوضع في قائمة الانتظار', 'draft', 'CD-025'),
  ('plan.review.gNot',             'Will not happen at publication', 'لن يحدث عند النشر', 'draft', 'CD-025'),
  ('plan.review.cPlan',            '1 visit plan', 'خطة زيارة واحدة', 'draft', 'CD-025'),
  ('plan.review.cPlanD',           'A single plan grouping every retained visit under one plan ID.', 'خطة واحدة تجمع كل زيارة مُبقاة تحت معرف خطة واحد.', 'draft', 'CD-025'),
  ('plan.review.cVisits',          '{n} visits', '{n} زيارات', 'draft', 'CD-025'),
  ('plan.review.cVisitsD',         'One physical periodic-compliance visit per retained factory.', 'زيارة امتثال دوري ميدانية واحدة لكل مصنع مُبقى.', 'draft', 'CD-025'),
  ('plan.review.cAssign',          '{n} assignments', '{n} إسنادات', 'draft', 'CD-025'),
  ('plan.review.cAssignD',         'One Inspector assignment per visit.', 'إسناد مفتش واحد لكل زيارة.', 'draft', 'CD-025'),
  ('plan.review.rType',            'Periodic compliance · Physical', 'امتثال دوري · ميداني', 'draft', 'CD-025'),
  ('plan.review.rTypeD',           'Visit type and execution mode applied to every visit.', 'نوع الزيارة ونمط التنفيذ المطبّقان على كل زيارة.', 'draft', 'CD-025'),
  ('plan.review.rWin',             'Shared inspection window', 'نافذة التفتيش المشتركة', 'draft', 'CD-025'),
  ('plan.review.rWinD',            'The single window every visit in this campaign shares.', 'النافذة الواحدة التي تشترك فيها كل زيارة في هذه الحملة.', 'draft', 'CD-025'),
  ('plan.review.rMethod',          '{manual} manual · {auto} automatic assignees', '{manual} يدوي · {auto} مُسنَد تلقائيًا', 'draft', 'CD-025'),
  ('plan.review.rMethodD',         'Manual Inspectors are named now; automatic Inspectors are chosen server-side at publish.', 'المفتشون اليدويون يُسمَّون الآن؛ والتلقائيون يُختارون في الخادم عند النشر.', 'draft', 'CD-025'),
  ('plan.review.recAudit',         'Audit mutations recorded', 'تسجيل تغييرات المراجعة', 'draft', 'CD-025'),
  ('plan.review.recAuditD',        'Plan, visit and assignment inserts are captured by the append-only table triggers with actor and timestamp (FND-003).', 'عمليات إدراج الخطة والزيارة والإسناد تُلتقط بمشغّلات الجداول للإلحاق فقط مع الفاعل والوقت (FND-003).', 'draft', 'CD-025'),
  ('plan.review.recNotif',         '{n} assignment notification records queued', '{n} سجل إشعار إسناد في قائمة الانتظار', 'draft', 'CD-025'),
  ('plan.review.recNotifD',        'Queued for sending only — created inside the transaction. Delivery, receipt and acceptance are not proven here (FND-004).', 'في قائمة الإرسال فقط — أُنشئت داخل المعاملة. التسليم والاستلام والقبول غير مثبتة هنا (FND-004).', 'draft', 'CD-025'),
  ('plan.review.notStart',         'No inspection starts', 'لا يبدأ أي تفتيش', 'draft', 'CD-025'),
  ('plan.review.notStartD',        'Publishing schedules visits; it does not begin any inspection.', 'النشر يجدول الزيارات؛ ولا يبدأ أي تفتيش.', 'draft', 'CD-025'),
  ('plan.review.notDeliver',       'No message is delivered or accepted', 'لا تُسلَّم أي رسالة ولا تُقبَل', 'draft', 'CD-025'),
  ('plan.review.notDeliverD',      'Notification rows are queued; provider delivery and Inspector acceptance are separate, unproven events.', 'صفوف الإشعارات في قائمة الانتظار؛ والتسليم والقبول أحداث منفصلة غير مثبتة.', 'draft', 'CD-025'),
  ('plan.review.notDrop',          'No factory is silently dropped', 'لا يُستبعَد أي مصنع بصمت', 'draft', 'CD-025'),
  ('plan.review.notDropD',         'Excluded factories are named explicitly; excluded scope never disappears.', 'المصانع المستبعدة تُسمَّى صراحةً؛ ولا يختفي أي نطاق مستبعد.', 'draft', 'CD-025'),
  ('plan.review.notPartial',       'No partial result is called success', 'لا تُعتبَر أي نتيجة جزئية نجاحًا', 'draft', 'CD-025'),
  ('plan.review.notPartialD',      'All-or-nothing: any guard or write failure rolls the whole transaction back.', 'الكل أو لا شيء: أي فشل في حارس أو كتابة يُرجِع المعاملة بالكامل.', 'draft', 'CD-025'),
  ('plan.review.notFinal',         'A committable retained scope is not final yet — resolve the blockers to lock the counts.', 'لم يُقفَل بعد نطاق قابل للالتزام — عالِج العوائق لتثبيت الأعداد.', 'draft', 'CD-025'),
  -- corrections / action
  ('plan.review.correctH',         'Corrections & publish', 'التصحيحات والنشر', 'draft', 'CD-025'),
  ('plan.review.backConfig',       'Back to targeting & assignment', 'العودة إلى الاستهداف والإسناد', 'draft', 'CD-025'),
  ('plan.review.backConfigD',      'Return to targeting with this selection preserved.', 'العودة إلى الاستهداف مع الحفاظ على هذا التحديد.', 'draft', 'CD-025'),
  ('plan.review.willRecheck',      'On publish the server re-checks role, package status, duplicates, Inspector eligibility and assignment overlap inside one transaction, then commits all-or-nothing.', 'عند النشر يعيد الخادم فحص الدور وحالة الحزمة والتكرارات وأهلية المفتش وتعارض الإسناد داخل معاملة واحدة، ثم يلتزم بالكل أو لا شيء.', 'draft', 'CD-025'),
  ('plan.review.disabledPrefix',   'Disabled: ', 'معطّل: ', 'draft', 'CD-025'),
  ('plan.review.allClearNote',     'All checks pass — the server will commit all-or-nothing.', 'كل الفحوصات مجتازة — سيلتزم الخادم بالكل أو لا شيء.', 'draft', 'CD-025'),
  ('plan.review.removeExcluded',   'Remove excluded factories', 'إزالة المصانع المستبعدة', 'draft', 'CD-025'),
  ('plan.review.publishReady',     'Publish plan and create {n} visits', 'انشر الخطة وأنشئ {n} زيارات', 'draft', 'CD-025'),
  ('plan.review.publishBlocked',   'Publish blocked — resolve {n} items', 'النشر محظور — عالِج {n} عناصر', 'draft', 'CD-025'),
  ('plan.review.checking',         'Checking readiness…', 'جارٍ التحقق من الجاهزية…', 'draft', 'CD-025'),
  ('plan.review.fix',              'Fix', 'إصلاح', 'draft', 'CD-025'),
  ('plan.review.change',           'Change', 'تغيير', 'draft', 'CD-025'),
  ('plan.review.reviewAction',     'Review', 'مراجعة', 'draft', 'CD-025'),
  ('plan.review.remove',           'Remove', 'إزالة', 'draft', 'CD-025'),
  ('plan.review.skip',             'Skip to publish action', 'الانتقال إلى إجراء النشر', 'draft', 'CD-025'),
  -- publishing / result
  ('plan.review.publishingTitle',  'Publishing…', 'جارٍ النشر…', 'draft', 'CD-025'),
  ('plan.review.publishingBody',   'The server is validating and committing the plan, its visits and assignments in one transaction. Do not close this page.', 'يتحقق الخادم ويلتزم بالخطة وزياراتها وإسناداتها في معاملة واحدة. لا تُغلق هذه الصفحة.', 'draft', 'CD-025'),
  ('plan.review.publishingSub',    '‘Published’ is not shown until the transaction returns an authoritative result.', 'لا تُعرض حالة «منشور» حتى تُرجِع المعاملة نتيجة مرجعية.', 'draft', 'CD-025'),
  ('plan.review.failTitle',        'Publishing failed — nothing was published', 'فشل النشر — لم يُنشر شيء', 'draft', 'CD-025'),
  ('plan.review.failBody',         'Nothing was published. The plan and visits were not created.', 'لم يُنشر شيء. لم تُنشأ الخطة والزيارات.', 'draft', 'CD-025'),
  ('plan.review.failSub',          'Technical details are logged server-side only.', 'سُجِّلت التفاصيل التقنية من جهة الخادم فقط.', 'draft', 'CD-025'),
  ('plan.review.tryAgain',         'Try again', 'إعادة المحاولة', 'draft', 'CD-025'),
  ('plan.review.successTitle',     'Plan published', 'نُشرت الخطة', 'draft', 'CD-025'),
  ('plan.review.successBody',      'The authoritative transaction committed in full.', 'التزمت المعاملة المرجعية بالكامل.', 'draft', 'CD-025'),
  ('plan.review.successSub',       'Notifications are queued for sending only — no delivery, acceptance or inspection start. Zero completed visits and zero drafts at this moment.', 'الإشعارات في قائمة الإرسال فقط — لا تسليم ولا قبول ولا بدء تفتيش. صفر زيارات مكتملة وصفر مسودات في هذه اللحظة.', 'draft', 'CD-025'),
  ('plan.review.sPlan',            'Plan', 'خطة', 'draft', 'CD-025'),
  ('plan.review.sVisits',          'Visits published', 'زيارات منشورة', 'draft', 'CD-025'),
  ('plan.review.sAssign',          'Assignments', 'إسنادات', 'draft', 'CD-025'),
  ('plan.review.sNotif',           'Notifications queued', 'إشعارات في الانتظار', 'draft', 'CD-025'),
  ('plan.review.goVisits',         'Go to visits', 'الذهاب إلى الزيارات', 'draft', 'CD-025'),
  ('plan.review.openPlan',         'Open the published plan (read-only)', 'فتح الخطة المنشورة (للقراءة فقط)', 'draft', 'CD-025'),
  -- unauthorized
  ('plan.review.unauth.title',     'You don’t have access to review this plan', 'لا تملك صلاحية مراجعة هذه الخطة', 'draft', 'CD-025 RBAC-007'),
  ('plan.review.unauth.body',      'This view requires the Planner role and matching scope. Navigation visibility is not authorization; RLS remains the boundary.', 'يتطلب هذا العرض دور المُخطِّط ونطاقًا مطابقًا. الرؤية في التنقّل ليست تفويضًا؛ ويظل RLS حدَّ التفويض.', 'draft', 'CD-025 RBAC-007'),
  ('plan.review.unauth.back',      'Back to planning', 'العودة إلى التخطيط', 'draft', 'CD-025'),
  -- blocker copy (kind → title / detail)
  ('plan.review.bl.dup.t',         'Active periodic visit already exists — cannot create a duplicate', 'توجد زيارة دورية نشطة بالفعل — لا يمكن إنشاء نسخة مكررة', 'draft', 'CD-025 M02-012'),
  ('plan.review.bl.dup.d',         '{targets}', '{targets}', 'draft', 'CD-025'),
  ('plan.review.bl.ov.t',          'Inspector is already booked in this window', 'المفتش محجوز بالفعل في هذه النافذة', 'draft', 'CD-025 M01-029'),
  ('plan.review.bl.ov.d',          '{targets}', '{targets}', 'draft', 'CD-025'),
  ('plan.review.bl.cov.t',         '{n} visits have no eligible Inspector available in the window', '{n} زيارات بلا مفتش مؤهَّل متاح في النافذة', 'draft', 'CD-025'),
  ('plan.review.bl.cov.d',         'Widen the window or assign an Inspector manually.', 'غيّر النافذة أو أسند مفتشًا يدويًا.', 'draft', 'CD-025'),
  ('plan.review.bl.nopkg.t',       'No published or locked package is available', 'لا توجد حزمة منشورة أو مقفلة متاحة', 'draft', 'CD-025'),
  ('plan.review.bl.nopkg.d',       'Cannot reference an unpublished version — this is a legitimate empty state.', 'لا يمكن الإسناد إلى إصدار غير منشور — هذه حالة فارغة مشروعة.', 'draft', 'CD-025'),
  ('plan.review.bl.pkginv.t',      'Selected package is no longer published at the authoritative check', 'الحزمة المحددة لم تعد منشورة عند الفحص المرجعي', 'draft', 'CD-025'),
  ('plan.review.bl.pkginv.d',      'Revalidate and choose a currently published version before publishing.', 'أعد التحقق واختر إصدارًا منشورًا حاليًا قبل النشر.', 'draft', 'CD-025'),
  ('plan.review.bl.nopool.t',      'No Inspector exists in the Inspector role pool', 'لا يوجد مفتش ضمن دور المفتش', 'draft', 'CD-025'),
  ('plan.review.bl.nopool.d',      'Automatic assignment cannot be derived — a legitimate empty pool, not a source failure.', 'لا يمكن اشتقاق الإسناد التلقائي — حالة فارغة مشروعة، لا فشل مصدر.', 'draft', 'CD-025'),
  ('plan.review.bl.cfg.t',         'Mandatory configuration is missing', 'التهيئة الإلزامية ناقصة', 'draft', 'CD-025'),
  ('plan.review.bl.cfg.d',         'Set the visit type, a valid window (end after start) and a package.', 'حدّد نوع الزيارة ونافذة صحيحة (النهاية بعد البداية) وحزمة.', 'draft', 'CD-025'),
  ('plan.review.bl.srcf.t',        'Factory/target source could not be verified', 'تعذّر التحقق من مصدر المصانع', 'draft', 'CD-025'),
  ('plan.review.bl.srcf.d',        'Not evaluated — blocks safely rather than showing false emptiness.', 'غير مُقيَّم — يمنع بأمان بدلًا من عرض فراغ زائف.', 'draft', 'CD-025'),
  ('plan.review.bl.srcp.t',        'Package source is unavailable', 'تعذّر الوصول إلى مصدر الحزم', 'draft', 'CD-025'),
  ('plan.review.bl.srcp.d',        'Distinct from ‘no package’ — the state is not evaluated, not empty.', 'مختلف عن «لا توجد حزمة» — الحالة غير مُقيَّمة، لا فارغة.', 'draft', 'CD-025'),
  ('plan.review.bl.srci.t',        'Inspector source is unavailable', 'تعذّر الوصول إلى مصدر المفتشين', 'draft', 'CD-025'),
  ('plan.review.bl.srci.d',        'Distinct from ‘empty pool’ — an empty pool cannot be confirmed.', 'مختلف عن «لا مفتشين» — لا يمكن تأكيد التجمّع الفارغ.', 'draft', 'CD-025'),
  ('plan.review.bl.srcd.t',        'Duplicate / overlap check could not run', 'تعذّر تنفيذ فحص التكرار/التعارض', 'draft', 'CD-025'),
  ('plan.review.bl.srcd.d',        'Distinct from ‘verified zero conflicts’ — publish is not allowed without the check.', 'مختلف عن «صفر تعارضات مؤكَّد» — لا يُسمح بالنشر دون فحص.', 'draft', 'CD-025')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';   -- never clobber a human-reviewed translation
