-- Compliance/Enforcement Library + field PWA terminology remediation (new surfaces)
-- Guarded upsert: never clobbers a human-reviewed translation (status='draft' only).
insert into ui_strings (key, en, ar, status, context) values
  ('approval.queue.emptyBody', 'No maker-checker assignments were found for your access.', 'لم يتم العثور على أي مهام فحص مزدوج ضمن صلاحية وصولك.', 'draft', 'empty-state body; removed ''governed read succeeded'''),
  ('approval.queue.history', 'Decision history', 'سجل القرارات', 'draft', 'section heading; dropped ''Immutable'''),
  ('approval.queue.loading', 'Loading Awaiting Approval', 'جارٍ تحميل بانتظار الاعتماد', 'draft', 'loading-state title'),
  ('approval.queue.loadingBody', 'Reading requests, objects, decisions, and final receipts within your access scope.', 'جارٍ قراءة الطلبات والعناصر والقرارات والإيصالات النهائية ضمن نطاق وصولك.', 'draft', 'loading-state body; ''immutable''->''final'', ''governed scope''->''access scope'''),
  ('approval.queue.publishedVersion', 'Published final version', 'الإصدار النهائي المنشور', 'draft', 'publication success badge; ''immutable''->''final'' per glossary'),
  ('approval.queue.scoringHoldBody', 'Item scoring and score-exclusion objects are not allowed by the request rules.', 'لا تسمح قواعد الطلب بتسجيل نقاط العناصر أو استبعادها من التقييم.', 'draft', 'warning banner explaining an unavailable feature; removed ''governed request contract'''),
  ('approval.queue.title', 'Awaiting Approval', 'بانتظار الاعتماد', 'draft', 'page/shell title'),
  ('approval.queue.unauthorized', 'Awaiting Approval access denied', 'الوصول إلى بانتظار الاعتماد مرفوض', 'draft', 'unauthorized-state heading'),
  ('approval.queue.unauthorizedBody', 'Sign in with a reviewer role. No list data or action controls are shown.', 'سجّل الدخول بدور مراجع معتمد. لا تُعرض بيانات القائمة ولا أدوات الإجراء.', 'draft', 'unauthorized-state body; removed ''governed'' and ''queue'''),
  ('approval.queue.unavailable', 'Awaiting Approval unavailable', 'بانتظار الاعتماد غير متاح', 'draft', 'error-state heading'),
  ('approval.queue.unavailableBody', 'No workload, eligibility, or decision data could be loaded.', 'تعذّر تحميل بيانات عبء العمل أو الأهلية أو القرار.', 'draft', 'error-state body, plain-language rewrite'),
  ('approval.queue.versionPublished', 'Final version published', 'تم نشر الإصدار النهائي', 'draft', 'timeline entry; ''immutable''->''final'''),
  ('field.completed.integrity', 'This inspection is unavailable, outside your assignment scope, or has no final submitted version. No editable record was used instead.', 'عملية التفتيش غير متاحة أو خارج نطاق إسنادك أو لا تحتوي على نسخة نهائية مُقدّمة. لم يتم استخدام سجل قابل للتعديل بدلاً منها.', 'draft', 'Critical alert shown when a completed-inspection receipt cannot be resolved'),
  ('field.completed.lineage', 'final submitted snapshot', 'لقطة نهائية مقدَّمة', 'draft', 'Caption footer under the completion receipt'),
  ('field.completed.readOnly', 'Locked final version — read-only', 'نسخة نهائية مقفلة — للقراءة فقط', 'draft', 'Lock banner on the completion receipt detail page'),
  ('field.completed.subtitle', 'Final submitted report history', 'سجل التقارير النهائية المقدمة', 'draft', 'Header subtitle on Completed Inspections list page'),
  ('field.devices.dt.checking', 'Reading the device list for your account.', 'جارٍ قراءة قائمة الأجهزة الخاصة بحسابك.', 'draft', 'settings/devices/page.tsx enrollment-status detail line shown while checking device state; removed exposed dev jargon ''RLS-scoped'' from both EN and AR, reworded to plain language.'),
  ('field.establishments.emptyBody', 'Change or clear the search filters. Only records you can access will show here.', 'غيّر مرشحات البحث أو امسحها. لا تظهر هنا إلا السجلات التي تملك صلاحية الوصول إليها.', 'draft', 'establishments/page.tsx empty-state body under the search grid; removed exposed dev jargon ''RLS'' and reworded to plain language for both EN and AR.'),
  ('field.incidents.immediateLock', 'When it starts, the checklist locks and cannot be changed — Immediate Inspection does not skip this lock.', 'عند البدء، تُقفل قائمة التفتيش ولا يمكن تغييرها — التفتيش الفوري لا يتجاوز هذا القفل.', 'draft', 'Explanatory note on the Incident Reports screen about immediate-inspection checklist locking; reworded ''package'' to ''checklist'' per DEC glossary spirit (frozen package definition -> Checklist version used for the inspection) and simplified ''immutable snapshot'' to plain English'),
  ('field.myTasks.noDossier', 'The full establishment record is unavailable until a commercial-registration/licence mapping exists for this factory, or Factory 360 access is granted.', 'ملف المنشأة الكامل غير متاح حتى يتوفر ربط بالسجل التجاري/الترخيص لهذا المصنع أو تُمنح صلاحية المصنع 360.', 'draft', 'my-tasks/page.tsx caption shown when the shared dossier loader returns no data; banned term ''dossier'' replaced with ''record''. Key name kept stable per instructions even though it still says ''noDossier''. Arabic unchanged (already said ملف المنشأة).'),
  ('field.myTasks.selectBody', 'Pick a task from the list to see the establishment record.', 'اختر مهمة من القائمة لعرض ملف المنشأة.', 'draft', 'my-tasks/page.tsx empty-detail-pane caption before a task is selected; banned term ''dossier'' replaced with ''record'' (this is the establishment record, not the Factory 360 profile). Arabic was already compliant, left unchanged.'),
  ('field.pack.repeatUnavailable', 'No violation history available (STR-KPI-011)', 'لا يوجد سجل مخالفات متاح (STR-KPI-011)', 'draft', 'page.tsx pre-inspection pack empty-state for repeat findings KPI; applied glossary mapping lineage -> history, kept STR-KPI-011 traceability code exactly.'),
  ('field.reports.emptyBody', 'A report appears here only after a final version is submitted.', 'يظهر التقرير هنا فقط بعد تقديم نسخة نهائية.', 'draft', 'Empty-state body copy on the field Reports screen'),
  ('field.reports.recordsHint', 'Submitted records available to this inspector — open a document to view its final version.', 'المحاضر المقدمة المتاحة لهذا المفتش — افتح المستند لعرض نسخته النهائية.', 'draft', 'Hint text above the visit-records list on the field Reports screen (two identical occurrences, both updated)'),
  ('field.start.arrivalRequired', 'Arrival evidence is required by Map Settings', 'دليل الوصول مطلوب بحسب إعدادات الخريطة', 'draft', 'page.tsx validation copy shown when arrival evidence is missing; applied glossary mapping GIS Configuration -> Map Settings and simplified phrasing. Arabic authored here for /admin/localization import.'),
  ('field.start.logExceptionSent', 'Exception recorded at ±{acc}m — this record cannot be changed', 'تم تسجيل الاستثناء عند دقة ±{acc} متر — لا يمكن تعديل هذا السجل', 'draft', 'page.tsx toast/log message after an exception is recorded during check-in; removed dev-jargon ''immutable geo event''. Arabic authored here (t() has no inline AR param in this file; real value lives in ui_strings via /admin/localization — flag for import there).')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';
