-- MIM iPad Inspector App — Figma reconciliation localization seed
-- Sponsor authorization: SPONSOR_DECISIONS_AND_IMPLEMENTATION_AUTHORIZATION.md, DEC-H
-- ('implement all Arabic/English keys now; the 94 flagged translations remain
-- marked for legal/native review but do not block development').
--
-- Namespace: keys use a deliberate 'figma.<page>.<string_id>' staging prefix,
-- NOT the app's real screen namespaces (field.*, f360.*, admin.*) — the actual
-- wizard/report-family screens these strings belong to are not yet built
-- (blocked on DEC-A/DEC-A-derived slices). Renaming to real in-code keys happens
-- as each screen is implemented; this migration only guarantees the Arabic/English
-- content exists and is traceable back to TRANSLATION_REVIEW_REGISTER.csv string_id.
--
-- 347 of 389 rows seeded (skipped 42 NON_PRODUCT_REFERENCE /
-- sample-data rows — those are placeholder/BRD-sample values, never user-visible copy).
-- ALL rows land as status='draft': the 94 HUMAN_DECISION_REQUIRED rows (legal/domain
-- terminology, see TRANSLATION_REVIEW_REGISTER.csv open_question_ids) are additionally
-- marked in the context column so the localization admin UI surfaces them for the
-- combined native-Arabic/legal review pass (DEC-H).
-- Paste-safe: straight ASCII quotes and Arabic text only, no smart quotes.

insert into ui_strings (key, en, ar, status, context) values
  ('figma.hometasks.ht001', 'My Tasks', 'مهامي', 'draft', 'Figma HT-001 - My Tasks - Nav bar title'),
  ('figma.hometasks.ht002', 'Request #192994 Details', 'تفاصيل طلب رقم #192994', 'draft', 'Figma HT-002 - Task Details - Page title with request number'),
  ('figma.hometasks.ht003', 'Directions', 'الإتجاهات', 'draft', 'Figma HT-003 - Establishment card - Map action button'),
  ('figma.hometasks.ht004', 'Establishment Type', 'نوع المنشأة', 'draft', 'Figma HT-004 - Establishment data - Field label'),
  ('figma.hometasks.ht005', 'Limited Liability', 'ذات مسؤولية محدودة', 'draft', 'Figma HT-005 - Establishment data - Field value (sample) - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht006', 'Registration Number', 'رقم السجل', 'draft', 'Figma HT-006 - Establishment data - Field label'),
  ('figma.hometasks.ht007', 'Establishment Status', 'حالة المنشأة', 'draft', 'Figma HT-007 - Establishment data - Field label'),
  ('figma.hometasks.ht008', 'Request Status', 'حالة الطلب', 'draft', 'Figma HT-008 - Request data - Field label'),
  ('figma.hometasks.ht009', 'Request Creation Date', 'تاريخ انشاء الطلب', 'draft', 'Figma HT-009 - Request data - Field label'),
  ('figma.hometasks.ht010', 'Investment Size', 'حجم الاستثمار', 'draft', 'Figma HT-010 - Establishment data - Field label'),
  ('figma.hometasks.ht011', 'Risk Level', 'درجة الخطورة', 'draft', 'Figma HT-011 - Risk data - Field label - PENDING_LEGAL_NATIVE_REVIEW - see TQ-03'),
  ('figma.hometasks.ht012', 'Compliance Rate', 'نسبة الامتثال', 'draft', 'Figma HT-012 - Compliance data - Field label - PENDING_LEGAL_NATIVE_REVIEW - see TQ-03'),
  ('figma.hometasks.ht013', 'License Status', 'حالة الترخيص', 'draft', 'Figma HT-013 - License data - Field label'),
  ('figma.hometasks.ht014', 'License Type', 'نوع الترخيص', 'draft', 'Figma HT-014 - License data - Field label'),
  ('figma.hometasks.ht015', 'Production', 'الانتاج', 'draft', 'Figma HT-015 - License data - License type value'),
  ('figma.hometasks.ht016', 'License Number', 'رقم الرخصة', 'draft', 'Figma HT-016 - License data - Field label'),
  ('figma.hometasks.ht017', 'Expiry Date', 'تاريخ الانتهاء', 'draft', 'Figma HT-017 - License data - Field label'),
  ('figma.hometasks.ht018', 'Issue Date', 'تاريخ الاصدار', 'draft', 'Figma HT-018 - License data - Field label'),
  ('figma.hometasks.ht019', 'Customs Tariff Code', 'رمز البند الجمركي', 'draft', 'Figma HT-019 - Customs data - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht020', 'Last Visit Date', 'تاريخ آخر زيارة', 'draft', 'Figma HT-020 - Visit data - Field label'),
  ('figma.hometasks.ht021', 'Visit Nature', 'طبيعة الزيارة', 'draft', 'Figma HT-021 - Visit data - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht022', 'Visit Type', 'نوع الزيارة', 'draft', 'Figma HT-022 - Visit data - Field label'),
  ('figma.hometasks.ht023', 'Targeted Regulatory', 'رقابية مستهدفة', 'draft', 'Figma HT-023 - Visit data - Visit type value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-05'),
  ('figma.hometasks.ht024', 'Visit Status', 'حالة الزيارة', 'draft', 'Figma HT-024 - Visit data - Field label'),
  ('figma.hometasks.ht025', 'City', 'المدينة', 'draft', 'Figma HT-025 - Address - Field label'),
  ('figma.hometasks.ht026', 'Dammam', 'الدمام', 'draft', 'Figma HT-026 - Address - Sample value'),
  ('figma.hometasks.ht027', 'Region', 'المنطقة', 'draft', 'Figma HT-027 - Address - Field label'),
  ('figma.hometasks.ht028', 'Eastern Province', 'الشرقية', 'draft', 'Figma HT-028 - Address - Sample value'),
  ('figma.hometasks.ht029', 'Nationality', 'الجنسية', 'draft', 'Figma HT-029 - Contact - Field label'),
  ('figma.hometasks.ht030', 'Kingdom of Saudi Arabia', 'المملكة العربية السعودية', 'draft', 'Figma HT-030 - Contact - Sample value'),
  ('figma.hometasks.ht031', 'ID Number', 'رقم الهوية', 'draft', 'Figma HT-031 - Contact - Field label'),
  ('figma.hometasks.ht032', 'Name', 'الاسم', 'draft', 'Figma HT-032 - Contact - Field label'),
  ('figma.hometasks.ht034', 'Email', 'البريد الإلكتروني', 'draft', 'Figma HT-034 - Contact - Field label'),
  ('figma.hometasks.ht035', 'Mobile', 'الجوال', 'draft', 'Figma HT-035 - Contact - Field label'),
  ('figma.hometasks.ht036', 'Workforce Count', 'عدد العمالة', 'draft', 'Figma HT-036 - Factory data - Field label'),
  ('figma.hometasks.ht037', 'Expected Annual Capacity', 'حجم الطاقة المتوقعة سنوياً', 'draft', 'Figma HT-037 - Factory data - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht038', 'Factory Number', 'رقم المصنع', 'draft', 'Figma HT-038 - Factory data - Field label'),
  ('figma.hometasks.ht039', 'Start Visit Execution', 'بدء تنفيذ الزيارة', 'draft', 'Figma HT-039 - Task actions - Primary CTA'),
  ('figma.hometasks.ht040', 'Resume Visit', 'استكمال الزيارة', 'draft', 'Figma HT-040 - Task actions - Primary CTA (in-progress task)'),
  ('figma.hometasks.ht041', 'Search', 'بحث', 'draft', 'Figma HT-041 - Tasks list - Search field placeholder'),
  ('figma.hometasks.ht042', 'Notifications', 'الإشعارات', 'draft', 'Figma HT-042 - Notifications - Panel title'),
  ('figma.hometasks.ht043', 'Notification Details', 'تفاصيل الإشعار', 'draft', 'Figma HT-043 - Notification details - Panel title'),
  ('figma.hometasks.ht044', 'Notification Date & Time', 'تاريخ و وقت الإشعار', 'draft', 'Figma HT-044 - Notification details - Field label'),
  ('figma.hometasks.ht045', 'Notification Sender', 'مرسل الإشعار', 'draft', 'Figma HT-045 - Notification details - Field label'),
  ('figma.hometasks.ht047', 'Notification Text', 'نص الإشعار', 'draft', 'Figma HT-047 - Notification details - Field label'),
  ('figma.hometasks.ht048', 'Dear Al-Huda Industrial Establishment, please be advised that the industrial license data was updated on 16/12/2025 as part of the Ministry of Industry and Mineral Resources services...', 'السادة الكرام منشأة الهدى للصناعة، نود إحاطتكم علمًا بأنه قد تم تحديث بيانات الترخيص الصناعي بتاريخ 16/12/2025...', 'draft', 'Figma HT-048 - Notification body - Sample notification body - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht049', 'Profile', 'الملف الشخصي', 'draft', 'Figma HT-049 - Profile - Panel title'),
  ('figma.hometasks.ht051', 'Field Inspector', 'مفتش ميداني', 'draft', 'Figma HT-051 - Profile - Role label'),
  ('figma.hometasks.ht052', 'Mobile Number', 'رقم الجوال', 'draft', 'Figma HT-052 - Profile - Field label'),
  ('figma.hometasks.ht053', 'Riyadh', 'الرياض', 'draft', 'Figma HT-053 - Profile - Sample value'),
  ('figma.hometasks.ht054', 'Central', 'الوسطى', 'draft', 'Figma HT-054 - Profile - Region sample value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht055', 'Substitute', 'البديل', 'draft', 'Figma HT-055 - Profile - Field label (substitute inspector) - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.hometasks.ht056', 'Sign Out', 'تسجيل الخروج', 'draft', 'Figma HT-056 - Profile - Action'),
  ('figma.hometasks.ht057', 'Sign In', 'تسجيل الدخول', 'draft', 'Figma HT-057 - Login - Screen title/CTA'),
  ('figma.hometasks.ht058', 'Sign In', 'تسجيل دخول', 'draft', 'Figma HT-058 - Login - Button label'),
  ('figma.hometasks.ht060', 'Reset Password', 'إعادة تعيين كلمة المرور', 'draft', 'Figma HT-060 - Reset password - Screen title'),
  ('figma.hometasks.ht061', 'Enter the email address whose password you want to change in the field below.', 'قم إدخال عنوان البريد الإلكتروني الذي تود تغيير كلمة مروره في الحقل أدناه.', 'draft', 'Figma HT-061 - Reset password - Helper text'),
  ('figma.hometasks.ht062', 'Continue', 'متابعة', 'draft', 'Figma HT-062 - Reset password - CTA'),
  ('figma.hometasks.ht063', 'Back', 'عودة', 'draft', 'Figma HT-063 - Reset password - Secondary CTA'),
  ('figma.hometasks.ht064', 'Enter Verification Code', 'ادخل رمز التحقق', 'draft', 'Figma HT-064 - OTP - Screen title'),
  ('figma.hometasks.ht065', 'A code has been sent to the email address you entered. Please enter it in the fields below.', 'تم ارسال رمز الى عنوان البريد الالكتروني الذي قمت بادخاله. رجاء قم بإدخاله في الحقول أدناه.', 'draft', 'Figma HT-065 - OTP - Helper text'),
  ('figma.hometasks.ht066', 'Save New Password', 'حفظ كلمة المرور الجديدة', 'draft', 'Figma HT-066 - New password - CTA'),
  ('figma.hometasks.ht067', 'Password Changed Successfully', 'تم تغيير كلمة المرور بنجاح', 'draft', 'Figma HT-067 - Password success - Success title'),
  ('figma.hometasks.ht068', 'You can now sign in using the new password.', 'بإمكانك الأن تسجيل الدخول باستخدام كلمة المرور الجديدة.', 'draft', 'Figma HT-068 - Password success - Success body'),
  ('figma.hometasks.ht069', 'Back to Sign In', 'عودة لتسجيل الدخول', 'draft', 'Figma HT-069 - Password success - CTA'),
  ('figma.hometasks.ht070', 'Request Start Time', 'وقت بداية الطلب', 'draft', 'Figma HT-070 - Violation details - Field label'),
  ('figma.hometasks.ht071', 'Industrial Inspection', 'التفتيش الصناعي', 'draft', 'Figma HT-071 - App shell - App/module title'),
  ('figma.hometasks.ht072', 'Pull the nearest-tasks list upward', 'سحب قائمة اقرب المهام للأعلى', 'draft', 'Figma HT-072 - Annotation - Designer annotation'),
  ('figma.hometasks.ht073', 'Select "View all tasks" in the list or "My Tasks" in the nav bar', 'اختيار "عرض جميع المهام" في القائمة او "مهامي" في شريط التنقل', 'draft', 'Figma HT-073 - Annotation - Designer annotation'),
  ('figma.hometasks.ht074', 'Timeline', 'الجدول الزمني', 'draft', 'Figma HT-074 - Annotation - Designer annotation'),
  ('figma.visitreports.vr001', 'Next', 'التالي', 'draft', 'Figma VR-001 - Inspection Items pagination - Wizard nav CTA'),
  ('figma.visitreports.vr002', 'Previous', 'السابق', 'draft', 'Figma VR-002 - Inspection Items pagination - Wizard nav CTA'),
  ('figma.visitreports.vr003', 'Items list: this section appears only when one of these report types is selected: Visit Report, Chemical Release Report, Customs Exemption Report, Safety Report — according to report type. Please set the applicability status to continue.', 'قائمة البنود : يظهر هذا القسم فقط عند اختيار أحد أنواع التقارير التالية: تقرير الزيارة، تقرير فسح كيميائي، تقرير إعفاء جمركي، تقرير سلامة...', 'draft', 'Figma VR-003 - Inspection Items annotation - Designer conditional-logic annotation - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr004', 'When "Production" is selected → the production-status field appears. When "Stopped/Closed/Repair/Relocation" is selected → the establishment-status justification field and the closing government-authority field appear.', 'عند اختيار "الإنتاج" → يظهر حقل الحالة الإنتاجية. عند اختيار "متوقف/مغلق/إصلاح/نقل" → يظهر حقل مبرر حالة المنشأة وحقل الجهة الحكومية التي قامت بالإغلاق.', 'draft', 'Figma VR-004 - Establishment status annotation - Designer conditional-logic annotation - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr005', 'Establishment Data', 'بيانات المنشأة', 'draft', 'Figma VR-005 - Establishment Management - Section header'),
  ('figma.visitreports.vr006', 'MODON Authority', 'هيئة مدن', 'draft', 'Figma VR-006 - Establishment Management - Industrial-city authority value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-06'),
  ('figma.visitreports.vr007', 'Continuous Production', 'انتاج مستمر', 'draft', 'Figma VR-007 - Establishment Management - Production status value'),
  ('figma.visitreports.vr008', 'Contacts', 'جهات التواصل', 'draft', 'Figma VR-008 - Establishment Management - Section header'),
  ('figma.visitreports.vr009', 'Notes', 'الملاحظات', 'draft', 'Figma VR-009 - Establishment Management - Section header'),
  ('figma.visitreports.vr010', 'The industrial license data was recently updated. Please review the establishment data and confirm the license validity and license number before executing the visit. If any discrepancy exists between platform data and establishment data, please document it...', 'تم تحديث بيانات الترخيص الصناعي مؤخرًا. يرجى مراجعة بيانات المنشأة والتأكد من سريان الترخيص وصحة رقم الترخيص قبل تنفيذ الزيارة...', 'draft', 'Figma VR-010 - Notes sample - Sample note body (truncated in grep) - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr011', 'Include signature (read from user profile)', 'تضمين التوقيع (قراءة من تعريف المستخدم)', 'draft', 'Figma VR-011 - Signature - Toggle label - PENDING_LEGAL_NATIVE_REVIEW - see TQ-07'),
  ('figma.visitreports.vr012', 'Signature', 'التوقيع', 'draft', 'Figma VR-012 - Signature - Field label'),
  ('figma.visitreports.vr013', 'Add Signature', 'إضافة توقيع', 'draft', 'Figma VR-013 - Signature - CTA'),
  ('figma.visitreports.vr014', 'Save as Draft and Leave', 'حفظ كمسودة و المغادرة', 'draft', 'Figma VR-014 - Exit modal - Destructive-flow CTA'),
  ('figma.visitreports.vr015', 'Leave Without Saving', 'مغادرة بدون حفظ', 'draft', 'Figma VR-015 - Exit modal - Destructive CTA'),
  ('figma.visitreports.vr016', 'Visit Report — Al-Amal Workers Training Company', 'تقرير زيارة شركة الامل للتدريب العمال', 'draft', 'Figma VR-016 - Report title - Sample report title - PENDING_LEGAL_NATIVE_REVIEW - see TQ-05'),
  ('figma.visitreports.vr017', 'The request has been sent for review and approval', 'تم إرسال الطلب لغاية المراجعة والاعتماد', 'draft', 'Figma VR-017 - Submission success - Success title'),
  ('figma.visitreports.vr018', 'The request will be sent to the competent authority to complete review and approval.', 'سيتم إرسال الطلب إلى الجهة المختصة لاستكمال المراجعة والاعتماد.', 'draft', 'Figma VR-018 - Submission success - Success body'),
  ('figma.visitreports.vr019', 'Back to Establishments List', 'عودة لقائمة المنشآت', 'draft', 'Figma VR-019 - Submission success - CTA'),
  ('figma.visitreports.vr020', 'Send Inspection Plan', 'إرسال خطة التفتيش', 'draft', 'Figma VR-020 - Section title - Flow title'),
  ('figma.visitreports.vr021', 'Please set the applicability status to continue the inspection process.', 'يرجى تحديد حالة التطبيق للمتابعة في عملية التفتيش.', 'draft', 'Figma VR-021 - Inline alert - Validation alert'),
  ('figma.visitreports.vr022', 'This merge will change some things in the club, e.g. club data, admin staff, memberships, and activities...', 'الدمج هذا بيغيّر بعض الأمور في النادي، مثل، بيانات النادي، الطاقم الإداري، العضويات، والأنشطة...', 'draft', 'Figma VR-022 - Inline alert (stray) - LEFTOVER copy from another product (club domain) - PENDING_LEGAL_NATIVE_REVIEW - see TQ-10'),
  ('figma.visitreports.vr023', 'Contact (1)', 'جهة التواصل (1)', 'draft', 'Figma VR-023 - Contacts - Repeater item header'),
  ('figma.visitreports.vr024', 'Send', 'إرسال', 'draft', 'Figma VR-024 - Summons Notice - Primary CTA'),
  ('figma.visitreports.vr025', 'Closed', 'مغلق', 'draft', 'Figma VR-025 - Establishment status - Status value'),
  ('figma.visitreports.vr026', 'Closed by the Ministry', 'مغلق من قبل الوزارة', 'draft', 'Figma VR-026 - Establishment status - Status justification value'),
  ('figma.visitreports.vr027', 'Ministry of Interior', 'وزارة الداخلية', 'draft', 'Figma VR-027 - Closing authority - Government authority value'),
  ('figma.visitreports.vr028', 'Unable to Complete Visit', 'تعذر تنفيذ الزيارة', 'draft', 'Figma VR-028 - Establishment Details - Secondary CTA / flow name'),
  ('figma.visitreports.vr029', 'Report Type', 'نوع التقرير', 'draft', 'Figma VR-029 - Establishment Details - Field label'),
  ('figma.visitreports.vr031', 'Start Preparing the Plan', 'ابدأ إعداد الخطة', 'draft', 'Figma VR-031 - Establishment Details - Primary CTA'),
  ('figma.visitreports.vr032', 'Specialization Details', 'تفاصيل التخصص', 'draft', 'Figma VR-032 - Specialization details - Section header'),
  ('figma.visitreports.vr033', 'Is a specialized visit needed?', 'هل يوجد حاجة لزيارة تخصصية؟', 'draft', 'Figma VR-033 - Specialization details - Yes/No question'),
  ('figma.visitreports.vr034', 'Yes', 'نعم', 'draft', 'Figma VR-034 - Yes option - Radio option'),
  ('figma.visitreports.vr035', 'Customs Exemption', 'اعفاء جمركي', 'draft', 'Figma VR-035 - Specialization details - Department/report value'),
  ('figma.visitreports.vr036', 'Sample Details', 'تفاصيل العينات', 'draft', 'Figma VR-036 - Samples - Section header'),
  ('figma.visitreports.vr037', 'Were samples collected from the establishment?', 'هل تم سحب عينات من المنشاة؟', 'draft', 'Figma VR-037 - Samples - Yes/No question'),
  ('figma.visitreports.vr038', 'Seizure Details', 'تفاصيل الحجز', 'draft', 'Figma VR-038 - Seizure - Section header - PENDING_LEGAL_NATIVE_REVIEW - see TQ-04'),
  ('figma.visitreports.vr039', 'Were products seized?', 'هل تم حجز منتجات؟', 'draft', 'Figma VR-039 - Seizure - Yes/No question - PENDING_LEGAL_NATIVE_REVIEW - see TQ-04'),
  ('figma.visitreports.vr040', 'Report Notes', 'ملاحظات المحضر', 'draft', 'Figma VR-040 - Report notes - Section header (official record notes) - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr041', 'Add Sample Photo', 'إضف صورة العينة', 'draft', 'Figma VR-041 - Sample photo - Upload label'),
  ('figma.visitreports.vr042', 'For best results upload an image 550 px wide × 340 px high, jpg format, max size 2 MB.', 'للحصول على أفضل النتائج، قم بتحميل الصورة عرض :550 px ارتفاع الصورة :340 px امتداد الصورة jpg واقصى حجم للصورة 2MB', 'draft', 'Figma VR-042 - Sample photo - Upload helper'),
  ('figma.visitreports.vr043', 'Final Product Sample', 'عينة منتج نهائي', 'draft', 'Figma VR-043 - Sample fields - Sample type value'),
  ('figma.visitreports.vr044', 'Polyethylene (PE) Pellets', 'حبيبات بولي إيثيلين PE', 'draft', 'Figma VR-044 - Sample fields - Sample material value'),
  ('figma.visitreports.vr045', 'The record day appears automatically after selecting the date.', 'يظهر يوم المحضر تلقائيًا بعد اختيار التاريخ.', 'draft', 'Figma VR-045 - Date helper - Field helper'),
  ('figma.visitreports.vr047', 'Add New Sample', 'إضافة عينة جديدة', 'draft', 'Figma VR-047 - Samples - CTA'),
  ('figma.visitreports.vr048', 'Product (1)', 'المنتج (1)', 'draft', 'Figma VR-048 - Seizure - Repeater item header'),
  ('figma.visitreports.vr049', 'Add New Products', 'إضافة منتجات جديدة', 'draft', 'Figma VR-049 - Seizure - CTA'),
  ('figma.visitreports.vr051', 'Supporting Documents for Review', 'الوثائق الداعمة للمراجعة', 'draft', 'Figma VR-051 - Attachments - Upload section header'),
  ('figma.visitreports.vr052', 'Attachments', 'مرفقات', 'draft', 'Figma VR-052 - Attachments - Label'),
  ('figma.visitreports.vr053', 'Browse Files', 'تصفح الملفات', 'draft', 'Figma VR-053 - Attachments - Upload CTA'),
  ('figma.visitreports.vr054', 'Incident Verification Record', 'محضر إثبات واقعة', 'draft', 'Figma VR-054 - Related records - Record type chip - PENDING_LEGAL_NATIVE_REVIEW - see TQ-01'),
  ('figma.visitreports.vr055', 'Item', 'البند', 'draft', 'Figma VR-055 - Violation item - Modal field label'),
  ('figma.visitreports.vr056', 'No operating license', 'عدم وجود رخصة تشغيل', 'draft', 'Figma VR-056 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr057', 'Licenses and Permits (14/16)', 'التراخيص والتصاريح (16/14)', 'draft', 'Figma VR-057 - Checklist group - Checklist group header with progress'),
  ('figma.visitreports.vr058', 'No safety permit', 'عدم وجود تصريح سلامة', 'draft', 'Figma VR-058 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr059', 'Production without a license from military authorities', 'الإنتاج دون وجود رخصة من الجهات العسكرية', 'draft', 'Figma VR-059 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr060', 'Production without a permit from the Nuclear Regulatory Commission', 'الإنتاج دون وجود تصريح من هيئة الرقابة النووية', 'draft', 'Figma VR-060 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr061', 'Production without a license from the Food and Drug Authority', 'الإنتاج دون وجود رخصة من هيئة الغذاء والدواء', 'draft', 'Figma VR-061 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr062', 'No valid environmental permit', 'عدم وجود تصريح بيئي ساري', 'draft', 'Figma VR-062 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr063', 'No industrial security permit', 'عدم وجود تصريح الأمن الصناعي', 'draft', 'Figma VR-063 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr064', 'No civil aviation permit', 'عدم وجود تصريح الطيران المدني', 'draft', 'Figma VR-064 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr065', 'No Ports Authority permit', 'عدم وجود تصريح هيئة الموانئ', 'draft', 'Figma VR-065 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr066', 'Producing products not listed in the industrial license', 'إنتاج منتجات غير موجودة في الترخيص الصناعي', 'draft', 'Figma VR-066 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr067', 'No ports recycling permit', 'عدم وجود تصريح موانئ لإعادة التدوير', 'draft', 'Figma VR-067 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr068', 'No documented safety training for workers', 'عدم وجود تدريب سلامة موثّق للعاملين', 'draft', 'Figma VR-068 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr069', 'Administrative Observations (6/6)', 'الملاحظات الإدارية (6/6)', 'draft', 'Figma VR-069 - Checklist group - Checklist group header'),
  ('figma.visitreports.vr070', 'Presence of fumes or volatile substances', 'وجود أبخرة أو مواد متطايرة', 'draft', 'Figma VR-070 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr071', 'Project expansion without Ministry approval', 'توسعة المشروع دون موافقة الوزارة', 'draft', 'Figma VR-071 - Violation item - Violation item - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr072', 'This is from the BRD file', 'هذا من ملف BRD', 'draft', 'Figma VR-072 - BRD annotation - Designer annotation'),
  ('figma.visitreports.vr073', 'Related records appear per visit status and conditions. Field visit: all available records and notices appear. Unable-to-complete visit: (Summons Notice + Incident Verification Record) appear, plus records of ...', 'تظهر المحاضر ذات الصلة حسب حالة الزيارة وبعض الشروط. في زيارة ميدانية: تظهر جميع المحاضر والإشعارات المتاحة. في تعذّر تنفيذ الزيارة: تظهر (مذكرة استدعاء + محضر إثبات واقعة)...', 'draft', 'Figma VR-073 - Report-visibility annotation - Conditional-visibility rule annotation - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr074', 'When report type "Visit Report" is selected in visit data, the "specialized visit needed" field appears. If "Yes", the "Reason" and "Competent Department" fields appear. When a product requiring sampling is specified, the system ...', 'عند اختيار نوع التقرير "تقرير زيارة" من بيانات الزيارة، يظهر حقل "يوجد حاجة لزيارة تخصصية". وإذا تم اختيار "نعم"، تظهر حقول "السبب" و"الإدارة المختصة". عند تحديد منتج يتطلب سحب عينة، يقوم النظام...', 'draft', 'Figma VR-074 - Specialized-visit annotation - Conditional-logic annotation - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr075', 'Inspection Items', 'بنود التفتيش', 'draft', 'Figma VR-075 - Wizard tabs - Wizard step / page title'),
  ('figma.visitreports.vr076', 'Record Details', 'تفاصيل المحاضر', 'draft', 'Figma VR-076 - Wizard tabs - Wizard step label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr077', 'Records', 'المحاضر', 'draft', 'Figma VR-077 - Wizard tabs - Wizard step label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr078', 'Visit Results', 'نتائج الزيارة', 'draft', 'Figma VR-078 - Wizard tabs - Wizard step label'),
  ('figma.visitreports.vr079', 'Establishment File', 'ملف المنشأة', 'draft', 'Figma VR-079 - Wizard tabs - Wizard step label'),
  ('figma.visitreports.vr080', 'Items List', 'قائمة البنود', 'draft', 'Figma VR-080 - Wizard tabs - Wizard step label'),
  ('figma.visitreports.vr081', 'Continue Creating Later', 'متابعة الإنشاء لاحقًا', 'draft', 'Figma VR-081 - Exit modal - Draft-exit CTA'),
  ('figma.visitreports.vr082', 'A photo was captured from the video and saved to your device photo album.', 'تم إلتقاط صورة من الفيديو، وتم حفظه في البوم الصور في جهازك.', 'draft', 'Figma VR-082 - Camera toast - Success toast'),
  ('figma.visitreports.vr083', 'Samples', 'العينات', 'draft', 'Figma VR-083 - Evidence linking - Section header'),
  ('figma.visitreports.vr084', 'Products', 'المنتجات', 'draft', 'Figma VR-084 - Evidence linking - Section header'),
  ('figma.visitreports.vr085', 'Link Photo to Samples', 'ربط الصورة العينات', 'draft', 'Figma VR-085 - Evidence linking - Action label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr086', 'Link Products Photo', 'ربط صورة المنتجات', 'draft', 'Figma VR-086 - Evidence linking - Action label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr087', 'To choose a photo, select one of the previously captured photos and link it to this item.', 'لاختيار الصورة، قم بتحديد صورة من الصور الملتقطة مسبقًا وربطها بهذا العنصر.', 'draft', 'Figma VR-087 - Evidence linking - Helper text'),
  ('figma.visitreports.vr088', 'Establishment Details', 'تفاصيل المنشأة', 'draft', 'Figma VR-088 - Establishment Details - Page title'),
  ('figma.visitreports.vr089', 'Establishment Name', 'اسم المنشأة', 'draft', 'Figma VR-089 - Establishment Details - Field label'),
  ('figma.visitreports.vr091', 'Registered Visit Access Link', 'رابط الدخول للزيارة المسجّل', 'draft', 'Figma VR-091 - Virtual visit - Field label (virtual visit) - PENDING_LEGAL_NATIVE_REVIEW - see TQ-09'),
  ('figma.visitreports.vr092', 'Actual Visit Access Link', 'رابط الدخول للزيارة الفعلي', 'draft', 'Figma VR-092 - Virtual visit - Field label (virtual visit) - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr093', 'Platform', 'المنصة', 'draft', 'Figma VR-093 - Virtual visit - Field label'),
  ('figma.visitreports.vr095', 'Password', 'كلمة السر', 'draft', 'Figma VR-095 - Virtual visit - Field label'),
  ('figma.visitreports.vr097', 'Seizure Record', 'محضر ضبط', 'draft', 'Figma VR-097 - Unable-to-complete - Record type value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-01'),
  ('figma.visitreports.vr098', 'Factory Closed', 'المصنع مغلق', 'draft', 'Figma VR-098 - Unable-to-complete - Reason value'),
  ('figma.visitreports.vr099', 'No permit from the authority; no action taken', 'عدم وجود تصريح من الهيئة ،عدم اتخاذ اجراء', 'draft', 'Figma VR-099 - Unable-to-complete - Reason detail sample - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.visitreports.vr100', 'Attachments', 'المرفقات', 'draft', 'Figma VR-100 - Attachments - Section header'),
  ('figma.visitreports.vr102', 'End the Plan', 'إنهاء الخطة', 'draft', 'Figma VR-102 - Unable-to-complete - Primary CTA'),
  ('figma.identifychallenge.ic001', 'Inspection Details', 'تفاصيل التفتيش', 'draft', 'Figma IC-001 - Challenge screen - Section header'),
  ('figma.identifychallenge.ic002', 'Inspector Name', 'اسم المفتش', 'draft', 'Figma IC-002 - Challenge screen - Field label'),
  ('figma.identifychallenge.ic004', 'Inspection Date', 'تاريخ التفتيش', 'draft', 'Figma IC-004 - Challenge screen - Field label'),
  ('figma.identifychallenge.ic005', 'Evaluation Elements', 'عناصر التقييم', 'draft', 'Figma IC-005 - Challenge screen - Section header - PENDING_LEGAL_NATIVE_REVIEW - see TQ-11'),
  ('figma.identifychallenge.ic006', 'Challenge Details', 'تفاصيل التحدي', 'draft', 'Figma IC-006 - Challenge screen - Section header'),
  ('figma.identifychallenge.ic007', 'Send', 'ارسال', 'draft', 'Figma IC-007 - Submit - Primary CTA (unhamzated variant)'),
  ('figma.report.cr001', 'Select Chemical Release Report', 'اختيار تقرير فسح كيميائي', 'draft', 'Figma CR-001 - Report selection - Annotation/step title - PENDING_LEGAL_NATIVE_REVIEW - see TQ-02'),
  ('figma.report.cr002', 'Basic Data', 'البيانات الأساسية', 'draft', 'Figma CR-002 - Chemical report - Section header'),
  ('figma.report.cr003', 'Chemical Clearance', 'الفسح الكيميائي', 'draft', 'Figma CR-003 - Chemical report - Section header - PENDING_LEGAL_NATIVE_REVIEW - see TQ-02'),
  ('figma.report.cr004', 'Import', 'استيراد', 'draft', 'Figma CR-004 - Chemical report - Clearance type value'),
  ('figma.report.cr005', 'Import Data', 'بيانات الاستيراد', 'draft', 'Figma CR-005 - Chemical report - Section header'),
  ('figma.report.cr006', 'Raw Material Usage', 'استخدام المادة الخام', 'draft', 'Figma CR-006 - Chemical report - Section header'),
  ('figma.report.cr007', 'Was the entire quantity used in the manufacturing process?', 'هل تم استخدام كامل الكمية في العملية التصنيعية؟', 'draft', 'Figma CR-007 - Chemical report - Yes/No question'),
  ('figma.report.cr009', 'Production Data', 'بيانات الإنتاج', 'draft', 'Figma CR-009 - Chemical report - Section header'),
  ('figma.report.cr011', 'Sold Locally', 'البيع محليا', 'draft', 'Figma CR-011 - Chemical report - Disposition value'),
  ('figma.report.cr012', 'Regulatory Status', 'الحالة التنظيمية', 'draft', 'Figma CR-012 - Chemical report - Section header'),
  ('figma.report.cr013', 'Are substances restricted under international conventions used within the establishment?', 'هل يتم استخدام مواد مقيدة في اتفاقيات دولية ضمن المنشأة؟', 'draft', 'Figma CR-013 - Chemical report - Yes/No question - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.report.cr014', 'Chemical Data', 'البيانات الكيميائية', 'draft', 'Figma CR-014 - Chemical report - Section header'),
  ('figma.report.cr015', 'International Conventions', 'الاتفاقيات الدولية', 'draft', 'Figma CR-015 - Chemical report - Section header - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.report.cr016', 'Substance Usage', 'استخدام المادة', 'draft', 'Figma CR-016 - Chemical report - Section header'),
  ('figma.report.cr017', 'Primary Substance', 'مادة أساسية', 'draft', 'Figma CR-017 - Chemical report - Value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.report.cr018', 'Product Data', 'بيانات المنتج', 'draft', 'Figma CR-018 - Chemical report - Section header'),
  ('figma.report.cr019', 'Export Clearance', 'الفسح التصديري', 'draft', 'Figma CR-019 - Chemical report - Section header - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.report.cr020', 'Does the establishment hold a chemical clearance for export?', 'هل المنشأة حاصل على فسح كيميائي للتصدير؟', 'draft', 'Figma CR-020 - Chemical report - Yes/No question - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.report.cr021', 'Export Data', 'بيانات التصدير', 'draft', 'Figma CR-021 - Chemical report - Section header'),
  ('figma.report.cr022', 'Was the entire quantity used for export?', 'هل تم استخدام كامل الكمية في التصدير؟', 'draft', 'Figma CR-022 - Chemical report - Yes/No question'),
  ('figma.report.cr023', 'China', 'الصين', 'draft', 'Figma CR-023 - Chemical report - Country sample value'),
  ('figma.report.cr024', 'Chemical Safety', 'السلامة الكيميائية', 'draft', 'Figma CR-024 - Chemical report - Section header'),
  ('figma.report.cr025', 'Raw Materials', 'المواد الخام', 'draft', 'Figma CR-025 - Tabs - Tab label'),
  ('figma.customsreport.cu001', 'Customs Exemption', 'الإعفاء الجمركي', 'draft', 'Figma CU-001 - Customs report - Section header'),
  ('figma.customsreport.cu002', 'Item Data', 'بيانات البنود', 'draft', 'Figma CU-002 - Customs report - Section header'),
  ('figma.customsreport.cu003', 'Raw Material', 'مادة خام', 'draft', 'Figma CU-003 - Customs report - Item type value'),
  ('figma.customsreport.cu004', 'Utilization Details', 'تفاصيل الاستفادة', 'draft', 'Figma CU-004 - Customs report - Section header - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.customsreport.cu005', 'Was the exemption utilized correctly?', 'هل تم الاستفادة بشكل صحيح؟', 'draft', 'Figma CU-005 - Customs report - Yes/No question - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.customsreport.cu006', 'Final Product', 'منتج نهائي', 'draft', 'Figma CU-006 - Customs report - Item type value'),
  ('figma.customsreport.cu007', 'Photograph the Item', 'تصوير البند', 'draft', 'Figma CU-007 - Customs report - Evidence action label'),
  ('figma.establishmentmanagement.em001', 'Establishments', 'المنشآت', 'draft', 'Figma EM-001 - Establishments list - Page title / tab'),
  ('figma.establishmentmanagement.em002', 'Unlicensed Establishments List', 'قائمة المنشآت غير مرخصة', 'draft', 'Figma EM-002 - Unlicensed list - Annotation/screen title'),
  ('figma.establishmentmanagement.em003', 'Unlicensed Establishment Details', 'تفاصيل المنشأة الغير مرخصة', 'draft', 'Figma EM-003 - Unlicensed details - Screen title'),
  ('figma.establishmentmanagement.em004', 'Responsible Person Phone', 'هاتف المسؤول', 'draft', 'Figma EM-004 - Card fields - Field label'),
  ('figma.establishmentmanagement.em005', 'Responsible Person', 'الشخص المسؤول', 'draft', 'Figma EM-005 - Card fields - Field label'),
  ('figma.establishmentmanagement.em006', 'Last Visit Date', 'تاريخ أخر الزيارة', 'draft', 'Figma EM-006 - Card fields - Field label'),
  ('figma.establishmentmanagement.em007', 'Field Inspector', 'المفتش الميداني', 'draft', 'Figma EM-007 - Card fields - Field label'),
  ('figma.establishmentmanagement.em008', 'Status', 'الحالة', 'draft', 'Figma EM-008 - Status - Field label'),
  ('figma.establishmentmanagement.em009', 'Immediate Closure', 'إغلاق فوري', 'draft', 'Figma EM-009 - Decision values - Enforcement decision value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em011', 'Saved Records (4)', 'السجلات المحفوظة (4)', 'draft', 'Figma EM-011 - Saved records - Section header with count'),
  ('figma.establishmentmanagement.em012', 'Unlicensed establishment data updated successfully.', 'تم تعديل بيانات المنشاة غير مرخصة بنجاح.', 'draft', 'Figma EM-012 - Success toast - Success toast'),
  ('figma.establishmentmanagement.em013', 'Unlicensed establishment created successfully.', 'تم إنشاء بيانات المنشاة غير مرخصة بنجاح.', 'draft', 'Figma EM-013 - Success toast - Success toast'),
  ('figma.establishmentmanagement.em014', 'View Details', 'عرض التفاصيل', 'draft', 'Figma EM-014 - List item - Link/CTA'),
  ('figma.establishmentmanagement.em015', 'Change Establishment Photo', 'تغيير صورة المنشاة', 'draft', 'Figma EM-015 - Photo - CTA'),
  ('figma.establishmentmanagement.em016', 'Basic Data', 'بيانات أساسية', 'draft', 'Figma EM-016 - Sections - Section header'),
  ('figma.establishmentmanagement.em017', 'Visit Location', 'موقع الزيارة', 'draft', 'Figma EM-017 - Sections - Section header'),
  ('figma.establishmentmanagement.em018', 'Visit Details', 'تفاصيل الزيارة', 'draft', 'Figma EM-018 - Sections - Section header'),
  ('figma.establishmentmanagement.em019', 'Action Decision', 'قرار الإجراء', 'draft', 'Figma EM-019 - Decision - Section header - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em020', 'Financial Fine', 'غرامة مالية', 'draft', 'Figma EM-020 - Decision values - Decision option - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em021', 'Refer to Committee', 'تحويل للجنة', 'draft', 'Figma EM-021 - Decision values - Decision option - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em022', 'Final Warning', 'إنذار نهائي', 'draft', 'Figma EM-022 - Decision values - Decision option - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em023', 'Visit Notes', 'ملاحظات الزيارة', 'draft', 'Figma EM-023 - Sections - Section header'),
  ('figma.establishmentmanagement.em024', 'Save Changes', 'حفظ التغييرات', 'draft', 'Figma EM-024 - Actions - Primary CTA'),
  ('figma.establishmentmanagement.em025', 'Add Establishment', 'اضف منشأة', 'draft', 'Figma EM-025 - Actions - Primary CTA'),
  ('figma.establishmentmanagement.em026', 'Edit Unlicensed Establishment Details', 'تعديل تفاصيل المنشأة الغير مرخصة', 'draft', 'Figma EM-026 - Titles - Page title'),
  ('figma.establishmentmanagement.em027', 'Create Unlicensed Establishment', 'إنشاء منشأة غير مرخصة', 'draft', 'Figma EM-027 - Titles - Page title'),
  ('figma.establishmentmanagement.em028', 'Incident Observation Details', 'تفاصيل رصد حادث', 'draft', 'Figma EM-028 - Incident - Screen title - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em029', 'Report an Incident', 'رصد حادث', 'draft', 'Figma EM-029 - Incident - Action - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em030', 'Previous Visits', 'الزيارات السابقة', 'draft', 'Figma EM-030 - Nav - Tab/action'),
  ('figma.establishmentmanagement.em031', 'View Record Attachments', 'عرض مرفقات المحاضر', 'draft', 'Figma EM-031 - Nav - Action - PENDING_LEGAL_NATIVE_REVIEW - see TQ-01'),
  ('figma.establishmentmanagement.em032', 'Start Time', 'وقت البداية', 'draft', 'Figma EM-032 - Visit meta - Field label'),
  ('figma.establishmentmanagement.em033', 'End Time', 'وقت الانتهاء', 'draft', 'Figma EM-033 - Visit meta - Field label'),
  ('figma.establishmentmanagement.em034', 'Record Attachments (6)', 'مرفقات المحاضر (6)', 'draft', 'Figma EM-034 - Attachments - Section header - PENDING_LEGAL_NATIVE_REVIEW - see TQ-01'),
  ('figma.establishmentmanagement.em035', 'View Challenges Report', 'عرض تقرير التحديات', 'draft', 'Figma EM-035 - Challenge report - Action'),
  ('figma.establishmentmanagement.em036', 'Are products exported?', 'هل يتم تصدير منتجات؟', 'draft', 'Figma EM-036 - Assessment Qs - Yes/No question'),
  ('figma.establishmentmanagement.em037', 'Does the company have a loan from the Industrial Development Fund?', 'هل لدى الشركة قرض من صندوق التنمية الصناعي؟', 'draft', 'Figma EM-037 - Assessment Qs - Yes/No question - PENDING_LEGAL_NATIVE_REVIEW - see TQ-06'),
  ('figma.establishmentmanagement.em038', 'What is the company capital?', 'كم يبلغ رأس مال الشركة', 'draft', 'Figma EM-038 - Assessment Qs - Question'),
  ('figma.establishmentmanagement.em039', 'Is there an approved expansion plan for the current or next year?', 'هل هناك خطة معتمدة للتوسع في السنة الحالية أو القادمة؟', 'draft', 'Figma EM-039 - Assessment Qs - Yes/No question'),
  ('figma.establishmentmanagement.em040', 'Has the company won government supply contracts?', 'هل فازت الشركة بعقود توريد حكومية؟', 'draft', 'Figma EM-040 - Assessment Qs - Yes/No question'),
  ('figma.establishmentmanagement.em041', 'Challenge Status', 'حالة التحدي', 'draft', 'Figma EM-041 - Challenge - Field label'),
  ('figma.establishmentmanagement.em042', 'Challenge Description', 'وصف التحدي', 'draft', 'Figma EM-042 - Challenge - Field label'),
  ('figma.establishmentmanagement.em045', 'Actions', 'الاجراءت', 'draft', 'Figma EM-045 - Actions panel - Panel title'),
  ('figma.establishmentmanagement.em046', 'Establishment Code', 'رمز المنشأة', 'draft', 'Figma EM-046 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em047', 'Commercial Registration Number', 'رقم السجل التجاري', 'draft', 'Figma EM-047 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em048', 'Report Source', 'مصدر البلاغ', 'draft', 'Figma EM-048 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em049', 'Reporter Name', 'اسم المُبلِّغ', 'draft', 'Figma EM-049 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em050', 'Reporter Contact Number', 'رقم تواصل المُبلِّغ', 'draft', 'Figma EM-050 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em051', 'Report Time', 'وقت البلاغ', 'draft', 'Figma EM-051 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em052', 'Number of Cases', 'عدد الحالات', 'draft', 'Figma EM-052 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em053', 'No fatalities or injuries', 'لا يوجد وفيات او اصابات', 'draft', 'Figma EM-053 - Incident values - Value'),
  ('figma.establishmentmanagement.em054', 'Resulting Damage', 'الأضرار الناجمة', 'draft', 'Figma EM-054 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em055', 'Hazardous material leak', 'تسريب مواد خطرة', 'draft', 'Figma EM-055 - Incident values - Value'),
  ('figma.establishmentmanagement.em056', 'Environmental pollution', 'تلوث بيئي', 'draft', 'Figma EM-056 - Incident values - Value'),
  ('figma.establishmentmanagement.em057', 'Incident Type', 'نوع الحادث', 'draft', 'Figma EM-057 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em058', 'Equipment incident', 'حادث معدات', 'draft', 'Figma EM-058 - Incident values - Value'),
  ('figma.establishmentmanagement.em059', 'Preliminary Incident Description', 'وصف مبدئي للحادث', 'draft', 'Figma EM-059 - Incident fields - Field label'),
  ('figma.establishmentmanagement.em061', 'Recorded Violation Details', 'تفاصيل مخالفة مسجلة', 'draft', 'Figma EM-061 - Violation record - Screen title'),
  ('figma.establishmentmanagement.em062', 'Violation Date', 'تاريخ المخالفة', 'draft', 'Figma EM-062 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em063', 'Request Number', 'رقم الطلب', 'draft', 'Figma EM-063 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em064', 'Field Supervisor', 'المشرف الميداني', 'draft', 'Figma EM-064 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em065', 'Penalty Execution', 'تنفيذ جزاء', 'draft', 'Figma EM-065 - Violation values - Visit type value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em066', 'Day Counter', 'عداد الأيام', 'draft', 'Figma EM-066 - Violation fields - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em067', 'Time Limit', 'المهلة الزمنية', 'draft', 'Figma EM-067 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em068', 'Correction Date', 'تاريخ التصحيح', 'draft', 'Figma EM-068 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em069', 'Actions', 'الاجراءات', 'draft', 'Figma EM-069 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em070', 'Worker training', 'تدريب العاملين', 'draft', 'Figma EM-070 - Violation values - Corrective action value'),
  ('figma.establishmentmanagement.em071', 'Inspection Notes', 'ملاحظات التفتيش', 'draft', 'Figma EM-071 - Violation fields - Field label'),
  ('figma.establishmentmanagement.em072', 'Failure to provide protective equipment', 'عدم توفير معدات الحماية', 'draft', 'Figma EM-072 - Violation values - Violation value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em073', 'Start Inspection Plan', 'بدء خطة تفتيش', 'draft', 'Figma EM-073 - Actions - CTA'),
  ('figma.establishmentmanagement.em074', 'Create Incident Observation', 'إنشاء رصد حادث', 'draft', 'Figma EM-074 - Actions - CTA - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em075', 'Previous Violations', 'المخالفات السابقة', 'draft', 'Figma EM-075 - Actions - Tab/action'),
  ('figma.establishmentmanagement.em076', 'Violations', 'المخالفات', 'draft', 'Figma EM-076 - Nav - Page title'),
  ('figma.establishmentmanagement.em077', 'Air Quality Regulation', 'لائحة جودة الهواء', 'draft', 'Figma EM-077 - Violation table - Regulation value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em078', 'Critical Violation', 'مخالفة حرجة', 'draft', 'Figma EM-078 - Violation table - Severity value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em079', 'Exceeding gas emission limits', 'تجاوز حدود الانبعاثات الغازية', 'draft', 'Figma EM-079 - Violation table - Violation value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em080', 'Implement a correction plan and train workers', 'تنفيذ خطة تصحيح وتدريب العاملين', 'draft', 'Figma EM-080 - Violation table - Corrective action'),
  ('figma.establishmentmanagement.em081', 'Establishment Management', 'إدارة المنشآت', 'draft', 'Figma EM-081 - Issue violation - Module title'),
  ('figma.establishmentmanagement.em082', 'Issue Violation', 'إصدار مخالفة', 'draft', 'Figma EM-082 - Issue violation - Flow title'),
  ('figma.establishmentmanagement.em083', 'Select Violations', 'تحديد المخالفات', 'draft', 'Figma EM-083 - Issue violation - Step title / CTA'),
  ('figma.establishmentmanagement.em084', 'Clear Selection', 'إلغاء الاختيار', 'draft', 'Figma EM-084 - Issue violation - Secondary CTA'),
  ('figma.establishmentmanagement.em085', 'View Violations', 'عرض المخالفات', 'draft', 'Figma EM-085 - Issue violation - Action'),
  ('figma.establishmentmanagement.em086', 'Please select the appropriate violations for the selected establishments.', 'يرجى اختيار المخالفات المناسبة للمنشآت المختارة.', 'draft', 'Figma EM-086 - Issue violation - Helper text'),
  ('figma.establishmentmanagement.em087', 'Search Violations', 'البحث عن المخالفة', 'draft', 'Figma EM-087 - Issue violation - Search placeholder'),
  ('figma.establishmentmanagement.em088', 'Confirm Violation', 'تاكيد المخالفة', 'draft', 'Figma EM-088 - Issue violation - CTA / step'),
  ('figma.establishmentmanagement.em089', 'Non-compliance with wearing safety equipment', 'عدم الالتزام بارتداء معدات السلامة', 'draft', 'Figma EM-089 - Violation catalog - Violation value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-04'),
  ('figma.establishmentmanagement.em090', 'Environmental Protection System Regulation', 'لائحة نظام حماية البيئة', 'draft', 'Figma EM-090 - Violation catalog - Regulation value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em091', 'Medium Violation', 'مخالفة متوسطة', 'draft', 'Figma EM-091 - Violation catalog - Severity value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em092', 'Written Warning', 'إنذار كتابي', 'draft', 'Figma EM-092 - Violation catalog - Penalty value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em093', 'Industrial Control Department', 'إدارة الرقابة الصناعية', 'draft', 'Figma EM-093 - Violation catalog - Department value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em094', 'Article Three (establishment obligation for waste management)', 'البند الثالث (التزام المنشأة بإدارة النفايات)', 'draft', 'Figma EM-094 - Violation catalog - Regulation article - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em095', 'Exemption Details', 'تفاصيل الإعفاء', 'draft', 'Figma EM-095 - Regulatory statuses - Modal title'),
  ('figma.establishmentmanagement.em096', 'Chemical Clearance Details', 'تفاصيل الفسح الكميائي', 'draft', 'Figma EM-096 - Regulatory statuses - Modal title - PENDING_LEGAL_NATIVE_REVIEW - see TQ-02'),
  ('figma.establishmentmanagement.em097', 'Document Name', 'اسم الوثيقة', 'draft', 'Figma EM-097 - Documents - Field label'),
  ('figma.establishmentmanagement.em098', 'Environmental construction permit from the National Center for Environmental Compliance', 'تصريح بيئي للإنشاء من المركز الوطني للرقابة', 'draft', 'Figma EM-098 - Documents - Sample document name - PENDING_LEGAL_NATIVE_REVIEW - see TQ-06'),
  ('figma.establishmentmanagement.em099', 'Document Copy', 'نسخة الوثيقة', 'draft', 'Figma EM-099 - Documents - Field label'),
  ('figma.establishmentmanagement.em100', 'No copy has been uploaded for this document.', 'لا توجد نسخة مرفوعة لهذه الوثيقة.', 'draft', 'Figma EM-100 - Documents - Empty state'),
  ('figma.establishmentmanagement.em101', 'Product Name', 'اسم المنتج', 'draft', 'Figma EM-101 - Exemption fields - Field label'),
  ('figma.establishmentmanagement.em103', 'Licensed Quantity', 'الكمية المرخصة', 'draft', 'Figma EM-103 - Exemption fields - Field label'),
  ('figma.establishmentmanagement.em104', 'Approved Quantity', 'الكمية المعتمدة', 'draft', 'Figma EM-104 - Exemption fields - Field label'),
  ('figma.establishmentmanagement.em105', 'Exemption Status', 'حالة الإعفاء', 'draft', 'Figma EM-105 - Exemption fields - Field label'),
  ('figma.establishmentmanagement.em106', 'Last Exemption Date', 'تاريخ آخر إعفاء', 'draft', 'Figma EM-106 - Exemption fields - Field label'),
  ('figma.establishmentmanagement.em107', 'Chemical Clearance Status', 'حالة الفسح الكيميائي', 'draft', 'Figma EM-107 - Chemical fields - Field label'),
  ('figma.establishmentmanagement.em108', 'Request Type', 'نوع الطلب', 'draft', 'Figma EM-108 - Chemical fields - Field label'),
  ('figma.establishmentmanagement.em109', 'Unrestricted chemical clearances', 'فسوحات كيميائية غير مقيدة', 'draft', 'Figma EM-109 - Chemical fields - Value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em110', 'Last Chemical Clearance Date', 'تاريخ آخر فسح كيميائي', 'draft', 'Figma EM-110 - Chemical fields - Field label'),
  ('figma.establishmentmanagement.em112', 'View Visit Report — Al-Amal Workers Training Company', 'عرض تقرير زيارة شركة الامل للتدريب العمال', 'draft', 'Figma EM-112 - View report - Page title'),
  ('figma.establishmentmanagement.em113', 'Visit Location Address', 'عنوان موقع الزيارة', 'draft', 'Figma EM-113 - Report meta - Field label'),
  ('figma.establishmentmanagement.em114', 'Location', 'الموقع', 'draft', 'Figma EM-114 - Report meta - Field label'),
  ('figma.establishmentmanagement.em115', 'Location matches the registered one', 'الموقع متطابق مع المسجّل', 'draft', 'Figma EM-115 - Report meta - Location-match status'),
  ('figma.establishmentmanagement.em116', 'Location does not match the record', 'الموقع غير متطابق مع السجل', 'draft', 'Figma EM-116 - Report meta - Location-mismatch status'),
  ('figma.establishmentmanagement.em117', 'Comprehensive media coverage', 'تغطية إعلامية شاملة', 'draft', 'Figma EM-117 - Report meta - Sample value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-08'),
  ('figma.establishmentmanagement.em118', 'Visit Report', 'تقرير زيارة', 'draft', 'Figma EM-118 - Report types - Report type value'),
  ('figma.establishmentmanagement.em119', 'Safety Report', 'تقرير سلامة', 'draft', 'Figma EM-119 - Report types - Report type value'),
  ('figma.establishmentmanagement.em120', 'Challenge Observation', 'رصد تحدي', 'draft', 'Figma EM-120 - Report types - Report type value - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em121', 'Chemical Clearance', 'فسح كيميائي', 'draft', 'Figma EM-121 - Report types - Report type value - PENDING_LEGAL_NATIVE_REVIEW - see TQ-02'),
  ('figma.establishmentmanagement.em123', 'Record Type', 'نوع المحضر', 'draft', 'Figma EM-123 - Record view - Field label - PENDING_LEGAL_NATIVE_REVIEW - see TQ-01'),
  ('figma.establishmentmanagement.em124', 'Reason for Non-Execution', 'سبب عدم التنفيذ', 'draft', 'Figma EM-124 - Record view - Field label'),
  ('figma.establishmentmanagement.em125', 'No permit from the authority', 'عدم وجود تصريح من الهيئة', 'draft', 'Figma EM-125 - Record view - Violation sample - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em126', 'Item Status', 'حالة البند', 'draft', 'Figma EM-126 - Item view - Field label'),
  ('figma.establishmentmanagement.em127', 'Item Type', 'نوع البند', 'draft', 'Figma EM-127 - Item view - Field label'),
  ('figma.establishmentmanagement.em128', 'Licenses and Permits', 'التراخيص والتصاريح', 'draft', 'Figma EM-128 - Item view - Item category'),
  ('figma.establishmentmanagement.em129', 'Item Number', 'رقم البند', 'draft', 'Figma EM-129 - Item view - Field label'),
  ('figma.establishmentmanagement.em130', 'Corrective Action', 'الإجراء التصحيحي', 'draft', 'Figma EM-130 - Item view - Field label'),
  ('figma.establishmentmanagement.em132', 'Corrective Grace Period', 'المهلة التصحيحية', 'draft', 'Figma EM-132 - Item view - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em133', 'Penalties', 'الجزاءات', 'draft', 'Figma EM-133 - Item view - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em134', 'No penalties currently recorded.', 'لا توجد جزاءات مسجلة حاليًا.', 'draft', 'Figma EM-134 - Item view - Empty state'),
  ('figma.establishmentmanagement.em135', 'Energy Type Used', 'نوع الطاقة المستخدمة', 'draft', 'Figma EM-135 - Establishment data - Field label'),
  ('figma.establishmentmanagement.em136', 'Establishment Site Supervision', 'الاشراف المكاني للمنشاة', 'draft', 'Figma EM-136 - Establishment data - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em137', 'Production Status', 'الحالة الإنتاجية', 'draft', 'Figma EM-137 - Establishment data - Field label'),
  ('figma.establishmentmanagement.em138', 'Government Authority That Performed the Closure', 'الجهة الحكومية التي قامت بالإغلاق', 'draft', 'Figma EM-138 - Establishment data - Field label'),
  ('figma.establishmentmanagement.em139', 'Establishment Status Justification', 'مبرر حالة المنشأة', 'draft', 'Figma EM-139 - Establishment data - Field label'),
  ('figma.establishmentmanagement.em140', 'Contact Person Name (1)', 'اسم مسؤول التواصل (1)', 'draft', 'Figma EM-140 - Contacts - Field label'),
  ('figma.establishmentmanagement.em141', 'Grand Total', 'المجموع الكلي', 'draft', 'Figma EM-141 - Workforce - Table footer'),
  ('figma.establishmentmanagement.em142', 'Registered Total', 'إجمالي المسجل', 'draft', 'Figma EM-142 - Workforce - Table footer'),
  ('figma.establishmentmanagement.em143', 'Number of Utilized Items', 'عدد البنود المستفاد منها', 'draft', 'Figma EM-143 - Items data - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em144', 'Item Name', 'اسم البند', 'draft', 'Figma EM-144 - Items data - Field label'),
  ('figma.establishmentmanagement.em146', 'Number of Exempted Items', 'عدد البنود المعفاة', 'draft', 'Figma EM-146 - Items data - Field label'),
  ('figma.establishmentmanagement.em147', 'Utilization Method', 'طريقة الاستفادة', 'draft', 'Figma EM-147 - Utilization - Field label - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em148', 'Verification Method', 'طريقة التحقيق', 'draft', 'Figma EM-148 - Utilization - Field label - PENDING_LEGAL_NATIVE_REVIEW - see TQ-12'),
  ('figma.establishmentmanagement.em149', 'Competent Department', 'الإدارة المختصة', 'draft', 'Figma EM-149 - Specialization - Field label'),
  ('figma.establishmentmanagement.em151', 'International Harmonized Code (390110)', 'الرمز المنسق الدولي (390110)', 'draft', 'Figma EM-151 - Products list - Field value'),
  ('figma.establishmentmanagement.em158', 'Various general administrative and office occupations', 'مهن إدارية ومكتبية عامة متعددة', 'draft', 'Figma EM-158 - Checklist - Occupations sample - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em159', 'If "Stopped/Closed/Repair/Relocation" is selected, the establishment-status justification and closing government-authority selections appear', 'في حالة اختيار "متوقف/مغلق/إصلاح/نقل" يتم ظهور اختيار مبرر حالة المنشأة و الجهة الحكومية التي قامت بالإغلاق', 'draft', 'Figma EM-159 - Annotation - Conditional-logic annotation - PENDING_LEGAL_NATIVE_REVIEW'),
  ('figma.establishmentmanagement.em171', 'Note Text', 'نص الملاحظة', 'draft', 'Figma EM-171 - Notes - Field label'),
  ('figma.establishmentmanagement.em172', 'View Visit Report', 'عرض تقرير الزيارة', 'draft', 'Figma EM-172 - Report view - Action'),
  ('figma.establishmentmanagement.em173', 'Visit Access Link', 'رابط الدخول للزيارة', 'draft', 'Figma EM-173 - Virtual - Field label')
on conflict (key) do update
  set ar = excluded.ar, en = excluded.en, context = excluded.context
  where ui_strings.status = 'draft';   -- never clobber a human-reviewed translation
