// Reviewed MSA interface fallbacks for PKT-RESPONSIVE-ADMIN-RBAC-008.
// Governed ui_strings values still take precedence. These strings describe UI
// and access behavior only; they introduce no legal, risk, SLA or policy value.
export const ADMIN_RBAC_AR_FALLBACK: Record<string, string> = {
  "admin.unauthorized.title": "الوصول إلى الإدارة مقيّد",
  "admin.unauthorized.heading": "ليس لديك صلاحية الوصول إلى هذه الوجهة",
  "admin.unauthorized.body": "يبقى قسم الإدارة ظاهراً لتوضيح بنية النظام، لكن دورك المسند لا يصرح بتحميل بيانات الإدارة.",
  "admin.unauthorized.return": "العودة إلى المساحة المصرح بها",
  "admin.unauthorized.destinationTitle": "الوصول إلى الإدارة مقيّد",
  "admin.unauthorized.destinationHeading": "ليس لديك صلاحية الوصول إلى هذه الوجهة",
  "admin.unauthorized.destinationBody": "يبقى قسم الإدارة ظاهراً لتوضيح بنية النظام، لكن دورك المسند لا يصرح بتحميل بيانات الإدارة.",
  "admin.unauthorized.destinationReturn": "العودة إلى المساحة المصرح بها",
  "admin.access.users.title": "المستخدمون والأدوار",
  "admin.access.roles.title": "الأدوار وملفات الصلاحيات",
  "admin.access.views.label": "طرق عرض إدارة الوصول",
  "admin.access.views.users": "المستخدمون",
  "admin.access.views.roles": "الأدوار",
  "admin.access.views.reviews": "مراجعة الوصول",
  "admin.access.views.devices": "الأجهزة الموثوقة",
  "admin.access.breadcrumb.admin": "الإدارة",
  "admin.access.breadcrumb.people": "المستخدمون والوصول",
  "admin.access.summary.visibleAccounts": "الحسابات الظاهرة",
  "admin.access.summary.canonicalRoles": "الأدوار المعتمدة",
  "admin.access.summary.management": "إدارة الوصول",
  "admin.access.summary.available": "متاحة",
  "admin.access.summary.readOnly": "للقراءة فقط",
  "admin.access.banner.title": "توجد ثلاثة أدوار معتمدة: المخطط والمفتش والمسؤول.",
  "admin.access.banner.body": "تظل ملفات الصلاحيات الداخلية منفصلة للمحافظة على أقل قدر من الصلاحيات. تُسجل التغييرات، وتصبح نافذة عند الطلب التالي، وتُرفض محاولة رفع المستخدم لصلاحياته الذاتية.",
  "admin.access.canonicalBanner.title": "توجد ثلاثة أدوار معتمدة: المخطط والمفتش والمسؤول.",
  "admin.access.canonicalBanner.body": "تظل ملفات الصلاحيات الداخلية منفصلة للمحافظة على أقل قدر من الصلاحيات. تُسجل التغييرات، وتصبح نافذة عند الطلب التالي، وتُرفض محاولة رفع المستخدم لصلاحياته الذاتية.",
  "admin.access.permissions.error.title": "تعذر التحقق من الصلاحيات.",
  "admin.access.permissions.error.body": "تعذر التحقق من صلاحيات إدارة الوصول. جميع عناصر التغيير غير متاحة؛ أعد تحميل الصفحة.",
  "admin.access.error.title": "تعذر تحميل قائمة المستخدمين المصرح بها. لم يتغير أي شيء. حاول مرة أخرى.",
  "admin.access.roles.error.title": "تفاصيل الأدوار غير متاحة.",
  "admin.access.roles.error.body": "تظل قائمة المستخدمين المصرح بها ظاهرة، لكن مسميات الأدوار وجميع تغييرات الوصول غير متاحة.",
  "admin.access.table.user": "المستخدم",
  "admin.access.table.email": "البريد الإلكتروني",
  "admin.access.table.region": "المنطقة",
  "admin.access.table.roles": "الأدوار المعتمدة",
  "admin.access.table.noRole": "لا يوجد دور داخلي معتمد",
  "admin.access.rlsNote.manage": "تعرض هذه القائمة النطاق المصرح لك به فقط. تُنفذ تغييرات الوصول من خلال الإجراءات المحكومة حصراً.",
  "admin.access.rlsNote": "تعرض هذه القائمة النطاق المصرح لك به فقط. هذه الشاشة للقراءة فقط.",
  "admin.access.roles.catalogue.title": "الأدوار المعتمدة",
  "admin.access.roles.catalogue.body": "تعرض الواجهة ثلاثة أدوار معتمدة فقط. تبقى ملفات الصلاحيات الحالية منفصلة خلف هذا العرض للحفاظ على جميع حدود التفويض والتدقيق.",
  "admin.access.roles.catalogue.error": "تعذر تحميل دليل الأدوار المصرح به. لا تتوفر أي عناصر تحكم.",
  "admin.access.roles.admin": "ملف صلاحيات المسؤول",
  "admin.access.roles.profiles": "ملفات الصلاحيات المتوافقة",
  "admin.access.roles.direct": "دور مباشر",
  "admin.access.roles.fieldGate": "تظل قناة المفتش الميدانية محكومة بقرار الوصول المعتمد.",
  "admin.access.roles.leastPrivilege": "لا يمنح دور المسؤول صلاحية شاملة؛ يظل كل ملف صلاحيات مقيداً بضوابطه الحالية.",
  "admin.access.manage.title": "إدارة الوصول",
  "admin.access.manage.intro": "امنح الأدوار أو ألغها، وأدر منح الصلاحيات المباشرة. تعيد الإجراءات المحكومة التحقق من هوية المنفذ، وتمنع رفع الصلاحيات الذاتية وإلغاء آخر مسؤول أمني، وتسجل كل تغيير.",
  "admin.access.manage.selectUser": "اختيار مستخدم",
  "admin.access.manage.roles": "ملفات الأدوار المسندة",
  "admin.access.manage.grantedAt": "مُنح في",
  "admin.access.manage.grantRole": "منح ملف دور",
  "admin.access.manage.revoke": "إلغاء",
  "admin.access.manage.confirmRevokeRole": "هل تريد إلغاء ملف الدور «{key}» من هذا المستخدم؟ يُسجل التغيير ويصبح نافذاً عند الطلب التالي.",
  "admin.access.manage.confirmGrantAdminRole": "هل تريد منح ملف المسؤول «{key}» لهذا المستخدم؟ يُسجل التغيير ويظل مقيداً بصلاحيات الملف.",
  "admin.access.manage.confirmRevokeCapability": "هل تريد إلغاء منحة الصلاحية المباشرة «{key}» من هذا المستخدم؟ لا تتأثر الصلاحيات المشتقة من الأدوار.",
  "admin.access.manage.confirm": "تأكيد",
  "admin.access.manage.capabilities": "الصلاحيات الفعلية",
  "admin.access.manage.capabilitiesHint": "الصلاحيات الفعلية للمستخدم مشتقة من ملفات أدواره ومنح الصلاحيات المباشرة، مع بيان مصدر كل صلاحية.",
  "admin.access.manage.viaRole": "عبر ملف الدور:",
  "admin.access.manage.directGrant": "منحة مباشرة",
  "admin.access.manage.grantCapability": "منح صلاحية مباشرة",
  "admin.access.manage.noCapabilities": "لا توجد لهذا المستخدم صلاحيات فعلية حالياً.",
  "admin.access.manage.selfTarget": "هذا حسابك. تمنع ضوابط رفع الصلاحيات الذاتية تغييرك لوصولك بنفسك؛ يجب أن ينفذ التغيير مسؤول أمني آخر.",
  "admin.access.manage.effectNote": "تصبح تغييرات الأدوار والصلاحيات نافذة عند طلب المستخدم التالي. يُؤكد كل تغيير هنا ويُسجل مع المنفذ والحالة السابقة واللاحقة والمرجع EXE-ACCESS.",
  "admin.access.manage.working": "جارٍ التطبيق…",
  "admin.access.manage.saved": "تم الحفظ — يصبح نافذاً عند طلب المستخدم التالي",
  "admin.access.manage.error.title": "بعض تفاصيل الوصول غير متاحة.",
  "admin.access.manage.error.body": "تظل قائمة المستخدمين ظاهرة، لكن تغييرات الوصول غير متاحة لتعذر قراءة مصدر محكوم واحد أو أكثر.",
  "admin.access.manage.capabilityColumn": "الصلاحية",
  "admin.access.manage.sourceColumn": "المصدر",
  "admin.access.manage.actionsColumn": "الإجراءات",
  "admin.access.rolecaps.title": "صلاحيات ملفات الأدوار",
  "admin.access.rolecaps.intro": "امنح صلاحية لملف دور كامل أو ألغها. تمنع الضوابط رفع الصلاحيات الذاتية، وتظل سياسات RLS الخاصة بالمسؤول الأمني هي سلطة الكتابة.",
  "admin.access.rolecaps.selectRole": "اختيار ملف دور",
  "admin.access.rolecaps.granted": "الصلاحيات الممنوحة",
  "admin.access.rolecaps.none": "لا توجد منح صلاحيات لهذا الملف حالياً.",
  "admin.access.rolecaps.grant": "منح صلاحية للملف",
  "admin.access.rolecaps.confirmRevoke": "هل تريد إلغاء «{permission}» من جميع المستخدمين الذين يحملون ملف الدور «{role}»؟ يصبح التغيير نافذاً عند طلبهم التالي.",
  "admin.access.rolecaps.confirmGrantSod": "هل تريد منح صلاحية فصل المهام admin.access.manage لملف الدور «{role}»؟ سيتمكن حاملوه عندئذ من تغيير الوصول.",
  "admin.access.rolecaps.auditNote": "ملاحظة التدقيق: تُسجل تغييرات أدوار المستخدمين بواسطة مشغل التدقيق الحالي. لا يُدعى تطبيق تدقيق صلاحيات ملفات الأدوار دون دليل بيئي.",
  "admin.access.rolecaps.error.title": "تفاصيل صلاحيات ملفات الأدوار غير متاحة.",
  "admin.access.rolecaps.error.body": "يظل دليل الأدوار ظاهراً، لكن تغييرات الصلاحيات غير متاحة لتعذر قراءة مصدر محكوم.",
};
