/** Reviewed Virtual Visit media-room fallback copy. Live ui_strings override it. */
export const VIRTUAL_AR_FALLBACK: Record<string, string> = {
  "field.ws.completion.tasks": "العودة إلى لوحة المعلومات",
  "virtual.stage.title": "غرفة التفتيش",
  "virtual.stage.statusReady": "جاهزة للاتصال",
  "virtual.stage.statusNotReady": "لا يمكن لأحد الانضمام بعد",
  "virtual.stage.stateConnected": "متصل",
  "virtual.stage.stateLocalOnly": "أجهزتك فقط",
  "virtual.stage.stateUnavailable": "الغرفة غير متاحة",
  "virtual.stage.remoteWaiting": "لا يوجد شخص آخر في الغرفة بعد.",
  "virtual.stage.remoteRepRoute": "ينضم ممثل المنشأة عبر جلسته الموثقة المسندة إليه.",
  "virtual.stage.remoteUnavailable": "خدمة الفيديو غير مهيأة في هذه البيئة.",
  "virtual.stage.remoteUnavailableReason": "تبقى الكاميرا والميكروفون ومشاركة الشاشة متاحة لفحص الجهاز محليًا.",
  "virtual.stage.selfView": "معاينة الكاميرا",
  "virtual.stage.cameraOff": "الكاميرا متوقفة",
  "virtual.stage.cameraOn": "الكاميرا تعمل",
  "virtual.stage.micOff": "الميكروفون متوقف",
  "virtual.stage.micOn": "الميكروفون يعمل",
  "virtual.stage.share": "مشاركة الشاشة",
  "virtual.stage.shareStop": "إيقاف المشاركة",
  "virtual.stage.leave": "مغادرة الغرفة",
  "virtual.stage.stopDevices": "إيقاف أجهزتي",
  "virtual.stage.sharingLabel": "مشاركة الشاشة",
  "virtual.stage.note": "تُحرر الأجهزة عند المغادرة أو إغلاق الصفحة. لا توجد مكالمة محاكاة هنا.",
  "virtual.stage.errDenied": "رُفض إذن الكاميرا أو الميكروفون. اسمح بالوصول من إعدادات المتصفح ثم أعد المحاولة.",
  "virtual.stage.errNotFound": "لم يتم العثور على كاميرا أو ميكروفون مناسب.",
  "virtual.stage.errBusy": "الكاميرا أو الميكروفون مستخدم من تطبيق آخر.",
  "virtual.stage.errUnsupported": "هذا المتصفح لا يدعم خاصية الوسائط المطلوبة.",
  "virtual.stage.errGeneric": "تعذر فتح الجهاز. تحقّق منه ثم أعد المحاولة.",
  "virtual.stage.join": "الانضمام إلى الغرفة",
  "virtual.stage.joining": "جارٍ الانضمام…",
  "virtual.stage.stateNotJoined": "غير متصل",
  "virtual.stage.joinedWith": "متصل مع {n} مشارك",
  "virtual.stage.joinedAlone": "متصل — بانتظار المشارك",
  "virtual.stage.errJoin": "تعذر الانضمام إلى غرفة الفيديو المحكومة. أعد المحاولة أو الجدولة أو صعّد؛ لا يوجد تجاوز.",
};
